/* A gentle home for a pet and a six-plot vegetable garden. Progress stays on this device. */
(function(root){
'use strict';
const KEY='kid-cozy-home-v1';
const pets=[['bunny','🐰','棉花兔'],['kitten','🐱','奶糖猫'],['puppy','🐶','布丁狗'],['bunny-peach','🐰','桃桃兔'],['bunny-cloud','🐰','云朵兔'],['kitten-orange','🐱','橘子猫'],['kitten-moon','🐱','月亮猫'],['puppy-cookie','🐶','曲奇狗'],['puppy-cocoa','🐶','可可狗']];

const PET_CHAT=[
 ['吃得香香的，谢谢你。我慢慢嚼，把肚子照顾好。你吃饭的时候，也记得坐稳、慢慢吃哦。','这一口真好吃。我想和你分享一个秘密：按时吃饭，我就有力气跳跳跑跑啦。','我的小肚子圆圆的，好满足。谢谢你照顾我，接下来我们一起休息一小会儿吧。'],
 ['泡泡把小爪子洗干净啦，真舒服。谢谢你动作这么轻，我喜欢被温柔地照顾。','洗完澡，我要把毛毛擦干，别着凉。你洗完手，也记得用自己的小毛巾擦干哦。','我现在香香软软的，想送给你一个小笑脸。你愿意轻轻摸摸我的头吗？'],
 ['球滚过来啦，我追到了。和你轮流玩真开心，下次换你先来，好吗？','跳一跳，停一停，我们一起深呼吸。玩累了就喝一点水，休息一下。','谢谢你陪我。我开心的时候会摇尾巴、眯眼睛。你开心的时候，会怎么笑呢？']
];
const crops=[['carrot','🥕','胡萝卜'],['tomato','🍅','番茄'],['corn','🌽','玉米'],['strawberry','🍓','草莓']];
const fresh=()=>({pet:'bunny',care:[0,0,0],careByPet:{},plots:Array.from({length:6},()=>({crop:null,stage:0})),basket:0,stars:0});
function load(){let d;try{d=JSON.parse(root.localStorage.getItem(KEY)||'null')}catch{}const v=fresh();if(!d||typeof d!=='object')return v;v.pet=pets.some(p=>p[0]===d.pet)?d.pet:v.pet;v.care=v.care.map((_,i)=>Math.min(3,Math.max(0,Math.floor(Number(d.care?.[i])||0))));v.plots=v.plots.map((p,i)=>{const a=d.plots?.[i];return a&&crops.some(c=>c[0]===a.crop)?{crop:a.crop,stage:Math.min(3,Math.max(1,Math.floor(Number(a.stage)||1)))}:p});for(const pet of pets){const care=d.careByPet?.[pet[0]];if(Array.isArray(care))v.careByPet[pet[0]]=[0,1,2].map(i=>Math.min(3,Math.max(0,Math.floor(Number(care[i])||0))));}if(v.careByPet[v.pet])v.care=v.careByPet[v.pet].slice();v.basket=Math.min(9999,Math.max(0,Math.floor(Number(d.basket)||0)));v.stars=Math.min(9999,Math.max(0,Math.floor(Number(d.stars)||0)));return v}
let data=load(),careTurns=[0,0,0],seed='carrot',tool='seed',notice='',petScene='home',courtIndex=-1,reaction=null,reactionTimer=null;
function react(kind,index=-1,icon=''){reaction={kind,index,icon,until:Date.now()+(index===-1?9000:5000)}}
function currentReaction(){return reaction&&reaction.until>Date.now()?reaction:null}
function save(){data.careByPet[data.pet]=data.care.slice();try{root.localStorage.setItem(KEY,JSON.stringify(data));return true}catch{notice='设备空间不足，这次进度暂时不能保存。';return false}}
function say(text){root.speak?.(text)}
function update(text){notice=text;save();root.render?.();say(notice)}
function nav(title,icon){return `<div class="mini-game-nav"><button class="game-exit" onclick="COZY.leave()"><span>🏠</span><b>回到乐园</b></button><div class="mini-game-name"><span>${icon}</span><b>${title}</b></div><button class="round-btn" onclick="COZY.help()" aria-label="听玩法">🔊</button></div>`}
function petMood(){return data.care[0]===3?'full':data.care[2]===0?'lonely':'happy'}
function petArt(){
 const p=pets.find(item=>item[0]===data.pet);
 return root.PET_CHARACTER.render({id:data.pet,name:p[2],mood:petMood(),action:currentReaction()?.kind||'idle'});
}
function petReward(){return data.care.every(value=>value===3)?'<div class="pet-complete-badge" role="status">🌟 三项照顾完成啦</div>':''}

function sceneSvg(body){return `<svg viewBox="0 0 600 360" aria-hidden="true">${body}</svg>`}
function renderPetScene(){
 if(petScene==='home')return `<div class="pet-room room-action-idle"><div class="room-bowl" aria-hidden="true">🥣</div><div class="room-ball" aria-hidden="true">🎾</div><div class="pet-roamer"><div class="pet-walking-body">${petArt()}</div></div><div class="room-caption">${petMood()==='full'?'吃饱啦，摸摸圆肚肚':petMood()==='lonely'?'想和你玩一会儿':'和你在一起真开心'}</div>${petReward()}</div>`;
 const r=currentReaction(),active=!!r,court=['basketball','football','tennis'][Math.max(0,courtIndex)%3],sport=petScene==='sport',title=petScene==='dining'?'暖暖餐厅':petScene==='bath'?'泡泡浴室':{basketball:'篮球场',football:'足球场',tennis:'网球场'}[court];
 let props='';
 if(petScene==='dining'){
  props='<div class="scene-chair">'+sceneSvg('<rect x="198" y="28" width="204" height="240" rx="50" fill="#daa5a0" stroke="#fff0df" stroke-width="14"/><path d="M236 63V190M300 63V190M364 63V190" stroke="#ecc2b0" stroke-width="12" stroke-linecap="round"/><path d="M215 235V338M385 235V338" stroke="#bf8b79" stroke-width="24"/><rect x="185" y="225" width="230" height="43" rx="18" fill="#f0c4aa"/>')+'</div><div class="scene-table">'+sceneSvg('<path d="M142 120V329M458 120V329" stroke="#aa7d69" stroke-width="20"/><ellipse cx="300" cy="103" rx="256" ry="62" fill="#c39275"/><ellipse cx="300" cy="82" rx="256" ry="62" fill="#fae9ca"/><path d="M102 88Q300 135 498 88" fill="none" stroke="#e9c6a0" stroke-width="5"/><ellipse cx="296" cy="68" rx="76" ry="24" fill="#fefaf4" stroke="#d5b5a0" stroke-width="4"/><path d="M250 66Q300 27 344 66Q341 91 295 91Q255 91 250 66" fill="#cddfb8"/><circle cx="275" cy="65" r="12" fill="#efbd77"/><circle cx="300" cy="56" r="13" fill="#e2a292"/><circle cx="321" cy="68" r="11" fill="#f6d18b"/><path d="M402 38H440L434 80H408Z" fill="#b9dae0" stroke="#fff" stroke-width="4"/>')+'</div><div class="scene-spoon" aria-hidden="true"><svg viewBox="0 0 80 80"><path d="M16 62 49 31" stroke="#bea88e" stroke-width="8" stroke-linecap="round"/><ellipse cx="57" cy="24" rx="14" ry="20" transform="rotate(45 57 24)" fill="#ecd4aa"/><circle cx="57" cy="23" r="9" fill="#e8b978"/></svg></div>';
 }else if(petScene==='bath'){
  props='<div class="scene-shower">'+sceneSvg('<path d="M393 62V29Q393 9 360 9H300" fill="none" stroke="#9bbbc7" stroke-width="17" stroke-linecap="round"/><path d="M258 59Q300 7 342 59Z" fill="#accad5" stroke="#f7ffff" stroke-width="5"/>')+'</div><div class="scene-water" aria-hidden="true">'+Array.from({length:9},(_,i)=>`<i style="--drop:${i}"></i>`).join('')+'</div><div class="scene-tub">'+sceneSvg('<ellipse cx="300" cy="301" rx="160" ry="18" fill="#789aaa" opacity=".2"/><path d="M110 80Q100 243 191 283H409Q500 244 490 80Z" fill="#fffaf4" stroke="#c4dbe0" stroke-width="8"/><path d="M139 112Q137 224 206 252H396" fill="none" stroke="#e5edf0" stroke-width="14" stroke-linecap="round"/><ellipse cx="300" cy="78" rx="201" ry="45" fill="#bde5e9" stroke="#fffaf4" stroke-width="18"/><path d="M165 274v36M435 274v36" stroke="#bbcbd0" stroke-width="19" stroke-linecap="round"/><g fill="#fff" opacity=".92"><circle cx="160" cy="67" r="25"/><circle cx="201" cy="83" r="29"/><circle cx="260" cy="83" r="22"/><circle cx="333" cy="84" r="25"/><circle cx="384" cy="73" r="30"/><circle cx="435" cy="67" r="22"/></g><path d="M409 118q12-17 25 0q23-9 22 12q-3 19-36 17q-30-5-20-19" fill="#f4d67e"/><circle cx="436" cy="115" r="3" fill="#856450"/>')+'</div><div class="scene-bubbles" aria-hidden="true">'+Array.from({length:7},(_,i)=>`<i style="--bubble:${i}"></i>`).join('')+'</div>';
 }else{
  const ball=court==='basketball'?'<circle cx="40" cy="40" r="33" fill="#edb076" stroke="#a97862" stroke-width="3"/><path d="M7 40H73M40 7V73M16 16Q60 40 16 64M64 16Q20 40 64 64" fill="none" stroke="#ac7d66" stroke-width="3"/>':court==='football'?'<circle cx="40" cy="40" r="33" fill="#fffaf1" stroke="#9daea2" stroke-width="3"/><path d="m40 22 17 12-6 21H29l-6-21ZM12 21l12 1-9 16-8-5M62 18l-7 13 16 9 3-11M23 68l5-13 20 13-2 6" fill="#758d83"/>':'<circle cx="40" cy="40" r="33" fill="#d9e898" stroke="#b5c67d" stroke-width="3"/><path d="M22 11Q60 40 22 69M58 11Q20 40 58 69" fill="none" stroke="#ffffec" stroke-width="5"/>';
  props='<div class="scene-ball" aria-hidden="true"><svg viewBox="0 0 80 80">'+ball+'</svg></div>';
 }
 return `<div class="pet-room pet-scene scene-${petScene} ${active?'scene-active':'scene-rest'} court-${court}" data-pet-scene="${petScene}" data-court="${sport?court:''}"><button class="scene-home" onclick="COZY.homeScene()" aria-label="回到宠物小屋">🏡</button><span class="scene-label">${title}</span><div class="pet-roamer"><div class="pet-walking-body">${petArt()}</div></div>${props}${petReward()}</div>`;
}

function renderPet(){const p=pets.find(p=>p[0]===data.pet);return `<section class="cozy-page cozy-pet-page">${nav('宠物小屋','🐰')}<div class="cozy-heading"><small>我的软萌好朋友</small><h1>${p[2]}在等你呀</h1><p>喂一口、洗个澡，再一起玩</p></div><div class="pet-choices">${pets.map(x=>`<button aria-pressed="${x[0]===data.pet}" onclick="COZY.choosePet('${x[0]}')">${x[1]} ${x[2]}</button>`).join('')}</div>${renderPetScene()}<div class="pet-needs">${['吃饱饱','香香澡','开心玩'].map((s,i)=>`<div><b>${s}</b><span aria-label="${data.care[i]}/3">${'♥'.repeat(data.care[i])}${'♡'.repeat(3-data.care[i])}</span></div>`).join('')}</div><div class="cozy-tools">${[['🥣','喂饭'],['🫧','洗澡'],['🎾','玩球']].map((x,i)=>`<button onclick="COZY.care(${i})"><span>${x[0]}</span><b>${x[1]}</b></button>`).join('')}</div><p class="cozy-notice" role="status">${notice||'小伙伴不会饿坏，也不会消失。随时来玩就好。'}</p><div class="cozy-footer"><button class="cozy-secondary" onclick="COZY.newDay()">🌤️ 再玩一轮照顾</button><button class="cozy-secondary" onclick="COZY.open('garden')">🌱 和小伙伴去种菜 →</button></div></section>`}
function gardenFx(r){return `<div class="garden-sequence" aria-hidden="true">${r.kind==='water'?'<span class="watering-can">🚿</span>'+Array.from({length:7},(_,i)=>`<i class="rain-drop" style="--n:${i}">💧</i>`).join(''):r.kind==='sow'?'<span class="sowing-hand">🤲</span><i class="falling-seed">🌰</i>':`<span class="harvest-crop">${r.icon}</span><span class="harvest-basket">🧺</span>`}</div>`}
function renderGarden(){const c=crops.find(c=>c[0]===seed);return `<section class="cozy-page cozy-garden-page">${nav('小小菜园','🌱')}<div class="cozy-heading"><small>种下一点点，收获甜甜的</small><h1>我的小菜园</h1><p>种下 → 浇两次水 → 采收。不用等很久。</p></div><div class="garden-summary ${currentReaction()?.kind==='harvest'?'basket-happy':''}"><span>🧺 已收获 ${data.basket} 个</span><span>🌟 ${data.stars} 颗花园星</span></div><div class="garden-seeds" aria-label="选择种子">${crops.map(x=>`<button aria-pressed="${seed===x[0]}" onclick="COZY.seed('${x[0]}')"><span>${x[1]}</span>${x[2]}</button>`).join('')}</div><div class="cozy-tools garden-tools">${[['seed','🌰','种下'],['water','💧','浇水'],['harvest','🧺','采收']].map(x=>`<button data-garden-tool="${x[0]}" aria-pressed="${tool===x[0]}" onclick="COZY.tool('${x[0]}')"><span>${x[1]}</span><b>${x[2]}</b></button>`).join('')}</div><div class="garden-landscape" aria-hidden="true"><span class="garden-sun">☀️</span><span class="garden-cloud">☁️</span><span class="garden-butterfly">🦋</span><span class="garden-fence"></span></div><div class="garden-board">${data.plots.map((p,i)=>{const crop=crops.find(c=>c[0]===p.crop),r=currentReaction(),active=r?.index===i;const stage=p.stage===0?'空地':p.stage===1?'小种子':p.stage===2?'小嫩芽':'可以收啦';return `<button class="garden-plot stage-${p.stage} ${active?'reacting-'+r.kind:''}" data-plot="${i}" onclick="COZY.plot(${i})" aria-label="第${i+1}块地，${crop?.[2]||'空地'}，${stage}"><span>${p.stage===0?'＋':p.stage===1?'🌰':p.stage===2?'🌱':crop[1]}</span><b>${crop?.[2]||'种点什么'}</b><small>${stage}</small>${active?gardenFx(r):''}</button>`}).join('')}</div><p class="cozy-notice" role="status">${notice||`先选${c[2]}种子，再点空地。也可以把上面的工具拖到地里。`}</p><button class="cozy-secondary" onclick="COZY.open('pet')">🐰 回宠物小屋</button></section>`}
function plot(i){if(!Number.isInteger(i)||i<0||i>=6)return;const p=data.plots[i];if(tool==='seed'){if(p.crop)return update('这里已经种好了，选水滴给它浇水吧。');p.crop=seed;p.stage=1;react('sow',i);update('种子住进泥土里啦，给它浇两次水吧。')}else if(tool==='water'){if(!p.crop)return update('这里还是空地，先种一颗种子吧。');if(p.stage>=3)return update('已经长大啦，选篮子收获吧。');p.stage++;react('water',i);update(p.stage===3?'长大啦！把它收到小篮子里吧。':'冒出小嫩芽了，再浇一次水吧。')}else{if(p.stage!==3)return update('还没长大呢，先给小菜浇水吧。');react('harvest',i,crops.find(c=>c[0]===p.crop)[1]);data.basket++;data.stars++;data.plots[i]={crop:null,stage:0};update('收获成功！你真是一位细心的小园丁。')}}
function mount(){if(reactionTimer){root.clearTimeout(reactionTimer);reactionTimer=null}const active=currentReaction();if(active)reactionTimer=root.setTimeout(()=>{reactionTimer=null;if(['pet','garden'].includes(root.state?.page)){reaction=null;root.render?.()}},Math.max(0,active.until-Date.now())+30);const page=document.querySelector('.cozy-page');if(!page||root.state?.page!=='garden')return;let drag=null;page.addEventListener('pointerdown',e=>{const b=e.target.closest('[data-garden-tool]');if(!b)return;e.preventDefault();drag={id:e.pointerId,tool:b.dataset.gardenTool,x:e.clientX,y:e.clientY};b.setPointerCapture?.(e.pointerId)});page.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;const d=drag;drag=null;if(Math.hypot(e.clientX-d.x,e.clientY-d.y)<10)return;const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-plot]');if(target){tool=d.tool;plot(Number(target.dataset.plot))}});page.addEventListener('pointercancel',()=>drag=null);page.addEventListener('dragstart',e=>{const b=e.target.closest('[data-garden-tool]');if(b)e.dataTransfer.setData('text/plain',b.dataset.gardenTool)});page.addEventListener('dragover',e=>{if(e.target.closest('[data-plot]'))e.preventDefault()});page.addEventListener('drop',e=>{const b=e.target.closest('[data-plot]'),t=e.dataTransfer.getData('text/plain');if(b&&['seed','water','harvest'].includes(t)){e.preventDefault();tool=t;plot(Number(b.dataset.plot))}})}
root.COZY={homeScene(){petScene='home';reaction=null;notice='';root.render?.()},pat(){react('pat');update('你的小手轻轻的，我很喜欢。我们一起眯着眼睛笑一笑吧。')},renderPet,renderGarden,mount,plot,open(page){notice='';petScene='home';reaction=null;root.go(page)},leave(){notice='';petScene='home';reaction=null;root.go('home')},choosePet(id){if(pets.some(p=>p[0]===id)){data.careByPet[data.pet]=data.care.slice();data.pet=id;data.care=(data.careByPet[id]||[0,0,0]).slice();petScene='home';reaction=null;update('你好呀，我会一直陪着你。')}},care(i){if(!Number.isInteger(i)||i<0||i>2)return;data.care[i]=Math.min(3,data.care[i]+1);petScene=['dining','bath','sport'][i];if(i===2)courtIndex=(courtIndex+1)%3;react(['eat','wash','play'][i]);update(PET_CHAT[i][careTurns[i]++%PET_CHAT[i].length])},newDay(){if(data.care.some(n=>n<3))return update('先把三颗爱心都照顾好，再开始新一轮吧。');data.care=[0,0,0];update('新一轮开始啦，我们继续一起玩。')},seed(id){if(crops.some(c=>c[0]===id)){seed=id;tool='seed';notice='';root.render()}},tool(id){if(['seed','water','harvest'].includes(id)){tool=id;notice='';root.render()}},help(){say(root.state?.page==='pet'?'选一个小伙伴，点饭碗、泡泡和小球照顾它。':'选种子，点空地种下，再选水滴浇两次，最后用篮子收获。')},_test:{load,fresh,get:()=>JSON.parse(JSON.stringify(data))}};
})(window);
