/* A gentle home for a pet and a six-plot vegetable garden. Progress stays on this device. */
(function(root){
'use strict';
const KEY='kid-cozy-home-v1';
const pets=[['bunny','🐰','棉花兔'],['kitten','🐱','奶糖猫'],['puppy','🐶','布丁狗']];
const crops=[['carrot','🥕','胡萝卜'],['tomato','🍅','番茄'],['corn','🌽','玉米'],['strawberry','🍓','草莓']];
const fresh=()=>({pet:'bunny',care:[0,0,0],plots:Array.from({length:6},()=>({crop:null,stage:0})),basket:0,stars:0});
function load(){let d;try{d=JSON.parse(root.localStorage.getItem(KEY)||'null')}catch{}const v=fresh();if(!d||typeof d!=='object')return v;v.pet=pets.some(p=>p[0]===d.pet)?d.pet:v.pet;v.care=v.care.map((_,i)=>Math.min(3,Math.max(0,Math.floor(Number(d.care?.[i])||0))));v.plots=v.plots.map((p,i)=>{const a=d.plots?.[i];return a&&crops.some(c=>c[0]===a.crop)?{crop:a.crop,stage:Math.min(3,Math.max(1,Math.floor(Number(a.stage)||1)))}:p});v.basket=Math.min(9999,Math.max(0,Math.floor(Number(d.basket)||0)));v.stars=Math.min(9999,Math.max(0,Math.floor(Number(d.stars)||0)));return v}
let data=load(),seed='carrot',tool='seed',notice='';
function save(){try{root.localStorage.setItem(KEY,JSON.stringify(data));return true}catch{notice='设备空间不足，这次进度暂时不能保存。';return false}}
function say(text){root.speak?.(text)}
function update(text){notice=text;save();root.render?.();say(notice)}
function nav(title,icon){return `<div class="mini-game-nav"><button class="game-exit" onclick="COZY.leave()"><span>🏠</span><b>回到乐园</b></button><div class="mini-game-name"><span>${icon}</span><b>${title}</b></div><button class="round-btn" onclick="COZY.help()" aria-label="听玩法">🔊</button></div>`}
function petArt(){const p=pets.find(p=>p[0]===data.pet);return `<div class="cozy-pet-art" aria-label="${p[2]}"><div class="cozy-pet-face">${p[1]}</div><span class="pet-heart">♡</span><span class="pet-paw">🐾</span></div>`}
function renderPet(){const p=pets.find(p=>p[0]===data.pet);return `<section class="cozy-page">${nav('宠物小屋','🐰')}<div class="cozy-heading"><small>我的软萌好朋友</small><h1>${p[2]}在等你呀</h1><p>喂一口、洗个澡，再一起玩</p></div><div class="pet-choices">${pets.map(x=>`<button aria-pressed="${x[0]===data.pet}" onclick="COZY.choosePet('${x[0]}')">${x[1]} ${x[2]}</button>`).join('')}</div><div class="pet-room">${petArt()}<div class="pet-floor"></div><div class="pet-room-window">☀️</div></div><div class="pet-needs">${['吃饱饱','香香澡','开心玩'].map((s,i)=>`<div><b>${s}</b><span aria-label="${data.care[i]}/3">${'♥'.repeat(data.care[i])}${'♡'.repeat(3-data.care[i])}</span></div>`).join('')}</div><div class="cozy-tools">${[['🥣','喂饭'],['🫧','洗澡'],['🎾','玩球']].map((x,i)=>`<button onclick="COZY.care(${i})"><span>${x[0]}</span><b>${x[1]}</b></button>`).join('')}</div><p class="cozy-notice" role="status">${notice||'小伙伴不会饿坏，也不会消失。随时来玩就好。'}</p><button class="cozy-secondary" onclick="COZY.newDay()">🌤️ 再玩一轮照顾</button><button class="cozy-secondary" onclick="COZY.open('garden')">🌱 和小伙伴去种菜 →</button></section>`}
function renderGarden(){const c=crops.find(c=>c[0]===seed);return `<section class="cozy-page">${nav('小小菜园','🌱')}<div class="cozy-heading"><small>种下一点点，收获甜甜的</small><h1>我的小菜园</h1><p>种下 → 浇两次水 → 采收。不用等很久。</p></div><div class="garden-summary"><span>🧺 已收获 ${data.basket} 个</span><span>🌟 ${data.stars} 颗花园星</span></div><div class="garden-seeds" aria-label="选择种子">${crops.map(x=>`<button aria-pressed="${seed===x[0]}" onclick="COZY.seed('${x[0]}')"><span>${x[1]}</span>${x[2]}</button>`).join('')}</div><div class="cozy-tools garden-tools">${[['seed','🌰','种下'],['water','💧','浇水'],['harvest','🧺','采收']].map(x=>`<button data-garden-tool="${x[0]}" aria-pressed="${tool===x[0]}" onclick="COZY.tool('${x[0]}')"><span>${x[1]}</span><b>${x[2]}</b></button>`).join('')}</div><div class="garden-board">${data.plots.map((p,i)=>{const crop=crops.find(c=>c[0]===p.crop);const stage=p.stage===0?'空地':p.stage===1?'小种子':p.stage===2?'小嫩芽':'可以收啦';return `<button class="garden-plot stage-${p.stage}" data-plot="${i}" onclick="COZY.plot(${i})" aria-label="第${i+1}块地，${crop?.[2]||'空地'}，${stage}"><span>${p.stage===0?'＋':p.stage===1?'🌰':p.stage===2?'🌱':crop[1]}</span><b>${crop?.[2]||'种点什么'}</b><small>${stage}</small></button>`}).join('')}</div><p class="cozy-notice" role="status">${notice||`先选${c[2]}种子，再点空地。也可以把上面的工具拖到地里。`}</p><button class="cozy-secondary" onclick="COZY.open('pet')">🐰 回宠物小屋</button></section>`}
function plot(i){if(!Number.isInteger(i)||i<0||i>=6)return;const p=data.plots[i];if(tool==='seed'){if(p.crop)return update('这里已经种好了，选水滴给它浇水吧。');p.crop=seed;p.stage=1;update('种子住进泥土里啦，给它浇两次水吧。')}else if(tool==='water'){if(!p.crop)return update('这里还是空地，先种一颗种子吧。');if(p.stage>=3)return update('已经长大啦，选篮子收获吧。');p.stage++;update(p.stage===3?'长大啦！把它收到小篮子里吧。':'冒出小嫩芽了，再浇一次水吧。')}else{if(p.stage!==3)return update('还没长大呢，先给小菜浇水吧。');data.basket++;data.stars++;data.plots[i]={crop:null,stage:0};update('收获成功！你真是一位细心的小园丁。')}}
function mount(){const page=document.querySelector('.cozy-page');if(!page||root.state?.page!=='garden')return;let drag=null;page.addEventListener('pointerdown',e=>{const b=e.target.closest('[data-garden-tool]');if(!b)return;e.preventDefault();drag={id:e.pointerId,tool:b.dataset.gardenTool,x:e.clientX,y:e.clientY};b.setPointerCapture?.(e.pointerId)});page.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;const d=drag;drag=null;if(Math.hypot(e.clientX-d.x,e.clientY-d.y)<10)return;const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-plot]');if(target){tool=d.tool;plot(Number(target.dataset.plot))}});page.addEventListener('pointercancel',()=>drag=null);page.addEventListener('dragstart',e=>{const b=e.target.closest('[data-garden-tool]');if(b)e.dataTransfer.setData('text/plain',b.dataset.gardenTool)});page.addEventListener('dragover',e=>{if(e.target.closest('[data-plot]'))e.preventDefault()});page.addEventListener('drop',e=>{const b=e.target.closest('[data-plot]'),t=e.dataTransfer.getData('text/plain');if(b&&['seed','water','harvest'].includes(t)){e.preventDefault();tool=t;plot(Number(b.dataset.plot))}})}
root.COZY={renderPet,renderGarden,mount,plot,open(page){notice='';root.go(page)},leave(){notice='';root.go('home')},choosePet(id){if(pets.some(p=>p[0]===id)){data.pet=id;update('你好呀，我会一直陪着你。')}},care(i){if(!Number.isInteger(i)||i<0||i>2)return;if(data.care[i]===3)return update('已经照顾好了，试试别的吧。');data.care[i]++;update(['吃得香香的，谢谢你。','洗得香香的，真舒服。','和你一起玩，我好开心。'][i])},newDay(){if(data.care.some(n=>n<3))return update('先把三颗爱心都照顾好，再开始新一轮吧。');data.care=[0,0,0];update('新一轮开始啦，我们继续一起玩。')},seed(id){if(crops.some(c=>c[0]===id)){seed=id;tool='seed';notice='';root.render()}},tool(id){if(['seed','water','harvest'].includes(id)){tool=id;notice='';root.render()}},help(){say(root.state?.page==='pet'?'选一个小伙伴，点饭碗、泡泡和小球照顾它。':'选种子，点空地种下，再选水滴浇两次，最后用篮子收获。')},_test:{load,fresh,get:()=>JSON.parse(JSON.stringify(data))}};
})(window);
