const $=s=>document.querySelector(s);const appEl=$('#app');const player=$('#player');
const state={page:'home',stack:[],book:null,pageNo:0,muted:false,stars:+localStorage.getItem('kid-stars-v2')||0,favs:JSON.parse(localStorage.getItem('kid-favs-v2')||'[]')};
const customArt=new Set(['dino_01','dino_02',...(window.BOOKS||[]).filter(b=>b.group==='peppa'||b.group==='paw').map(b=>b.id)]);
function artSrc(b){return `art/${b.id}.${b.group==='peppa'||b.group==='paw'?'webp':'png'}?v=20260926b`}
const learnSets={
  animals:[['🐼','panda','熊猫'],['🐘','elephant','大象'],['🦁','lion','狮子'],['🐰','rabbit','兔子'],['🐬','dolphin','海豚'],['🦒','giraffe','长颈鹿']],
  fruit:[['🍎','apple','苹果'],['🍌','banana','香蕉'],['🍓','strawberry','草莓'],['🍉','watermelon','西瓜'],['🍇','grape','葡萄'],['🍊','orange','橙子']],
  nature:[['☀️','sun','太阳'],['🌙','moon','月亮'],['🌧️','rain','下雨'],['🌈','rainbow','彩虹'],['🌳','tree','树'],['🌸','flower','花']],
  feelings:[['😄','happy','开心'],['😢','sad','难过'],['😠','angry','生气'],['😨','scared','害怕'],['😴','tired','累了'],['🥰','love','爱']]
};
const gameSets={count:{title:'数一数',icon:'🔢'},sound:{title:'听音找词',icon:'👂'},match:{title:'图形配对',icon:'🧩'},memory:{title:'记忆翻牌',icon:'🧠'},sort:{title:'物品分类',icon:'🧺'},pop:{title:'彩色气球',icon:'🎈'},snakeFruit:{title:'滑动小虫吃水果',icon:'🐛'},beeGarden:{title:'小蜜蜂采花',icon:'🐝'},peppaCount:{title:'佩奇泥坑数数',icon:'🐷'},peppaPicnic:{title:'佩奇野餐篮',icon:'🧺'},pawMaze:{title:'手指救援迷宫',icon:'🐾'},pawGear:{title:'汪汪队装备配对',icon:'🎒'},brandMemory:{title:'角色记忆翻牌',icon:'💛'},storyOrder:{title:'故事顺序',icon:'🔢'}};
const colorings=[['cat','小猫'],['dog','小狗'],['rabbit','小兔'],['fish','小鱼'],['butterfly','蝴蝶'],['flower','花朵'],['car','小汽车'],['house','小房子'],['star','星星'],['icecream','冰淇淋']];
const palette=['#ff6b6b','#ffad5c','#ffd65a','#62ce91','#56b4ff','#8c86f5','#d47be7','#795548'];
const swipeMazePaths=[[0,1,2,9,16,17,18,25,32,31,30,37,44,45,46,47,48],[0,7,14,15,16,9,10,11,18,25,24,31,38,39,40,47,48],[0,1,8,15,22,23,24,17,10,11,12,19,26,33,32,39,46,47,48]];
const beeFlowers=[[17,18],[78,17],[49,34],[19,61],[79,65],[49,86]];
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function voiceKey(text,lang){return `${String(lang).toLowerCase().startsWith('en')?'en':'zh'}|${text}`}
function playSpoken(text,lang='zh-CN',onend=null){
  if(state.muted)return;
  const src=window.VOICE_MAP?.[voiceKey(text,lang)];
  if(src){
    player.onended=onend;player.onerror=()=>fallbackSpeech(text,lang,onend);player.src=src;player.play().catch(()=>fallbackSpeech(text,lang,onend));return;
  }
  fallbackSpeech(text,lang,onend);
}
function fallbackSpeech(text,lang,onend){
  player.onended=null;player.onerror=null;player.pause();player.removeAttribute('src');
  if(!window.speechSynthesis){onend?.();return}const u=new SpeechSynthesisUtterance(text);u.lang=lang;u.rate=.82;u.pitch=1.08;u.onend=onend;speechSynthesis.speak(u)
}
function speak(text,lang='zh-CN'){stopAudio();playSpoken(text,lang)}
function stopAudio(){player.pause();player.onended=null;player.onerror=null;player.removeAttribute('src');if(window.speechSynthesis)speechSynthesis.cancel()}
function go(page,data=null,push=true){stopInteractiveGame();stopAudio();if(state.page==='reader'&&page!=='reader')state.readerAuto=false;if(push&&state.page!==page)state.stack.push({page:state.page,book:state.book,pageNo:state.pageNo});state.page=page;if(data?.book!==undefined)state.book=data.book;if(data?.pageNo!==undefined)state.pageNo=data.pageNo;render()}
function back(){stopInteractiveGame();stopAudio();const last=state.stack.pop();if(!last)return go('home',null,false);state.page=last.page;state.book=last.book;state.pageNo=last.pageNo;render()}
function reward(){state.stars++;localStorage.setItem('kid-stars-v2',state.stars);$('#stars').textContent=state.stars}
function courseKey(c){return `${c.subject}:${c.unit}:${c.title}`}
function completedCourses(){return JSON.parse(localStorage.getItem('kid-course-done-v1')||'[]')}
function completeCourse(c){const done=completedCourses(),key=courseKey(c);if(!done.includes(key)){done.push(key);localStorage.setItem('kid-course-done-v1',JSON.stringify(done));return true}return false}
function shell(title,sub,body){return `<div class="page-head"><div><h1>${title}</h1><p>${sub}</p></div></div>${body}`}
function renderHome(){const recent=JSON.parse(localStorage.getItem('kid-recent-v2')||'null');return `<section class="hero"><div><h1>果粒橙小朋友，今天想玩什么？</h1><p>听故事、上小课，再玩一个小游戏吧</p></div><div class="mascot">🦕</div></section><button class="school-banner" onclick="go('school')"><span>🎓</span><span><b>一年级上册课堂</b><small>浙江教材方向 · 语文和数学 · 点一点就讲课</small></span><strong>开始上课 ›</strong></button>${recent?`<button class="continue" onclick="openBook('${recent.id}',${recent.page||0})"><span style="font-size:35px">📖</span><span><b>继续上次的故事</b><small>${esc(recent.title)}</small></span><span class="play">继续 ▶</span></button>`:''}<h2 class="section-title">开始探索</h2><div class="big-grid"><button class="big-card" onclick="go('stories')"><span class="icon">📚</span><b>听故事</b><small>翻一页，听一页</small></button><button class="big-card" onclick="go('learn')"><span class="icon">🔎</span><b>认一认</b><small>动物、英语和生活常识</small></button><button class="big-card" onclick="go('games')"><span class="icon">🎮</span><b>玩游戏</b><small>数数、听音和记忆</small></button><button class="big-card" onclick="go('create')"><span class="icon">🎨</span><b>创意乐园</b><small>画画、音乐和节奏</small></button></div>`}
function thumb(b){if(customArt.has(b.id))return `<div class="book-cover sprite" style="background-image:url('${artSrc(b)}')"></div>`;let p=b.pages[0]||{};let src=p.img||`${b.img_prefix.replace(/\/?$/,'/')}cover.webp`;return `<div class="book-cover"><img src="${esc(src)}" onerror="this.src='img/dino/dino_01/cover.webp'" alt=""></div>`}
function renderStories(filter='all'){let books=window.BOOKS||[];if(filter!=='all')books=books.filter(b=>b.group===filter);return shell('故事屋',`61 本适合 5 岁孩子的短故事，每页都能朗读`,`<div class="filters"><button class="chip ${filter==='all'?'active':''}" onclick="showBooks('all')">全部</button><button class="chip ${filter==='peppa'?'active':''}" onclick="showBooks('peppa')">🐷 小猪佩奇</button><button class="chip ${filter==='paw'?'active':''}" onclick="showBooks('paw')">🐾 汪汪队</button><button class="chip ${filter==='dino'?'active':''}" onclick="showBooks('dino')">🦕 生活成长</button><button class="chip ${filter==='poem'?'active':''}" onclick="showBooks('poem')">🌿 古诗</button><button class="chip ${filter==='idiom'?'active':''}" onclick="showBooks('idiom')">💡 小故事</button></div><div class="book-grid">${books.map(b=>`<button class="book" onclick="openBook('${b.id}',0)">${thumb(b)}<div class="info"><b>${esc(b.title.replace(/^(古诗|成语)：/,''))}</b><small>${b.pages.length} 页 · 有声故事</small></div></button>`).join('')}</div>`)}
window.showBooks=f=>{appEl.innerHTML=renderStories(f)};
function openBook(id,n=0){const b=(window.BOOKS||[]).find(x=>x.id===id);if(!b)return;state.readerAuto=false;state.book=b;state.pageNo=Math.max(0,Math.min(n,b.pages.length-1));localStorage.setItem('kid-recent-v2',JSON.stringify({id:b.id,title:b.title,page:state.pageNo}));go('reader',{book:b,pageNo:state.pageNo})}
function pageVisual(b,n){const p=b.pages[n]||{};if(customArt.has(b.id)){const col=n%2,row=Math.floor(n/2);return `<div class="story-picture" style="background-image:url('${artSrc(b)}');background-size:200% 300%;background-position:${col*100}% ${row*50}%"></div>`}let src=p.img||`${b.img_prefix.replace(/\/?$/,'/')}page${n+1}.webp`;return `<div class="story-picture"><img src="${esc(src)}" onerror="this.onerror=null;this.src='img/dino/dino_01/page1.webp'" alt=""></div>`}
function renderReader(){const b=state.book,p=b.pages[state.pageNo],n=state.pageNo,total=b.pages.length;return `<div class="reader"><div class="reader-top"><button class="round-btn" onclick="state.readerAuto=false;go('stories')">←</button><h1>${esc(b.title)}</h1><button class="round-btn" onclick="toggleFav('${b.id}')">${state.favs.includes(b.id)?'❤️':'🤍'}</button></div><div class="progress-dots">${b.pages.map((_,i)=>`<i class="dot ${i===n?'on':''}"></i>`).join('')}</div><article class="reader-stage">${pageVisual(b,n)}<div class="story-text">${esc(p.text).replace(/\n/g,'<br>')}</div></article><div class="reader-controls"><button class="control" onclick="turn(-1)" ${n===0?'disabled':''}>← 上一页</button><button class="control primary" onclick="readPage()">🔊 读这一页</button><button class="control" onclick="turn(1)">${n===total-1?'读完啦':'下一页 →'}</button></div><button class="auto-read-btn ${state.readerAuto?'playing':''}" onclick="toggleAutoRead()">${state.readerAuto?`⏸ 停止连续朗读 · 第 ${n+1}/${total} 页`:'▶ 从这一页开始连续听故事'}</button></div>`}
function readPage(){state.readerAuto=false;stopAudio();playSpoken(state.book.pages[state.pageNo].text)}
function toggleAutoRead(){if(state.readerAuto){state.readerAuto=false;stopAudio();render();return}if(state.muted){state.muted=false;$('#soundBtn').textContent='🔊'}state.readerAuto=true;stopAudio();render();readAutoPage()}
function readAutoPage(){if(!state.readerAuto||state.page!=='reader'||!state.book)return;playSpoken(state.book.pages[state.pageNo].text,'zh-CN',()=>{if(!state.readerAuto||state.page!=='reader')return;if(state.pageNo>=state.book.pages.length-1){state.readerAuto=false;reward();render();speak('故事读完啦');return}state.pageNo++;localStorage.setItem('kid-recent-v2',JSON.stringify({id:state.book.id,title:state.book.title,page:state.pageNo}));render();setTimeout(readAutoPage,250)})}
function turn(d){state.readerAuto=false;if(state.pageNo+d>=state.book.pages.length){reward();go('stories');return}state.pageNo=Math.max(0,state.pageNo+d);localStorage.setItem('kid-recent-v2',JSON.stringify({id:state.book.id,title:state.book.title,page:state.pageNo}));stopAudio();render()}
function toggleFav(id){state.favs=state.favs.includes(id)?state.favs.filter(x=>x!==id):[...state.favs,id];localStorage.setItem('kid-favs-v2',JSON.stringify(state.favs));render()}
function renderLearn(){const cards=[['animals','🐼','动物朋友'],['fruit','🍎','水果乐园'],['nature','🌈','大自然'],['feelings','😊','认识情绪']];return shell('认一认','点一点，就会读给你听',`<div class="activity-grid">${cards.map(x=>`<button class="activity" onclick="openLearn('${x[0]}')"><span class="icon">${x[1]}</span><b>${x[2]}</b><small>看图 · 中文 · 英语</small></button>`).join('')}</div>`)}
function openLearn(k){state.learn=k;go('lesson')}
function renderLesson(){const list=learnSets[state.learn]||learnSets.animals;const item=list[state.learnNo||0];return `<div class="lesson"><h2>点卡片听一听</h2><button class="flash" style="width:100%;border:0" onclick="speakWord('${item[1]}','${item[2]}')"><span class="emoji">${item[0]}</span><span class="word">${item[1]}</span><span class="meaning">${item[2]}</span></button><div class="reader-controls"><button class="control" onclick="learnTurn(-1)">← 上一个</button><button class="control primary" onclick="speakWord('${item[1]}','${item[2]}')">🔊 听发音</button><button class="control" onclick="learnTurn(1)">下一个 →</button></div></div>`}
function speakWord(en,zh){stopAudio();playSpoken(en,'en-US',()=>playSpoken(zh,'zh-CN'))}function learnTurn(d){stopAudio();const n=(learnSets[state.learn]||[]).length;state.learnNo=((state.learnNo||0)+d+n)%n;render()}
function renderGames(){return shell('游戏乐园','短短几分钟，动脑又开心',`<div class="activity-grid">${Object.entries(gameSets).map(([k,v])=>`<button class="activity" onclick="openGame('${k}')"><span class="icon">${v.icon}</span><b>${v.title}</b><small>适合 5 岁 · 随机出题</small></button>`).join('')}</div>`)}
function openGame(k){stopInteractiveGame();state.game=k;state.question=null;state.memory=null;state.maze=null;state.order=null;state.snake=null;state.bee=null;go('game')}
function newQuestion(){if(state.game==='count'){const n=1+Math.floor(Math.random()*9),opts=[n];while(opts.length<4){let x=1+Math.floor(Math.random()*9);if(!opts.includes(x))opts.push(x)}state.question={prompt:'一共有多少颗星星？',show:'⭐'.repeat(n),right:String(n),opts:opts.sort(()=>Math.random()-.5).map(String)}}else{const all=learnSets.animals.concat(learnSets.fruit);const x=all[Math.floor(Math.random()*all.length)],opts=[x];while(opts.length<4){let y=all[Math.floor(Math.random()*all.length)];if(!opts.includes(y))opts.push(y)}state.question={prompt:state.game==='sound'?'听一听，选出正确的图片':'找到相同的朋友',show:state.game==='sound'?'🔊':x[0],right:x[0],word:x[1],opts:opts.sort(()=>Math.random()-.5).map(y=>y[0])}}return state.question}
function renderGame(){if(state.game==='memory')return renderMemory();if(state.game==='sort')return renderSort();if(state.game==='pop')return renderPop();if(state.game==='snakeFruit')return renderSnakeFruit();if(state.game==='beeGarden')return renderBeeGarden();if(state.game==='peppaCount')return renderPeppaCount();if(state.game==='peppaPicnic')return renderPeppaPicnic();if(state.game==='pawMaze')return renderPawMaze();if(state.game==='pawGear')return renderPawGear();if(state.game==='brandMemory')return renderBrandMemory();if(state.game==='storyOrder')return renderStoryOrder();const q=state.question||newQuestion();return `<div class="lesson"><h2>${gameSets[state.game]?.icon||'🎮'} ${gameSets[state.game]?.title||'小游戏'}</h2><p>${q.prompt}</p><div class="flash" onclick="gamePrompt()"><span class="emoji" style="font-size:${state.game==='count'?'48px':'95px'}">${q.show}</span></div><div class="answer-grid">${q.opts.map(o=>`<button class="answer" onclick="answer(this,'${o}')">${o}</button>`).join('')}</div><div class="message" id="message"></div><button class="wide-btn" onclick="state.question=null;render()">换一题</button></div>`}
function gamePrompt(){const q=state.question;if(state.game==='sound')speak(q.word,'en-US');else speak(q.prompt)}function answer(el,o){document.querySelectorAll('.answer').forEach(b=>b.disabled=true);if(o===state.question.right){el.classList.add('good');$('#message').textContent='答对啦！真棒 ⭐';reward();speak('答对啦，真棒')}else{el.classList.add('bad');$('#message').textContent='没关系，再试一题';speak('没关系，再试一题')}}
function renderMemory(){if(!state.memory){const icons=['🐶','🐱','🐰','🐼','🦊','🐸'];state.memory={cards:[...icons,...icons].sort(()=>Math.random()-.5),open:[],done:[]}}const m=state.memory;return `<div class="lesson"><h2>🧠 记忆翻牌</h2><p>每次翻两张，找出一样的朋友</p><div class="memory-grid">${m.cards.map((x,i)=>`<button class="memory-card ${m.open.includes(i)||m.done.includes(i)?'open':''}" onclick="flipCard(${i})">${m.open.includes(i)||m.done.includes(i)?x:'❓'}</button>`).join('')}</div><div class="message">已经找到 ${m.done.length/2} 对</div><button class="wide-btn" onclick="state.memory=null;render()">重新开始</button></div>`}
function flipCard(i){const m=state.memory;if(m.done.includes(i)||m.open.includes(i)||m.open.length>=2)return;m.open.push(i);render();if(m.open.length===2){const[a,b]=m.open;if(m.cards[a]===m.cards[b])setTimeout(()=>{m.done.push(a,b);m.open=[];reward();if(m.done.length===m.cards.length)speak('全部找到了，你的记忆力真棒');render()},500);else setTimeout(()=>{m.open=[];render()},800)}}
function renderSort(){if(!state.question){const items=[['🍎','水果'],['🍌','水果'],['🐶','动物'],['🐼','动物'],['🚗','交通'],['🚲','交通'],['🥛','食物'],['🍞','食物']];const x=items[Math.floor(Math.random()*items.length)];state.question={show:x[0],right:x[1]}}const q=state.question;return `<div class="lesson"><h2>🧺 物品分类</h2><p>它应该放进哪个篮子？</p><div class="flash"><span class="emoji">${q.show}</span></div><div class="answer-grid">${['水果','动物','交通','食物'].map(x=>`<button class="answer" onclick="sortAnswer(this,'${x}')">${x}</button>`).join('')}</div><div class="message" id="message"></div><button class="wide-btn" onclick="state.question=null;render()">换一个物品</button></div>`}
function sortAnswer(el,x){if(x===state.question.right){el.classList.add('good');$('#message').textContent='放对篮子啦 ⭐';reward();speak('分类正确，真棒')}else{el.classList.add('bad');$('#message').textContent='再想一想，它是'+state.question.right;speak('再想一想')}}
function renderPop(){if(!state.question){const colors=[['红色','#ff6262'],['黄色','#ffd34e'],['蓝色','#55aaff'],['绿色','#5bca86']],t=colors[Math.floor(Math.random()*colors.length)];state.question={right:t[0],items:Array.from({length:16},()=>colors[Math.floor(Math.random()*colors.length)])}}const q=state.question;return `<div class="lesson"><h2>🎈 彩色气球</h2><p>请点所有的 <b style="font-size:24px">${q.right}</b> 气球</p><div class="balloon-grid">${q.items.map(x=>`<button class="balloon" style="background:${x[1]}" onclick="popBalloon(this,'${x[0]}')">🎈</button>`).join('')}</div><div class="message" id="message">找一找，点一点</div><button class="wide-btn" onclick="state.question=null;render()">换一种颜色</button></div>`}
function popBalloon(el,color){if(el.classList.contains('popped'))return;if(color===state.question.right){el.classList.add('popped');reward();tone(523.3,.12);$('#message').textContent='找到了！'}else{el.classList.add('shake');setTimeout(()=>el.classList.remove('shake'),350);speak('再看清楚颜色')}}
function renderPeppaCount(){if(!state.question){const n=2+Math.floor(Math.random()*7),opts=[n];while(opts.length<4){const x=1+Math.floor(Math.random()*9);if(!opts.includes(x))opts.push(x)}state.question={right:String(n),opts:opts.sort(()=>Math.random()-.5).map(String)}}const q=state.question;return `<div class="lesson peppa-game"><h2>🐷 佩奇泥坑数数</h2><p>佩奇找到了多少个泥坑？</p><div class="puddle-field"><span class="peppa-mini">🐷</span>${'🟤'.repeat(+q.right)}</div><div class="answer-grid">${q.opts.map(x=>`<button class="answer" onclick="brandAnswer(this,'${x}')">${x}</button>`).join('')}</div><div class="message" id="message"></div><button class="wide-btn" onclick="state.question=null;render()">再数一次</button></div>`}
function renderPeppaPicnic(){if(!state.question){const items=[['🍎','带去野餐'],['🥪','带去野餐'],['🥛','带去野餐'],['🧸','带去野餐'],['🛁','留在家里'],['🛏️','留在家里'],['🚪','留在家里'],['🪥','留在家里']],x=items[Math.floor(Math.random()*items.length)];state.question={show:x[0],right:x[1]}}const q=state.question;return `<div class="lesson peppa-game"><h2>🧺 佩奇野餐篮</h2><p>这个东西要不要放进野餐篮？</p><div class="flash"><span class="emoji">${q.show}</span></div><div class="answer-grid"><button class="answer" onclick="brandAnswer(this,'带去野餐')">🧺 带去野餐</button><button class="answer" onclick="brandAnswer(this,'留在家里')">🏠 留在家里</button></div><div class="message" id="message"></div><button class="wide-btn" onclick="state.question=null;render()">下一个东西</button></div>`}
function brandAnswer(el,value){document.querySelectorAll('.answer').forEach(b=>b.disabled=true);if(value===state.question.right){el.classList.add('good');$('#message').textContent='答对啦！真棒 ⭐';reward();speak('答对啦，真棒')}else{el.classList.add('bad');$('#message').textContent='再想一想';speak('再想一想')}}
function renderPawGear(){if(!state.question){const tasks=[['🔥','哪里着火了，谁来帮忙？','毛毛'],['🚓','需要维持秩序，谁来帮忙？','阿奇'],['🌊','水上有人需要帮助，谁来？','路马'],['🚁','高处需要空中救援，谁来？','天天']];const q=tasks[Math.floor(Math.random()*tasks.length)];state.question={show:q[0],prompt:q[1],right:q[2]}}const q=state.question;return `<div class="lesson paw-game"><h2>🎒 汪汪队装备配对</h2><p>${q.prompt}</p><div class="flash"><span class="emoji">${q.show}</span></div><div class="answer-grid">${[['毛毛','🚒'],['阿奇','🚓'],['路马','🚤'],['天天','🚁']].map(x=>`<button class="answer" onclick="brandAnswer(this,'${x[0]}')">${x[1]} ${x[0]}</button>`).join('')}</div><div class="message" id="message"></div><button class="wide-btn" onclick="state.question=null;render()">下一个任务</button></div>`}
function renderPawMaze(){if(!state.maze)state.maze={route:Math.floor(Math.random()*swipeMazePaths.length),step:0,done:false};const m=state.maze,path=swipeMazePaths[m.route];return `<div class="lesson paw-game"><h2>🐾 手指救援迷宫</h2><p>按住阿奇，沿着浅色小路一直滑到小猫身边</p><div class="swipe-maze" id="swipeMaze">${Array.from({length:49},(_,i)=>{const p=path.indexOf(i),walk=p>=0,passed=walk&&p<=m.step;return `<div data-cell="${i}" class="swipe-maze-cell ${walk?'road':'wall'} ${passed?'passed':''} ${i===48?'goal':''}">${i===path[m.step]?'🐶':i===48?'🐱':walk&&p<m.step?'•':' '}</div>`}).join('')}</div><div class="gesture-tip">☝️ 手指可以不松开，慢慢转弯</div><div class="message" id="message">从阿奇身上开始滑</div><button class="wide-btn" onclick="state.maze=null;render()">换一条路，再玩一次</button></div>`}
function mazeMove(){return false}
function initPawMaze(){const board=$('#swipeMaze');if(!board)return;let dragging=false;const path=swipeMazePaths[state.maze.route];const cellAt=e=>{const r=board.getBoundingClientRect(),x=Math.max(0,Math.min(r.width-1,e.clientX-r.left)),y=Math.max(0,Math.min(r.height-1,e.clientY-r.top));return Math.floor(y/(r.height/7))*7+Math.floor(x/(r.width/7))};const paint=()=>{const m=state.maze;board.querySelectorAll('[data-cell]').forEach(el=>{const idx=+el.dataset.cell,p=path.indexOf(idx);el.classList.toggle('passed',p>=0&&p<=m.step);el.textContent=idx===path[m.step]?'🐶':idx===48?'🐱':p>=0&&p<m.step?'•':' '})};const visit=idx=>{const m=state.maze,p=path.indexOf(idx);if(m.done||p<0)return;if(p>m.step&&p<=m.step+3)m.step=p;else if(p===m.step-1)m.step=p;else return;paint();if(m.step===path.length-1){m.done=true;dragging=false;$('#message').textContent='救援成功啦！你的小手真灵活 ⭐';reward();tone(659,.18);setTimeout(()=>tone(784,.22),170);speak('救援成功，真勇敢')}};board.onpointerdown=e=>{const idx=cellAt(e);if(idx!==path[state.maze.step])return;e.preventDefault();dragging=true;board.setPointerCapture?.(e.pointerId);$('#message').textContent='沿着小路继续滑'};board.onpointermove=e=>{if(!dragging)return;e.preventDefault();visit(cellAt(e))};board.onpointerup=board.onpointercancel=e=>{if(!dragging)return;dragging=false;board.releasePointerCapture?.(e.pointerId);if(!state.maze.done)$('#message').textContent='很好！从阿奇现在的位置继续滑'}}

function snakeNewFruit(s){let x,y;do{x=10+Math.random()*80;y=12+Math.random()*76}while(Math.hypot(x-s.x,y-s.y)<28);return{x,y}}
function renderSnakeFruit(){if(!state.snake){const s={x:50,y:75,score:0,fruit:null,done:false};s.fruit=snakeNewFruit(s);state.snake=s}const s=state.snake;return `<div class="lesson snake-game"><h2>🐛 滑动小虫吃水果</h2><p>按住小虫，手指滑到哪里，小虫就跑到哪里</p><div class="snake-score">🍎 已吃到 <b id="snakeScore">${s.score}</b> / 5</div><div class="bug-field" id="snakeBoard"><span class="bug-sun">☀️</span><span class="bug-leaf leaf-one">🌿</span><span class="bug-leaf leaf-two">🍃</span><span class="bug-fruit" id="bugFruit" style="left:${s.fruit.x}%;top:${s.fruit.y}%">🍎</span><span class="bug-player" id="bugPlayer" style="left:${s.x}%;top:${s.y}%">🐛</span></div><div class="gesture-tip">☝️ 上下左右随便滑，不会碰撞，也不会失败</div><div class="message" id="message">按住小虫，去找苹果吧</div><button class="wide-btn" onclick="resetSnakeFruit()">重新开始</button></div>`}
function initSnakeFruit(){const field=$('#snakeBoard'),bug=$('#bugPlayer'),fruit=$('#bugFruit'),s=state.snake;if(!field||!bug||!fruit||!s)return;let dragging=false;const move=e=>{const r=field.getBoundingClientRect();s.x=Math.max(5,Math.min(95,(e.clientX-r.left)/r.width*100));s.y=Math.max(6,Math.min(94,(e.clientY-r.top)/r.height*100));bug.style.left=s.x+'%';bug.style.top=s.y+'%';if(Math.hypot(s.x-s.fruit.x,s.y-s.fruit.y)>11||s.done)return;s.score++;$('#snakeScore').textContent=s.score;tone(523+s.score*35,.12);if(s.score>=5){s.done=true;dragging=false;fruit.classList.add('picked');reward();$('#message').textContent='五个苹果都找到啦！真棒 ⭐';speak('答对啦，真棒');return}s.fruit=snakeNewFruit(s);fruit.style.left=s.fruit.x+'%';fruit.style.top=s.fruit.y+'%';fruit.animate?.([{transform:'translate(-50%,-50%) scale(.35)'},{transform:'translate(-50%,-50%) scale(1.15)'},{transform:'translate(-50%,-50%) scale(1)'}],{duration:260});$('#message').textContent=`吃到苹果啦，还剩 ${5-s.score} 个`};field.onpointerdown=e=>{if(s.done)return;e.preventDefault();dragging=true;field.setPointerCapture?.(e.pointerId);move(e)};field.onpointermove=e=>{if(!dragging)return;e.preventDefault();move(e)};field.onpointerup=field.onpointercancel=e=>{dragging=false;field.releasePointerCapture?.(e.pointerId)}}
function resetSnakeFruit(){stopInteractiveGame();state.snake=null;render()}

function renderBeeGarden(){if(!state.bee)state.bee={x:50,y:50,collected:[],done:false};const b=state.bee;return `<div class="lesson bee-game"><h2>🐝 小蜜蜂采花</h2><p>按住小蜜蜂，在花园里滑动，把六朵花都找到</p><div class="bee-score">🌸 已采到 <b id="beeScore">${b.collected.length}</b> / ${beeFlowers.length}</div><div class="bee-field" id="beeField"><div class="garden-cloud">☁️</div>${beeFlowers.map((p,i)=>`<span data-flower="${i}" class="garden-flower ${b.collected.includes(i)?'picked':''}" style="left:${p[0]}%;top:${p[1]}%">🌸</span>`).join('')}<span class="bee-player" id="beePlayer" style="left:${b.x}%;top:${b.y}%">🐝</span></div><div class="gesture-tip">☝️ 手指不松开，可以在花园里转来转去</div><div class="message" id="message">按住小蜜蜂开始采花</div><button class="wide-btn" onclick="state.bee=null;render()">重新采花</button></div>`}
function initBeeGarden(){const field=$('#beeField'),bee=$('#beePlayer'),b=state.bee;if(!field||!bee||!b)return;let dragging=false;const move=e=>{const r=field.getBoundingClientRect();b.x=Math.max(5,Math.min(95,(e.clientX-r.left)/r.width*100));b.y=Math.max(5,Math.min(95,(e.clientY-r.top)/r.height*100));bee.style.left=b.x+'%';bee.style.top=b.y+'%';beeFlowers.forEach((p,i)=>{if(b.collected.includes(i)||Math.hypot(b.x-p[0],b.y-p[1])>10)return;b.collected.push(i);field.querySelector(`[data-flower="${i}"]`)?.classList.add('picked');$('#beeScore').textContent=b.collected.length;tone(600+i*45,.1)});if(b.collected.length===beeFlowers.length&&!b.done){b.done=true;dragging=false;reward();$('#message').textContent='六朵花都采到啦！真棒 ⭐';speak('答对啦，真棒')}else if(!b.done)$('#message').textContent=`还剩 ${beeFlowers.length-b.collected.length} 朵花`};field.onpointerdown=e=>{if(b.done)return;e.preventDefault();dragging=true;field.setPointerCapture?.(e.pointerId);move(e)};field.onpointermove=e=>{if(!dragging)return;e.preventDefault();move(e)};field.onpointerup=field.onpointercancel=e=>{dragging=false;field.releasePointerCapture?.(e.pointerId)}}
function stopInteractiveGame(){}
function renderBrandMemory(){if(!state.memory){const icons=['🐷','🦖','🚒','🚓','🚁','🚤'];state.memory={cards:[...icons,...icons].sort(()=>Math.random()-.5),open:[],done:[]}}const m=state.memory;return `<div class="lesson brand-memory"><h2>💛 角色记忆翻牌</h2><p>找出佩奇和汪汪队的相同伙伴</p><div class="memory-grid">${m.cards.map((x,i)=>`<button class="memory-card ${m.open.includes(i)||m.done.includes(i)?'open':''}" onclick="flipCard(${i})">${m.open.includes(i)||m.done.includes(i)?x:'⭐'}</button>`).join('')}</div><div class="message">已经找到 ${m.done.length/2} 对</div><button class="wide-btn" onclick="state.memory=null;render()">重新开始</button></div>`}
function renderStoryOrder(){if(!state.order){const sets=[[['🥾','穿好雨靴'],['🐷','跳泥坑'],['🛁','回家洗澡']],[['🔔','收到警报'],['🚒','出发救援'],['🐱','救出小猫']]],steps=[...sets[Math.floor(Math.random()*sets.length)].map((x,i)=>({icon:x[0],text:x[1],order:i}))].sort(()=>Math.random()-.5);state.order={steps,picked:[]}}const o=state.order;return `<div class="lesson"><h2>🔢 故事顺序</h2><p>按事情发生的顺序点卡片</p><div class="story-order">${o.steps.map(x=>`<button class="order-card ${o.picked.includes(x.order)?'picked':''}" onclick="orderPick(this,${x.order})"><span>${x.icon}</span><b>${x.text}</b></button>`).join('')}</div><div class="message" id="message">先点第 1 步</div><button class="wide-btn" onclick="state.order=null;render()">换一个故事</button></div>`}
function orderPick(el,n){const o=state.order;if(o.picked.includes(n))return;if(n===o.picked.length){o.picked.push(n);el.classList.add('picked');if(o.picked.length===3){reward();$('#message').textContent='顺序全对啦 ⭐';speak('故事顺序全对啦')}else $('#message').textContent='再点第 '+(o.picked.length+1)+' 步'}else{el.classList.add('shake');setTimeout(()=>el.classList.remove('shake'),350);speak('想一想，哪件事先发生')}}
function renderSchool(){const all=window.GRADE_ONE_COURSES||[],subject=state.subject||'语文',items=all.filter(x=>x.subject===subject),units=[...new Set(items.map(x=>x.unit))],done=completedCourses(),doneCount=items.filter(x=>done.includes(courseKey(x))).length,percent=Math.round(doneCount/items.length*100);return shell('一年级上册课堂','浙江教材方向 · 每一课都能语音讲解',`<div class="subject-tabs"><button class="subject-tab ${subject==='语文'?'active':''}" onclick="showSubject('语文')">📕 语文 <small>${all.filter(x=>x.subject==='语文').length}课</small></button><button class="subject-tab ${subject==='数学'?'active':''}" onclick="showSubject('数学')">📘 数学 <small>${all.filter(x=>x.subject==='数学').length}课</small></button></div><div class="study-progress"><div><b>本学科学习进度</b><span>${doneCount} / ${items.length} 课</span></div><i><em style="width:${percent}%"></em></i><small>${doneCount?`已经完成 ${doneCount} 节，继续保持！`:'完成一节课，就会在这里留下小脚印。'}</small></div>${units.map((u,ui)=>`<section class="course-unit"><h2><span>${ui+1}</span>${esc(u)}</h2><div class="course-list">${items.filter(x=>x.unit===u).map(x=>{const finished=done.includes(courseKey(x));return `<button class="course-card ${finished?'finished':''}" onclick="openCourse('${subject}',${all.indexOf(x)})"><i>${x.icon}</i><span><b>${esc(x.title)}</b><small>${finished?'已完成 · 可以再复习':'讲解 · 图案 · 随堂练习'}</small></span><strong>${finished?'✓':'▶'}</strong></button>`}).join('')}</div></section>`).join('')}`)}
function showSubject(subject){state.subject=subject;appEl.innerHTML=renderSchool();scrollTo(0,0)}
function openCourse(subject,index){state.subject=subject;state.course=(window.GRADE_ONE_COURSES||[])[index];state.courseStep=0;go('classroom')}
function renderClassroom(){const c=state.course;if(!c)return renderSchool();const step=state.courseStep||0,text=step===0?c.intro:step===1?c.demo:c.question,label=['老师讲一讲','图案演示','随堂一题'][step];return `<div class="classroom"><div class="classroom-head"><button class="round-btn" onclick="go('school')">←</button><div><small>${esc(c.subject)} · ${esc(c.unit)}</small><h1>${c.icon} ${esc(c.title)}</h1></div></div><div class="class-progress"><i class="${step>=0?'on':''}"></i><i class="${step>=1?'on':''}"></i><i class="${step>=2?'on':''}"></i></div><article class="teacher-card"><div class="teacher-label">🧑🏻‍🏫 ${label}</div><div class="lesson-visual">${esc(c.visual)}</div><p>${esc(text)}</p><button class="listen-teacher" onclick="speakCourse()">🔊 老师讲给我听</button></article>${step===2?`<div class="course-answers">${c.choices.map((x,i)=>`<button onclick="courseAnswer(this,${i})">${esc(x)}</button>`).join('')}</div><div class="message" id="courseMessage"></div>`:''}<div class="class-actions"><button onclick="courseTurn(-1)" ${step===0?'disabled':''}>← 上一步</button><button class="primary" onclick="courseTurn(1)">${step===2?'完成课程 ⭐':'下一步 →'}</button></div><aside class="parent-tip">💡 小提示：${esc(c.tip)}</aside></div>`}
function speakCourse(){const c=state.course,step=state.courseStep||0;speak(step===0?c.intro:step===1?c.demo:c.question)}
function courseTurn(d){stopAudio();if(d>0&&(state.courseStep||0)===2){if(completeCourse(state.course))reward();go('school');speak('这节课完成啦，真棒');return}state.courseStep=Math.max(0,Math.min(2,(state.courseStep||0)+d));render()}
function courseAnswer(el,index){document.querySelectorAll('.course-answers button').forEach(b=>b.disabled=true);if(index===state.course.answer){el.classList.add('good');$('#courseMessage').textContent='答对啦！你听得真认真 ⭐';reward();speak('答对啦，你听得真认真')}else{el.classList.add('bad');const right=state.course.choices[state.course.answer];$('#courseMessage').textContent='再想一想，正确答案是：'+right;speak('再想一想')}}
function renderCreate(){return shell('创意乐园','自由探索，没有标准答案',`<div class="activity-grid"><button class="activity" onclick="go('coloring')"><span class="icon">🎨</span><b>涂颜色</b><small>点一点，给图画上色</small></button><button class="activity" onclick="go('draw')"><span class="icon">🖍️</span><b>自由画画</b><small>用手指画出想象</small></button><button class="activity" onclick="go('piano')"><span class="icon">🎹</span><b>音乐小琴</b><small>听听不同的声音</small></button><button class="activity" onclick="openGame('match')"><span class="icon">🧩</span><b>图形配对</b><small>观察和判断</small></button></div>`)}
function renderColoring(){const cur=state.coloring||colorings[0],fill=state.fill||palette[0];return `<div class="lesson coloring-game"><h2>🎨 涂颜色</h2><p>选图画、选颜色，再点要上色的地方</p><div class="coloring-choices">${colorings.map(x=>`<button class="coloring-choice ${x[0]===cur[0]?'active':''}" onclick="chooseColoring('${x[0]}')"><img src="img/coloring/${x[0]}.png" alt=""><span>${x[1]}</span></button>`).join('')}</div><div class="palette">${palette.map(c=>`<button class="${fill===c?'active':''}" style="background:${c}" onclick="setFill('${c}',this)" aria-label="选择颜色"></button>`).join('')}</div><canvas id="colorPad" width="560" height="560"></canvas><div class="color-actions"><button id="colorUndo" onclick="undoColoring()" disabled>↶ 撤销一步</button><button onclick="resetColoring()">↻ 重新涂</button><button class="finish-coloring" onclick="reward();speak('画得真漂亮')">⭐ 完成啦</button><button onclick="nextColoring()">换一张 →</button></div></div>`}
function initColoring(){const c=$('#colorPad');if(!c)return;const x=c.getContext('2d',{willReadFrequently:true}),img=new Image();state.colorUndo=[];state.colorReady=false;img.onload=()=>{x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);const r=Math.min(c.width/img.width,c.height/img.height),w=img.width*r,h=img.height*r;x.drawImage(img,(c.width-w)/2,(c.height-h)/2,w,h);state.colorReady=true};img.src='img/coloring/'+(state.coloring||colorings[0])[0]+'.png';c.onpointerup=e=>{if(!state.colorReady)return;e.preventDefault();const r=c.getBoundingClientRect(),sx=Math.floor((e.clientX-r.left)*c.width/r.width),sy=Math.floor((e.clientY-r.top)*c.height/r.height),before=x.getImageData(0,0,c.width,c.height);if(!floodFill(x,sx,sy,state.fill||palette[0]))return;state.colorUndo.push(before);if(state.colorUndo.length>8)state.colorUndo.shift();$('#colorUndo').disabled=false;tone(520,.08)};state.colorCtx=x}
function floodFill(ctx,sx,sy,hex){const im=ctx.getImageData(0,0,ctx.canvas.width,ctx.canvas.height),d=im.data,w=im.width,h=im.height,i0=(sy*w+sx)*4,target=[d[i0],d[i0+1],d[i0+2]],rgb=hex.match(/\w\w/g).map(x=>parseInt(x,16));if(target.every((v,i)=>Math.abs(v-rgb[i])<8)||(target[0]<80&&target[1]<80&&target[2]<80))return false;const seen=new Uint8Array(w*h),q=[sx,sy];let head=0,count=0;while(head<q.length&&count<w*h){const x=q[head++],y=q[head++],p=y*w+x;if(x<0||y<0||x>=w||y>=h||seen[p])continue;seen[p]=1;const i=p*4;if(Math.abs(d[i]-target[0])>38||Math.abs(d[i+1]-target[1])>38||Math.abs(d[i+2]-target[2])>38)continue;d[i]=rgb[0];d[i+1]=rgb[1];d[i+2]=rgb[2];count++;q.push(x+1,y,x-1,y,x,y+1,x,y-1)}if(!count)return false;ctx.putImageData(im,0,0);return true}
function chooseColoring(id){state.coloring=colorings.find(x=>x[0]===id);state.colorUndo=[];render()}function nextColoring(){const i=colorings.findIndex(x=>x[0]===(state.coloring||colorings[0])[0]);state.coloring=colorings[(i+1)%colorings.length];state.colorUndo=[];render()}function setFill(c,el){state.fill=c;document.querySelectorAll('.palette button').forEach(b=>b.classList.remove('active'));el.classList.add('active')}function undoColoring(){const im=state.colorUndo?.pop();if(!im||!state.colorCtx)return;state.colorCtx.putImageData(im,0,0);$('#colorUndo').disabled=!state.colorUndo.length}function resetColoring(){state.colorUndo=[];render()}
function renderDraw(){const pen=state.pen||'#ff6b6b',size=state.penSize||14,colors=['#ff6b6b','#ffb84d','#58c792','#4b9cff','#9b78e8','#344052'];return `<div class="lesson draw-game"><h2>🖍️ 自由画画</h2><p>选颜色和笔头大小，用手指画出想象</p><div class="draw-tools"><div class="draw-colors">${colors.map(c=>`<button class="draw-color ${pen===c?'active':''}" style="background:${c}" onclick="setPen('${c}',this)" aria-label="选择颜色"></button>`).join('')}<button class="eraser-btn ${pen==='#fff'?'active':''}" onclick="setPen('#fff',this)">🧽 橡皮</button></div><div class="brush-sizes"><span>笔头</span>${[[8,'小'],[14,'中'],[26,'大']].map(x=>`<button class="brush-btn ${size===x[0]?'active':''}" onclick="setBrush(${x[0]},this)"><i style="width:${x[0]}px;height:${x[0]}px"></i>${x[1]}</button>`).join('')}</div></div><canvas id="drawPad" width="700" height="700" aria-label="自由画板"></canvas><div class="draw-actions"><button onclick="clearPad()">↻ 擦干净</button><button class="finish-drawing" onclick="reward();speak('画得真漂亮')">⭐ 画好啦</button></div></div>`}
function initDraw(){const c=$('#drawPad');if(!c)return;const x=c.getContext('2d');x.lineCap='round';x.lineJoin='round';let down=false;const point=e=>{const r=c.getBoundingClientRect();return[(e.clientX-r.left)*c.width/r.width,(e.clientY-r.top)*c.height/r.height]};const style=()=>{x.lineWidth=state.penSize||14;x.strokeStyle=state.pen||'#ff6b6b';x.fillStyle=state.pen||'#ff6b6b'};c.onpointerdown=e=>{e.preventDefault();down=true;c.setPointerCapture?.(e.pointerId);const[a,b]=point(e);style();x.beginPath();x.arc(a,b,(state.penSize||14)/2,0,Math.PI*2);x.fill();x.beginPath();x.moveTo(a,b)};c.onpointermove=e=>{if(!down)return;e.preventDefault();const[a,b]=point(e);style();x.lineTo(a,b);x.stroke()};c.onpointerup=c.onpointercancel=e=>{if(!down)return;down=false;c.releasePointerCapture?.(e.pointerId)};state.pad=x}
function setPen(c,el){state.pen=c;document.querySelectorAll('.draw-color,.eraser-btn').forEach(b=>b.classList.remove('active'));el?.classList.add('active')}function setBrush(n,el){state.penSize=n;document.querySelectorAll('.brush-btn').forEach(b=>b.classList.remove('active'));el?.classList.add('active')}function clearPad(){state.pad?.clearRect(0,0,700,700)}
function renderPiano(){const keys=[['do','#ff746c',261.6],['re','#ffad5c',293.7],['mi','#ffd65a',329.6],['fa','#6ed19d',349.2],['sol','#65b8ff',392],['la','#8b91ff',440],['si','#b788ed',493.9],['do','#ef7eba',523.3]];return `<div class="lesson"><h2>🎹 音乐小琴</h2><p>点琴键，听听声音有什么不同</p><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:18px 0">${keys.map(k=>`<button onclick="tone(${k[2]})" style="height:120px;border-radius:20px;background:${k[1]};color:white;font-size:20px;font-weight:900">${k[0]}</button>`).join('')}</div><button class="wide-btn" onclick="playSong()">▶ 听一段小星星</button></div>`}
function tone(freq,d=.35){const C=window.AudioContext||window.webkitAudioContext;state.ctx=state.ctx||new C();const o=state.ctx.createOscillator(),g=state.ctx.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.15,state.ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,state.ctx.currentTime+d);o.connect(g).connect(state.ctx.destination);o.start();o.stop(state.ctx.currentTime+d)}function playSong(){[261.6,261.6,392,392,440,440,392].forEach((n,i)=>setTimeout(()=>tone(n,.42),i*480))}
function render(){const pages={home:renderHome,school:renderSchool,classroom:renderClassroom,stories:()=>renderStories('all'),reader:renderReader,learn:renderLearn,lesson:renderLesson,games:renderGames,game:renderGame,create:renderCreate,coloring:renderColoring,draw:renderDraw,piano:renderPiano};appEl.innerHTML=(pages[state.page]||renderHome)();$('#backBtn').classList.toggle('hidden',state.page==='home'||state.page==='reader'||state.page==='classroom');$('#bottomNav').classList.toggle('hidden',['reader','classroom','game','lesson','coloring','draw','piano'].includes(state.page));document.querySelectorAll('#bottomNav button').forEach(b=>b.classList.toggle('active',b.dataset.go===state.page));$('#stars').textContent=state.stars;if(state.page==='draw')initDraw();if(state.page==='coloring')initColoring();if(state.page==='game'&&state.game==='pawMaze')initPawMaze();if(state.page==='game'&&state.game==='snakeFruit')initSnakeFruit();if(state.page==='game'&&state.game==='beeGarden')initBeeGarden();scrollTo(0,0)}
$('#backBtn').onclick=back;$('#homeBtn').onclick=()=>go('home');$('#soundBtn').onclick=()=>{state.muted=!state.muted;stopAudio();$('#soundBtn').textContent=state.muted?'🔇':'🔊'};document.querySelectorAll('#bottomNav button').forEach(b=>b.onclick=()=>go(b.dataset.go));
window.go=go;window.showSubject=showSubject;window.openCourse=openCourse;window.speakCourse=speakCourse;window.courseTurn=courseTurn;window.courseAnswer=courseAnswer;window.openBook=openBook;window.turn=turn;window.readPage=readPage;window.toggleAutoRead=toggleAutoRead;window.readAutoPage=readAutoPage;window.toggleFav=toggleFav;window.openLearn=openLearn;window.learnTurn=learnTurn;window.speakWord=speakWord;window.openGame=openGame;window.gamePrompt=gamePrompt;window.answer=answer;window.flipCard=flipCard;window.sortAnswer=sortAnswer;window.popBalloon=popBalloon;window.brandAnswer=brandAnswer;window.mazeMove=mazeMove;window.orderPick=orderPick;window.resetSnakeFruit=resetSnakeFruit;window.chooseColoring=chooseColoring;window.nextColoring=nextColoring;window.setFill=setFill;window.undoColoring=undoColoring;window.resetColoring=resetColoring;window.setPen=setPen;window.setBrush=setBrush;window.clearPad=clearPad;window.tone=tone;window.playSong=playSong;window.state=state;window.render=render;render();
