const $=s=>document.querySelector(s);const appEl=$('#app');const player=$('#player');let voiceRun=0;
function savedGameMenu(){try{const menu=JSON.parse(sessionStorage.getItem('kid-game-menu-v1')||'null');return menu&&typeof menu==='object'?menu:{}}catch{return{}}}
function savedStoryMenu(){try{const menu=JSON.parse(sessionStorage.getItem('kid-story-menu-v1')||'null');return menu&&typeof menu==='object'?menu:{}}catch{return{}}}
const gameMenu=savedGameMenu();
const storyMenu=savedStoryMenu();
const state={gameMenu,gameCategory:gameMenu.category,storyMenu,storyFilter:storyMenu.filter||'all',page:['games','learn','stories','school','videos','writing','pet','garden'].includes(new URLSearchParams(location.search).get('section'))?new URLSearchParams(location.search).get('section'):'home',stack:[],book:null,pageNo:0,muted:false,readerPaused:false,stars:+localStorage.getItem('kid-stars-v2')||0,favs:JSON.parse(localStorage.getItem('kid-favs-v2')||'[]')};
const customArt=new Set(['dino_01','dino_02',...(window.BOOKS||[]).filter(b=>b.art||b.group==='peppa'||b.group==='paw').map(b=>b.id)]);
function artSrc(b){return `${b.art||`art/${b.id}.${b.group==='peppa'||b.group==='paw'?'webp':'png'}`}?v=20260930a`}
const learnSets={
  animals:[['🐼','panda','熊猫'],['🐘','elephant','大象'],['🦁','lion','狮子'],['🐰','rabbit','兔子'],['🐬','dolphin','海豚'],['🦒','giraffe','长颈鹿']],
  fruit:[['🍎','apple','苹果'],['🍌','banana','香蕉'],['🍓','strawberry','草莓'],['🍉','watermelon','西瓜'],['🍇','grape','葡萄'],['🍊','orange','橙子']],
  nature:[['☀️','sun','太阳'],['🌙','moon','月亮'],['🌧️','rain','下雨'],['🌈','rainbow','彩虹'],['🌳','tree','树'],['🌸','flower','花']],
  feelings:[['😄','happy','开心'],['😢','sad','难过'],['😠','angry','生气'],['😨','scared','害怕'],['😴','tired','累了'],['🥰','love','爱']]
};
const gameSets={
  princess:{title:'公主换装舞会',icon:'👑',desc:'10 位公主，礼服和饰品自由搭配',category:'create',action:'换一换',help:'先选一位公主，再给她换衣服、发型和配饰。换好后点换好啦，她会和你说话哦。'},
  snakeFruit:{title:'小虫吃水果',icon:'🐛',desc:'自由滑动，帮小虫找苹果',category:'swipe',action:'滑一滑',help:'在草地上滑动手指，小虫就会跟着转弯。找到五个苹果就成功啦。'},
  pawMaze:{title:'手指救援迷宫',icon:'🐾',desc:'沿着小路滑到小猫身边',category:'swipe',action:'滑一滑',help:'按住阿奇，沿着浅色小路一直滑，找到小猫。走错了也没关系。'},
  beeGarden:{title:'小蜜蜂采花',icon:'🐝',desc:'拖着蜜蜂找齐六朵花',category:'swipe',action:'拖一拖',help:'按住小蜜蜂，在花园里自由滑动，把六朵花都找到。'},
  rocketStars:{title:'火箭收星星',icon:'🚀',desc:'手指带着火箭自由飞',category:'swipe',action:'拖一拖',help:'按住火箭，在太空里自由滑动，把八颗星星都收起来。'},
  fruitBasket:{title:'水果回家',icon:'🍎',desc:'把水果和玩具送回自己的家',category:'swipe',action:'拖一拖',help:'按住中间的东西，把水果拖进果篮，把玩具拖进玩具箱。'},
  fireflyTrail:{title:'萤火虫亮灯',icon:'✨',desc:'手指不停，点亮夜空小灯',category:'swipe',action:'滑一滑',help:'按住小萤火虫，从发亮的圆点开始滑，按照小路把灯一盏一盏点亮。'},
  colorTrain:{title:'彩虹小火车',icon:'🚂',desc:'把彩色乘客送上同色车厢',category:'swipe',action:'拖一拖',help:'按住彩色乘客，把它拖到一样颜色的车厢里。'},
  bubbleBath:{title:'泡泡洗澡',icon:'🫧',desc:'点破泡泡，帮小鸭洗澡',category:'tap',action:'点一点',help:'用小手点一点击破泡泡，帮小鸭把所有泡泡都洗干净。'},
  pop:{title:'彩色气球',icon:'🎈',desc:'找准颜色点气球',category:'tap',action:'点一点',help:'听清楚要找的颜色，再把这种颜色的气球全部点出来。'},
  peppaCount:{title:'泥坑数数',icon:'🐷',desc:'看一看有几个泥坑',category:'tap',action:'点答案',help:'数一数画面里有几个泥坑，再点正确的数字。'},
  rhythmTap:{title:'森林节奏',icon:'🥁',desc:'看灯光，照着顺序点',category:'tap',action:'跟着点',help:'先看小动物亮起来的顺序，再照着顺序点一遍。完成三轮就成功啦。'},
  sound:{title:'听音找词',icon:'👂',desc:'听声音，找出正确图片',category:'find',action:'听一听',help:'点喇叭听声音，再从图片里找到它。'},
  match:{title:'图形配对',icon:'🧩',desc:'找到一样的朋友',category:'find',action:'找一找',help:'认真看中间的图案，再找到和它一模一样的朋友。'},
  memory:{title:'动物翻翻乐',icon:'🧠',desc:'翻一翻，找出相同动物',category:'find',action:'翻一翻',help:'每次翻两张卡片，记住它们的位置，把一样的动物找成一对。'},
  sort:{title:'物品分类',icon:'🧺',desc:'把东西放进正确篮子',category:'find',action:'分一分',help:'看看中间是什么，再选择它应该放进哪一个篮子。'},
  peppaPicnic:{title:'野餐篮',icon:'🧺',desc:'找出适合带去野餐的东西',category:'find',action:'选一选',help:'看看这个东西适不适合带去野餐，再点正确的篮子。'},
  pawGear:{title:'救援装备',icon:'🎒',desc:'为任务找到合适的伙伴',category:'find',action:'选一选',help:'先看看发生了什么，再选一位最适合完成任务的救援伙伴。'},
  brandMemory:{title:'伙伴翻翻乐',icon:'💛',desc:'记住伙伴藏在哪里',category:'find',action:'翻一翻',help:'每次翻两张卡片，找出两个一样的伙伴。'},
  shadowMatch:{title:'影子好朋友',icon:'🔦',desc:'看看影子是谁的',category:'find',action:'找一找',help:'认真看看黑色影子的形状，再从下面找到它的好朋友。'},
  count:{title:'数一数',icon:'🔢',desc:'看一看一共有几个',category:'think',action:'想一想',help:'慢慢数一数画面里有多少颗星星，再点正确的数字。'},
  storyOrder:{title:'故事排排队',icon:'📚',desc:'按先后顺序点卡片',category:'think',action:'排一排',help:'想一想事情先做什么、再做什么，按照顺序点三张卡片。'}
};
for(const entry of window.NEW_GAMES?.entries||[])gameSets[entry.id]={...entry,newRelease:true};
const gameCategories=[
  {id:'create',icon:'🎨',title:'创作与陪伴',sub:'画画 · 换装 · 养宠物',color:'#d58daf',help:'选择小小画家、公主换装、音乐小琴，或者和小伙伴种菜、玩耍。'},
  {id:'swipe',icon:'☝️',title:'手指冒险',sub:'滑动 · 拖动 · 拼图',color:'#80b69a',help:'选一个游戏，用小手滑一滑、拖一拖。'},
  {id:'challenge',icon:'🧩',title:'动脑挑战',sub:'路线 · 记忆 · 逻辑',color:'#a389cf',help:'慢慢想，试试看。可以自己选难度，随时重新玩。'}
];
const curatedGameIds=new Set(['princess','pet','garden','artist','piano','pawMaze','snakeFruit','ngBentoChef','ngAnimalPuzzle','ngBunnyTrail','memory','cgRobotRoute','cgSlidePuzzle','cgMemoryLights','cgLogicGarden']);
const creativeGames=[
  {id:'pet',title:'宠物小屋',icon:'🐰',desc:'喂饭、洗澡，照顾软萌朋友',category:'create',action:'照顾它'},
  {id:'garden',title:'小小菜园',icon:'🌱',desc:'种下、浇水，收获四种蔬果',category:'create',action:'种一种'},
  {id:'artist',title:'小小画家',icon:'🎨',desc:'26个跟画、40张涂色、磁铁修形',category:'create',action:'画一画'},
  {id:'coloring',title:'涂颜色',icon:'🎨',desc:'给喜欢的图画上颜色',category:'create',action:'涂一涂'},
  {id:'draw',title:'自由画画',icon:'🖍️',desc:'画笔、形状、对称，收藏小画作',category:'create',action:'画一画'},
  {id:'piano',title:'音乐小琴',icon:'🎹',desc:'50 首小歌，亮灯跟着弹',category:'create',action:'弹一弹'}
];
const colorings=[['cat','小猫'],['dog','小狗'],['rabbit','小兔'],['fish','小鱼'],['butterfly','蝴蝶'],['flower','花朵'],['car','小汽车'],['house','小房子'],['star','星星'],['icecream','冰淇淋']];
const palette=['#ff6b6b','#ffad5c','#ffd65a','#62ce91','#56b4ff','#8c86f5','#d47be7','#795548'];
const drawStamps=['⭐','❤️','🌸','🌈','🦕','🐾'];
const swipeMazePaths=[[0,1,2,9,16,17,18,25,32,31,30,37,44,45,46,47,48],[0,7,14,15,16,9,10,11,18,25,24,31,38,39,40,47,48],[0,1,8,15,22,23,24,17,10,11,12,19,26,33,32,39,46,47,48]];
const beeFlowers=[[17,18],[78,17],[49,34],[19,61],[79,65],[49,86]];
const rocketStarPoints=[[16,18],[48,13],[82,22],[69,44],[26,48],[14,75],[48,82],[83,72]];
const fireflyPoints=[[14,78],[26,57],[18,34],[39,20],[55,40],[72,22],[85,45],[68,66],[86,82]];
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function voiceKey(text,lang){return `${String(lang).toLowerCase().startsWith('en')?'en':'zh'}|${text}`}
function playSpoken(text,lang='zh-CN',onend=null){
  const run=++voiceRun;
  if(state.muted){onend?.();return}

  let fallbackStarted=false,finished=false;
  const finish=()=>{if(run!==voiceRun||finished)return;finished=true;onend?.()};
  const fallback=()=>{if(run!==voiceRun||fallbackStarted||finished)return;fallbackStarted=true;fallbackSpeech(text,lang,finish,run)};
  const start=()=>{
    if(run!==voiceRun||state.muted)return;
    const src=window.VOICE_MAP?.[voiceKey(text,lang)];
    if(src){player.onended=finish;player.onerror=fallback;player.src=src;player.play().catch(error=>{if(error?.name==='AbortError'&&state.page==='reader'&&state.readerPaused)return;fallback()});return}
    fallback();
  };
  if(window.ensureVoiceCatalogue&&!window.VOICE_CATALOGUE_READY){window.ensureVoiceCatalogue().then(start,()=>fallback());return}
  start();
}
function fallbackSpeech(text,lang,onend,run=voiceRun){
  if(run!==voiceRun)return;
  player.onended=null;player.onerror=null;player.pause();player.removeAttribute('src');
  if(['game','games','pet','garden','piano','draw','coloring'].includes(state.page)){onend?.();return}
  if(!window.speechSynthesis){onend?.();return}const u=new SpeechSynthesisUtterance(text);u.lang=lang;u.rate=.82;u.pitch=1.08;u.onend=()=>{if(run===voiceRun)onend?.()};speechSynthesis.speak(u)
}
function speak(text,lang='zh-CN'){stopAudio();playSpoken(text,lang)}
function stopAudio(){voiceRun++;player.pause();player.onended=null;player.onerror=null;player.removeAttribute('src');if(window.speechSynthesis)speechSynthesis.cancel()}
function go(page,data=null,push=true){if(state.page==='games'&&page!=='games')rememberGameMenu();if(state.page==='stories'&&page!=='stories')rememberStoryMenu();stopInteractiveGame();stopAudio();if(state.page==='reader'&&page!=='reader'){state.readerAuto=false;state.readerPaused=false}if(push&&state.page!==page)state.stack.push({page:state.page,book:state.book,pageNo:state.pageNo});state.page=page;if(data?.book!==undefined)state.book=data.book;if(data?.pageNo!==undefined)state.pageNo=data.pageNo;render();if(['coloring','draw','piano'].includes(page))creativeGameHelp()}
function back(){if(state.page==='reader')return leaveReader();if(window.KNOW?.backRoot())return;if(state.page==='games')rememberGameMenu();if(state.page==='stories')rememberStoryMenu();stopInteractiveGame();stopAudio();const last=state.stack.pop();if(!last)return go('home',null,false);state.page=last.page;state.book=last.book;state.pageNo=last.pageNo;render()}
function reward(){state.stars++;localStorage.setItem('kid-stars-v2',state.stars);$('#stars').textContent=state.stars}
function courseKey(c){return `${c.subject}:${c.unit}:${c.title}`}
function completedCourses(){return JSON.parse(localStorage.getItem('kid-course-done-v1')||'[]')}
function completeCourse(c){const done=completedCourses(),key=courseKey(c);if(!done.includes(key)){done.push(key);localStorage.setItem('kid-course-done-v1',JSON.stringify(done));return true}return false}
function shell(title,sub,body){return `<div class="page-head"><div><h1>${title}</h1><p>${sub}</p></div></div>${body}`}
function renderHome(){return window.HOME.render()}
function artFallback(img){img.onerror=null;img.parentElement?.classList.remove('sprite-page','sprite-sheet');img.style.cssText='';img.src='img/dino/dino_01/page1.webp'}
function thumb(b){if(b.reillustrated)return `<div class="book-cover"><img src="${esc(b.cover)}" loading="lazy" decoding="async" onerror="artFallback(this)" alt="${esc(b.title)}"></div>`;if(b.artEmoji)return `<div class="book-cover story-card-art theme-${esc(b.theme||'garden')}"><span class="scene-orb"></span><span class="scene-emoji">${esc(b.artEmoji)}</span><i>✦</i></div>`;if(customArt.has(b.id))return `<div class="book-cover sprite-sheet"><img src="${artSrc(b)}" onerror="artFallback(this)" alt="${esc(b.title)}"></div>`;let p=b.pages[0]||{};let src=p.img||`${b.img_prefix.replace(/\/?$/,'/')}cover.webp`;return `<div class="book-cover"><img src="${esc(src)}" onerror="artFallback(this)" alt="${esc(b.title)}"></div>`}
const STORY_FILTERS=[['all','📚','全部'],['peppa','🐷','小猪佩奇'],['paw','🐾','汪汪队'],['zootopia','🐰','朱迪和尼克'],['princess','👑','公主童话'],['dino','🦕','生活成长'],['poem','🌿','唐诗宋词'],['idiom','💡','小故事']];
function validStoryFilter(filter){return STORY_FILTERS.some(x=>x[0]===filter)?filter:'all'}
function persistStoryMenu(){try{sessionStorage.setItem('kid-story-menu-v1',JSON.stringify(state.storyMenu))}catch{}}
function rememberStoryMenu(bookId){if(state.page!=='stories')return false;const cards=[...(document.querySelectorAll?.('.book')||[])],card=cards.find(x=>x.dataset?.bookId===bookId)||document.activeElement?.closest?.('.book');state.storyMenu={filter:validStoryFilter(state.storyFilter),y:Math.max(0,scrollY),rail:$('.filters')?.scrollLeft||0,width:innerWidth,cardId:bookId||card?.dataset?.bookId||state.storyMenu.cardId,cardTop:card?.getBoundingClientRect?.().top??state.storyMenu.cardTop};persistStoryMenu();return true}
function restoreStoryMenu(){const grid=$('.book-grid');if(!grid)return;requestAnimationFrame(()=>{if(state.page!=='stories'||$('.book-grid')!==grid)return;const rail=$('.filters'),active=rail?.querySelector?.('.chip.active');if(rail){if(Number.isFinite(state.storyMenu.rail))rail.scrollLeft=state.storyMenu.rail;if(active){const a=active.getBoundingClientRect(),r=rail.getBoundingClientRect();if(a.left<r.left||a.right>r.right)rail.scrollLeft=Math.max(0,active.offsetLeft-(rail.clientWidth-active.clientWidth)/2)}}let y=Number.isFinite(state.storyMenu.y)?Math.max(0,state.storyMenu.y):0;if(state.storyMenu.width!==innerWidth&&Number.isFinite(state.storyMenu.cardTop)){const card=[...grid.querySelectorAll('.book')].find(x=>x.dataset?.bookId===state.storyMenu.cardId);if(card)y=card.getBoundingClientRect().top+scrollY-state.storyMenu.cardTop}scrollTo(0,y)})}
function renderStories(filter=state.storyFilter||'all'){filter=validStoryFilter(filter);state.storyFilter=filter;state.storyMenu={...state.storyMenu,filter};let all=[...(window.BOOKS||[])].sort((a,b)=>Number(b.id.startsWith('tablet_story_'))-Number(a.id.startsWith('tablet_story_'))||Number(b.id.startsWith('adventure_'))-Number(a.id.startsWith('adventure_'))||Number(b.id.startsWith('extra_'))-Number(a.id.startsWith('extra_'))),books=filter==='all'?all:all.filter(b=>b.group===filter);return shell('故事屋',`${all.length} 本适合 5 岁孩子的短故事，点开就会自动讲`,`<div class="filters" role="tablist" aria-label="故事分类">${STORY_FILTERS.map(x=>`<button role="tab" aria-selected="${filter===x[0]}" class="chip ${filter===x[0]?'active':''}" onclick="showBooks('${x[0]}')">${x[1]} ${x[2]}</button>`).join('')}</div><div class="book-grid">${books.map(b=>`<button class="book" data-book-id="${esc(b.id)}" onclick="openBook('${b.id}',0)">${thumb(b)}${(b.id.startsWith('adventure_')||b.id.startsWith('tablet_story_'))?'<span class="book-badge">新故事</span>':''}<div class="info"><b>${esc(b.title.replace(/^(古诗|成语)：/,''))}</b><small>${b.id.startsWith('tablet_story_')?'5 幅画面 · 连续讲故事':b.id.startsWith('adventure_')?'6 幅画面 · 更长的故事':`${b.pages.length} 页 · 有声故事`}</small></div></button>`).join('')}</div>`)}
function showBooks(filter){filter=validStoryFilter(filter);state.storyFilter=filter;state.storyMenu={filter,y:0,rail:0,width:innerWidth};persistStoryMenu();appEl.innerHTML=renderStories(filter);scrollTo(0,0);requestAnimationFrame(()=>{const bar=document.querySelector('.filters'),active=bar?.querySelector('.chip.active');if(bar&&active){bar.scrollTo({left:Math.max(0,active.offsetLeft-(bar.clientWidth-active.clientWidth)/2),behavior:'smooth'});state.storyMenu.rail=bar.scrollLeft;persistStoryMenu()}})}
function openBook(id,n=0){const b=(window.BOOKS||[]).find(x=>x.id===id);if(!b)return;if(state.page==='stories')rememberStoryMenu(id);state.readerAuto=!state.muted;state.readerPaused=false;state.book=b;state.pageNo=Math.max(0,Math.min(n,b.pages.length-1));localStorage.setItem('kid-recent-v2',JSON.stringify({id:b.id,title:b.title,page:state.pageNo}));go('reader',{book:b,pageNo:state.pageNo});if(state.readerAuto)readAutoPage()}
function pageVisual(b,n,mode='stopped'){const p=b.pages[n]||{},playing=mode==='playing',paused=mode==='paused',control=`<button class="story-touch" onclick="toggleAutoRead()" aria-label="${playing?'暂停故事':paused?'继续播放故事':'播放故事'}">${playing?'⏸ 点画面暂停':paused?'▶ 点画面继续':'▶ 点画面播放'}</button>`,cls=playing?'story-playing':paused?'story-paused':'';if(b.reillustrated)return `<div class="story-picture reillustrated-story ${b.id.startsWith('adventure_')?'adventure-story':''} ${cls}"><img src="${esc(p.img)}" decoding="async" onerror="artFallback(this)" alt="${esc(b.title)}第${n+1}页">${control}</div>`;if(p.emoji)return `<div class="story-picture story-card-art story-scene theme-${esc(b.theme||'garden')} ${cls}"><span class="scene-cloud one">☁️</span><span class="scene-cloud two">☁️</span><span class="scene-orb"></span><span class="scene-emoji">${esc(p.emoji)}</span><i>✦</i>${control}</div>`;if(customArt.has(b.id)){const col=n%2,row=Math.floor(n/2);return `<div class="story-picture sprite-page ${cls}"><img src="${artSrc(b)}" style="left:-${col*100}%;top:-${row*100}%" onerror="artFallback(this)" alt="${esc(b.title)}第${n+1}页">${control}</div>`}let src=p.img||`${b.img_prefix.replace(/\/?$/,'/')}page${n+1}.webp`;return `<div class="story-picture ${cls}"><img src="${esc(src)}" onerror="artFallback(this)" alt="${esc(b.title)}第${n+1}页">${control}</div>`}
function renderReader(){const b=state.book,p=b.pages[state.pageNo],n=state.pageNo,total=b.pages.length,autoClass=state.readerAuto?(state.readerPaused?'paused':'playing'):'',returnLabel=state.stack.at(-1)?.page==='home'?'返回首页':'返回故事屋';return `<div class="reader"><div class="reader-top"><button class="round-btn" onclick="leaveReader()" aria-label="${returnLabel}">←</button><h1>${esc(b.title)}</h1><button class="round-btn" onclick="toggleFav('${b.id}')" aria-label="${state.favs.includes(b.id)?'取消收藏':'收藏'}${esc(b.title)}">${state.favs.includes(b.id)?'❤️':'🤍'}</button></div><div class="progress-dots">${b.pages.map((_,i)=>`<i class="dot ${i===n?'on':''}"></i>`).join('')}</div><article class="reader-stage">${pageVisual(b,n,state.readerAuto?(state.readerPaused?'paused':'playing'):'stopped')}<div class="story-text">${esc(p.text).replace(/\n/g,'<br>')}</div></article><div class="reader-controls"><button class="control" onclick="turn(-1)" ${n===0?'disabled':''}>← 上一页</button><button class="control primary" onclick="readPage()">🔊 读这一页</button><button class="control" onclick="turn(1)">${n===total-1?'读完啦':'下一页 →'}</button></div><button class="auto-read-btn ${autoClass}" onclick="toggleAutoRead()">${state.readerPaused?`▶ 继续播放 · 第 ${n+1}/${total} 页`:state.readerAuto?`⏸ 暂停一下 · 第 ${n+1}/${total} 页`:'▶ 从这一页开始连续听故事'}</button></div>`}
function leaveReader(){if(state.page!=='reader')return false;state.readerAuto=false;state.readerPaused=false;stopAudio();let last=state.stack.pop();while(last?.page==='reader')last=state.stack.pop();if(last){state.page=last.page;state.book=last.book;state.pageNo=last.pageNo}else state.page='stories';render();return true}
function readPage(){state.readerAuto=false;state.readerPaused=false;stopAudio();render();playSpoken(state.book.pages[state.pageNo].text)}
function toggleAutoRead(){if(state.readerAuto&&!state.readerPaused){state.readerPaused=true;player.pause();if(window.speechSynthesis?.speaking)speechSynthesis.pause();render();return}if(state.readerAuto&&state.readerPaused){state.readerPaused=false;render();if(player.src){const run=voiceRun;player.play().catch(error=>{if(run!==voiceRun||error?.name==='AbortError')return;state.readerAuto=false;render()})}else if(window.speechSynthesis?.paused)speechSynthesis.resume();else readAutoPage();return}if(state.muted){state.muted=false;$('#soundBtn').textContent='🔊'}state.readerAuto=true;state.readerPaused=false;stopAudio();render();readAutoPage()}
function readAutoPage(){if(!state.readerAuto||state.readerPaused||state.page!=='reader'||!state.book)return;playSpoken(state.book.pages[state.pageNo].text,'zh-CN',()=>{if(!state.readerAuto||state.readerPaused||state.page!=='reader')return;if(state.pageNo>=state.book.pages.length-1){state.readerAuto=false;state.readerPaused=false;reward();render();speak('故事读完啦');return}state.pageNo++;localStorage.setItem('kid-recent-v2',JSON.stringify({id:state.book.id,title:state.book.title,page:state.pageNo}));render();setTimeout(readAutoPage,250)})}
function turn(d){state.readerAuto=false;state.readerPaused=false;if(state.pageNo+d>=state.book.pages.length){reward();leaveReader();return}state.pageNo=Math.max(0,state.pageNo+d);localStorage.setItem('kid-recent-v2',JSON.stringify({id:state.book.id,title:state.book.title,page:state.pageNo}));stopAudio();render()}
function toggleFav(id){state.favs=state.favs.includes(id)?state.favs.filter(x=>x!==id):[...state.favs,id];localStorage.setItem('kid-favs-v2',JSON.stringify(state.favs));render()}
function renderLearn(){return window.KNOW?KNOW.renderHub():shell('认一认','认知内容正在准备中','')}
function openLearn(k){state.learn=k;go('lesson')}
function renderLesson(){if(state.learn==='recognition'&&window.KNOW)return KNOW.renderLesson();const list=learnSets[state.learn]||learnSets.animals;const item=list[state.learnNo||0];return `<div class="lesson"><h2>点卡片听一听</h2><button class="flash" style="width:100%;border:0" onclick="speakWord('${item[1]}','${item[2]}')"><span class="emoji">${item[0]}</span><span class="word">${item[1]}</span><span class="meaning">${item[2]}</span></button><div class="reader-controls"><button class="control" onclick="learnTurn(-1)">← 上一个</button><button class="control primary" onclick="speakWord('${item[1]}','${item[2]}')">🔊 听发音</button><button class="control" onclick="learnTurn(1)">下一个 →</button></div></div>`}
function speakWord(en,zh){stopAudio();playSpoken(en,'en-US',()=>playSpoken(zh,'zh-CN'))}function learnTurn(d){stopAudio();const n=(learnSets[state.learn]||[]).length;state.learnNo=((state.learnNo||0)+d+n)%n;render()}
function allGameEntries(){return [
  ...Object.entries(gameSets).map(([id,g])=>({...g,id,type:'local'})),
  ...creativeGames.map(g=>({...g,type:'creative'}))
].filter(g=>curatedGameIds.has(g.id)).map(g=>({...g,category:g.id.startsWith('cg')||g.id==='memory'?'challenge':g.category})).sort((a,b)=>Number(Boolean(b.newRelease))-Number(Boolean(a.newRelease)))}
function gameDirectoryCard(g){const fresh=Boolean(g.newRelease)||['fruitBasket','fireflyTrail','colorTrain','bubbleBath','rhythmTap','shadowMatch'].includes(g.id),inside=`<span class="game-card-action">${esc(g.action)}</span><span class="game-card-icon">${g.icon}</span><span class="game-card-copy"><b>${esc(g.title)}</b><small>${esc(g.desc)}</small></span><strong>${fresh?'新游戏':'开始'} ›</strong>`;if(g.type==='creative')return `<button class="game-choice" data-game-id="${g.id}" onclick="${g.id==='artist'?'HOME.openArtist()':`go('${g.id}')`}">${inside}</button>`;return `<button class="game-choice" data-game-id="${g.id}" onclick="openGame('${g.id}')">${inside}</button>`}
function renderGames(){const entries=allGameEntries(),cat=gameCategories.some(x=>x.id===state.gameCategory)?state.gameCategory:'create',active=gameCategories.find(x=>x.id===cat),shown=entries.filter(x=>x.category===cat);state.gameCategory=cat;return `<section class="game-home">
  <div class="game-hero"><div><small>果粒橙游戏乐园</small><h1>只留下好玩的</h1><p>15 个精选玩法，分成三组，点开就能玩。</p></div><span>🎮</span></div>
  <div class="game-category-rail" role="tablist" aria-label="游戏分类">${gameCategories.map(c=>{const count=entries.filter(x=>x.category===c.id).length;return `<button role="tab" aria-selected="${c.id===cat}" class="game-category ${c.id===cat?'active':''}" style="--cat:${c.color}" onclick="selectGameCategory('${c.id}')"><span>${c.icon}</span><b>${c.title}</b><small>${count} 个</small></button>`}).join('')}</div>
  <div class="game-category-head" style="--cat:${active.color}"><span>${active.icon}</span><div><h2>${active.title}</h2><p>${active.sub}</p></div><button class="game-directory-help" onclick="categoryGameHelp()" aria-label="听${esc(active.title)}的玩法">🔊 <span>听一听</span></button></div>
  <div class="game-choice-grid">${shown.map(gameDirectoryCard).join('')}</div>
  </section>`}
function persistGameMenu(){try{sessionStorage.setItem('kid-game-menu-v1',JSON.stringify(state.gameMenu))}catch{}}
function rememberGameMenu(){if(state.page!=='games')return;const card=document.activeElement?.closest('.game-choice');state.gameMenu={category:state.gameCategory,y:Math.max(0,scrollY),rail:$('.game-category-rail')?.scrollLeft||0,width:innerWidth,cardId:card?.dataset.gameId,cardTop:card?.getBoundingClientRect().top};persistGameMenu()}
function restoreGameMenu(){const home=$('.game-home');if(!home)return;requestAnimationFrame(()=>{if(state.page!=='games'||$('.game-home')!==home)return;const rail=$('.game-category-rail'),active=$('.game-category.active');if(rail){if(Number.isFinite(state.gameMenu.rail))rail.scrollLeft=state.gameMenu.rail;if(active){const a=active.getBoundingClientRect(),r=rail.getBoundingClientRect();if(a.left<r.left||a.right>r.right)rail.scrollLeft=Math.max(0,active.offsetLeft-(rail.clientWidth-active.clientWidth)/2)}}let y=Number.isFinite(state.gameMenu.y)?Math.max(0,state.gameMenu.y):0;if(state.gameMenu.width!==innerWidth&&Number.isFinite(state.gameMenu.cardTop)){const card=[...home.querySelectorAll('.game-choice')].find(x=>x.dataset.gameId===state.gameMenu.cardId);if(card)y=card.getBoundingClientRect().top+scrollY-state.gameMenu.cardTop}scrollTo(0,y)})}
function syncGameMenuUrl(){try{const url=new URL(location.href),section=['games','game','coloring','draw','piano'].includes(state.page)?'games':state.page==='learn'||(state.page==='lesson'&&state.learn==='recognition')?'learn':['stories','reader'].includes(state.page)?'stories':['school','classroom'].includes(state.page)?'school':state.page==='videos'?'videos':state.page==='writing'?'writing':['pet','garden'].includes(state.page)?state.page:null;if(section)url.searchParams.set('section',section);else url.searchParams.delete('section');if(url.href!==location.href)history.replaceState(history.state,'',url.href)}catch{}}
function categoryGameHelp(){const cat=gameCategories.find(c=>c.id===state.gameCategory);if(cat)speak(cat.help)}
function selectGameCategory(cat){if(!gameCategories.some(c=>c.id===cat))return;state.gameCategory=cat;state.gameMenu={category:cat,y:0};appEl.innerHTML=renderGames();const home=$('.game-home');requestAnimationFrame(()=>{if(state.page!=='games'||$('.game-home')!==home)return;const rail=$('.game-category-rail'),active=$('.game-category.active');if(rail&&active)rail.scrollLeft=Math.max(0,active.offsetLeft-(rail.clientWidth-active.clientWidth)/2);scrollTo(0,0);rememberGameMenu()});categoryGameHelp()}
function resetGameState(){stopInteractiveGame();['question','memory','maze','order','snake','bee','rocket','bubbleBath','fruitBasket','colorTrain','shadowMatch','firefly','rhythm'].forEach(k=>state[k]=null);document.querySelector('#gameCelebration')?.remove()}
function openGame(k){resetGameState();state.game=k;go('game');gameHelp()}
function trimGameStack(){const i=state.stack.map(x=>x.page).lastIndexOf('games');if(i>=0)state.stack=state.stack.slice(0,i);else if(state.stack.at(-1)?.page==='create')state.stack.pop()}
function leaveGame(){resetGameState();stopAudio();trimGameStack();state.page='games';render()}
function gameHelp(){const help=gameSets[state.game]?.help;if(help)speak(help)}
function restartCurrentGame(){resetGameState();if(state.game==='princess'){princessReset();return}render();gameHelp()}
function gameShell(body){const g=gameSets[state.game]||{icon:'🎮',title:'小游戏'};return `<div class="mini-game-page"><div class="mini-game-nav"><button class="game-exit" onclick="leaveGame()"><span>🏠</span><b>游戏乐园</b></button><div class="mini-game-name"><span>${g.icon}</span><b>${esc(g.title)}</b></div><div class="mini-game-tools"><button onclick="gameHelp()" aria-label="听玩法">🔊</button><button onclick="restartCurrentGame()" aria-label="重新玩">↻</button></div></div>${body}</div>`}
function creativeGameNav(){const meta={coloring:['🎨','涂颜色'],draw:['🖍️','自由画画'],piano:['🎹','音乐小琴']}[state.page];if(!meta)return'';return `<div class="mini-game-nav creative-game-nav"><button class="game-exit" onclick="leaveCreativeGame()"><span>🏠</span><b>游戏乐园</b></button><div class="mini-game-name"><span>${meta[0]}</span><b>${meta[1]}</b></div><div class="mini-game-tools"><button onclick="creativeGameHelp()" aria-label="听玩法">🔊</button><button onclick="restartCreativeGame()" aria-label="重新玩">↻</button></div></div>`}
function creativeGameHelp(){const studio=state.page==='draw'?window.ART_STUDIO:state.page==='piano'?window.MUSIC_STUDIO:null;if(studio){speak(studio.helpText);return}const help={coloring:'先选一种颜色，再点图画里的小块，就能涂上颜色啦。',draw:'先选一种颜色，再用小手在白纸上画画。也可以点图章，印上小星星。',piano:'轻轻点彩色琴键，听听不同的声音。点播放按钮，还能听小星星。'}[state.page];if(help)speak(help)}
function leaveCreativeGame(){stopInteractiveGame();stopAudio();trimGameStack();state.page='games';render()}
function restartCreativeGame(){if(state.page==='coloring'){state.colorUndo=[];resetColoring();return}if(state.page==='draw'){if(window.ART_STUDIO)window.ART_STUDIO.reset();else clearPad();return}if(state.page==='piano'&&window.MUSIC_STUDIO){window.MUSIC_STUDIO.reset();return}if(state.page==='piano')speak('小琴准备好啦，点一个琴键试试看')}
function newQuestion(){if(state.game==='count'){const n=1+Math.floor(Math.random()*9),opts=[n];while(opts.length<4){let x=1+Math.floor(Math.random()*9);if(!opts.includes(x))opts.push(x)}state.question={prompt:'一共有多少颗星星？',show:'⭐'.repeat(n),right:String(n),opts:opts.sort(()=>Math.random()-.5).map(String)}}else{const all=learnSets.animals.concat(learnSets.fruit);const x=all[Math.floor(Math.random()*all.length)],opts=[x];while(opts.length<4){let y=all[Math.floor(Math.random()*all.length)];if(!opts.includes(y))opts.push(y)}state.question={prompt:state.game==='sound'?'听一听，选出正确的图片':'找到相同的朋友',show:state.game==='sound'?'🔊':x[0],right:x[0],word:x[1],opts:opts.sort(()=>Math.random()-.5).map(y=>y[0])}}return state.question}
function renderGameContent(){if(state.game==='princess')return renderPrincessGame();if(window.NEW_GAMES?.entries.some(g=>g.id===state.game))return window.NEW_GAMES.render(state.game);if(state.game==='memory')return renderMemory();if(state.game==='sort')return renderSort();if(state.game==='pop')return renderPop();if(state.game==='snakeFruit')return renderSnakeFruit();if(state.game==='beeGarden')return renderBeeGarden();if(state.game==='rocketStars')return renderRocketStars();if(state.game==='peppaCount')return renderPeppaCount();if(state.game==='peppaPicnic')return renderPeppaPicnic();if(state.game==='pawMaze')return renderPawMaze();if(state.game==='pawGear')return renderPawGear();if(state.game==='brandMemory')return renderBrandMemory();if(state.game==='storyOrder')return renderStoryOrder();if(state.game==='bubbleBath')return renderBubbleBath();if(state.game==='fruitBasket')return renderFruitBasket();if(state.game==='colorTrain')return renderColorTrain();if(state.game==='shadowMatch')return renderShadowMatch();if(state.game==='fireflyTrail')return renderFireflyTrail();if(state.game==='rhythmTap')return renderRhythmTap();const q=state.question||newQuestion();return `<div class="lesson simple-game"><h2>${gameSets[state.game]?.icon||'🎮'} ${gameSets[state.game]?.title||'小游戏'}</h2><p>${q.prompt}</p><div class="flash" onclick="gamePrompt()"><span class="emoji" style="font-size:${state.game==='count'?'48px':'95px'}">${q.show}</span></div><div class="answer-grid">${q.opts.map(o=>`<button class="answer" onclick="answer(this,'${o}')">${o}</button>`).join('')}</div><div class="message" id="message"></div><button class="wide-btn soft" onclick="state.question=null;render()">换一题</button></div>`}
function renderGame(){return gameShell(renderGameContent())}
function gamePrompt(){const q=state.question;if(state.game==='sound')speak(q.word,'en-US');else speak(q.prompt)}function answer(el,o){document.querySelectorAll('.answer').forEach(b=>b.disabled=true);if(o===state.question.right){el.classList.add('good');$('#message').textContent='答对啦！真棒 ⭐';reward();speak('答对啦，真棒')}else{el.classList.add('bad');$('#message').textContent='没关系，再试一题';speak('没关系，再试一题')}}
function renderMemory(){if(!state.memory){const icons=['🐶','🐱','🐰','🐼','🦊','🐸'];state.memory={cards:[...icons,...icons].sort(()=>Math.random()-.5),open:[],done:[]}}const m=state.memory;return `<div class="lesson"><h2>🧠 记忆翻牌</h2><p>每次翻两张，找出一样的朋友</p><div class="memory-grid">${m.cards.map((x,i)=>`<button class="memory-card ${m.open.includes(i)||m.done.includes(i)?'open':''}" onclick="flipCard(${i})">${m.open.includes(i)||m.done.includes(i)?x:'❓'}</button>`).join('')}</div><div class="message">已经找到 ${m.done.length/2} 对</div><button class="wide-btn" onclick="state.memory=null;render()">重新开始</button></div>`}
function flipCard(i){const m=state.memory;if(m.done.includes(i)||m.open.includes(i)||m.open.length>=2)return;m.open.push(i);render();if(m.open.length===2){const[a,b]=m.open;if(m.cards[a]===m.cards[b])later(()=>{if(state.memory!==m||state.page!=='game')return;m.done.push(a,b);m.open=[];if(m.done.length===m.cards.length){render();finishMiniGame('全部找到了，你的记忆力真棒！')}else render()},500);else later(()=>{if(state.memory!==m||state.page!=='game')return;m.open=[];render()},800)}}
function renderSort(){if(!state.question){const items=[['🍎','水果'],['🍌','水果'],['🐶','动物'],['🐼','动物'],['🚗','交通'],['🚲','交通'],['🥛','食物'],['🍞','食物']];const x=items[Math.floor(Math.random()*items.length)];state.question={show:x[0],right:x[1]}}const q=state.question;return `<div class="lesson"><h2>🧺 物品分类</h2><p>它应该放进哪个篮子？</p><div class="flash"><span class="emoji">${q.show}</span></div><div class="answer-grid">${['水果','动物','交通','食物'].map(x=>`<button class="answer" onclick="sortAnswer(this,'${x}')">${x}</button>`).join('')}</div><div class="message" id="message"></div><button class="wide-btn" onclick="state.question=null;render()">换一个物品</button></div>`}
function sortAnswer(el,x){if(state.question.answered)return;if(x===state.question.right){state.question.answered=true;document.querySelectorAll('.answer').forEach(b=>b.disabled=true);el.classList.add('good');$('#message').textContent='放对篮子啦 ⭐';reward();speak('分类正确，真棒')}else{el.classList.add('bad');$('#message').textContent='再想一想，它是'+state.question.right;speak('再想一想')}}
function renderPop(){if(!state.question){const colors=[['红色','#ff6262'],['黄色','#ffd34e'],['蓝色','#55aaff'],['绿色','#5bca86']],t=colors[Math.floor(Math.random()*colors.length)],items=Array.from({length:16},()=>colors[Math.floor(Math.random()*colors.length)]);if(!items.some(x=>x[0]===t[0]))items[0]=t;state.question={right:t[0],items,found:0,total:items.filter(x=>x[0]===t[0]).length,done:false}}const q=state.question;return `<div class="lesson"><h2>🎈 彩色气球</h2><p>请点所有的 <b style="font-size:24px">${q.right}</b> 气球</p><div class="balloon-grid">${q.items.map(x=>`<button class="balloon" style="background:${x[1]}" onclick="popBalloon(this,'${x[0]}')">🎈</button>`).join('')}</div><div class="message" id="message">还要找到 ${q.total-q.found} 个</div><button class="wide-btn" onclick="state.question=null;render()">换一种颜色</button></div>`}
function popBalloon(el,color){const q=state.question;if(!q||q.done||el.classList.contains('popped'))return;if(color===q.right){el.classList.add('popped');q.found++;tone(523.3,.12);if(q.found>=q.total){q.done=true;$('#message').textContent='全都找到了！';later(()=>finishMiniGame(`${q.right}气球全都找到了！`),300)}else $('#message').textContent=`找到了！还剩 ${q.total-q.found} 个`}else{el.classList.add('shake');later(()=>el.classList.remove('shake'),350);speak('再看清楚颜色')}}
function renderPeppaCount(){if(!state.question){const n=2+Math.floor(Math.random()*7),opts=[n];while(opts.length<4){const x=1+Math.floor(Math.random()*9);if(!opts.includes(x))opts.push(x)}state.question={right:String(n),opts:opts.sort(()=>Math.random()-.5).map(String)}}const q=state.question;return `<div class="lesson peppa-game"><h2>🐷 佩奇泥坑数数</h2><p>佩奇找到了多少个泥坑？</p><div class="puddle-field"><span class="peppa-mini">🐷</span>${'🟤'.repeat(+q.right)}</div><div class="answer-grid">${q.opts.map(x=>`<button class="answer" onclick="brandAnswer(this,'${x}')">${x}</button>`).join('')}</div><div class="message" id="message"></div><button class="wide-btn" onclick="state.question=null;render()">再数一次</button></div>`}
function renderPeppaPicnic(){if(!state.question){const items=[['🍎','带去野餐'],['🥪','带去野餐'],['🥛','带去野餐'],['🧸','带去野餐'],['🛁','留在家里'],['🛏️','留在家里'],['🚪','留在家里'],['🪥','留在家里']],x=items[Math.floor(Math.random()*items.length)];state.question={show:x[0],right:x[1]}}const q=state.question;return `<div class="lesson peppa-game"><h2>🧺 佩奇野餐篮</h2><p>这个东西要不要放进野餐篮？</p><div class="flash"><span class="emoji">${q.show}</span></div><div class="answer-grid"><button class="answer" onclick="brandAnswer(this,'带去野餐')">🧺 带去野餐</button><button class="answer" onclick="brandAnswer(this,'留在家里')">🏠 留在家里</button></div><div class="message" id="message"></div><button class="wide-btn" onclick="state.question=null;render()">下一个东西</button></div>`}
function brandAnswer(el,value){document.querySelectorAll('.answer').forEach(b=>b.disabled=true);if(value===state.question.right){el.classList.add('good');$('#message').textContent='答对啦！真棒 ⭐';reward();speak('答对啦，真棒')}else{el.classList.add('bad');$('#message').textContent='再想一想';speak('再想一想')}}
function renderPawGear(){if(!state.question){const tasks=[['🔥','哪里着火了，谁来帮忙？','毛毛'],['🚓','需要维持秩序，谁来帮忙？','阿奇'],['🌊','水上有人需要帮助，谁来？','路马'],['🚁','高处需要空中救援，谁来？','天天']];const q=tasks[Math.floor(Math.random()*tasks.length)];state.question={show:q[0],prompt:q[1],right:q[2]}}const q=state.question;return `<div class="lesson paw-game"><h2>🎒 汪汪队装备配对</h2><p>${q.prompt}</p><div class="flash"><span class="emoji">${q.show}</span></div><div class="answer-grid">${[['毛毛','🚒'],['阿奇','🚓'],['路马','🚤'],['天天','🚁']].map(x=>`<button class="answer" onclick="brandAnswer(this,'${x[0]}')">${x[1]} ${x[0]}</button>`).join('')}</div><div class="message" id="message"></div><button class="wide-btn" onclick="state.question=null;render()">下一个任务</button></div>`}
function renderPawMaze(){if(!state.maze)state.maze={route:Math.floor(Math.random()*swipeMazePaths.length),step:0,done:false,started:false};const m=state.maze,path=swipeMazePaths[m.route];return `<div class="lesson paw-game gesture-lesson"><div class="game-title-row"><div><h2>🐾 手指救援迷宫</h2><p>手指按住阿奇，沿着浅色小路滑到小猫身边</p></div><button class="voice-help" onclick="speak('按住阿奇，沿着浅色小路滑到小猫身边')">🔊 听玩法</button></div><div class="swipe-maze ${m.started?'started':''}" id="swipeMaze">${Array.from({length:49},(_,i)=>{const p=path.indexOf(i),walk=p>=0,passed=walk&&p<=m.step;return `<div data-cell="${i}" class="swipe-maze-cell ${walk?'road':'wall'} ${passed?'passed':''} ${i===48?'goal':''}">${i===path[m.step]?'🐶':i===48?'🐱':walk&&p<m.step?'•':' '}</div>`}).join('')}<span class="maze-hand" aria-hidden="true">☝️</span></div><div class="gesture-tip">手指不松开，也可以慢慢转弯</div><div class="message" id="message">从阿奇身上开始滑</div><button class="wide-btn" onclick="state.maze=null;render()">换一条路，再玩一次</button></div>`}
function mazeMove(){return false}
function initPawMaze(){const board=$('#swipeMaze');if(!board)return;let pointerId=null,last=null;const path=swipeMazePaths[state.maze.route];const cellAtPoint=(x,y)=>{const r=board.getBoundingClientRect(),px=Math.max(0,Math.min(r.width-1,x-r.left)),py=Math.max(0,Math.min(r.height-1,y-r.top));return Math.floor(py/(r.height/7))*7+Math.floor(px/(r.width/7))};const paint=()=>{const m=state.maze;board.classList.toggle('started',m.started);board.querySelectorAll('[data-cell]').forEach(el=>{const idx=+el.dataset.cell,p=path.indexOf(idx);el.classList.toggle('passed',p>=0&&p<=m.step);el.textContent=idx===path[m.step]?'🐶':idx===48?'🐱':p>=0&&p<m.step?'•':' '})};const visit=idx=>{const m=state.maze,p=path.indexOf(idx);if(m.done)return;if(p<0){navigator.vibrate?.(16);$('#message').textContent='草地走不通，回到浅色小路吧';return}if(p>m.step&&p<=m.step+4)m.step=p;else if(p<m.step&&p>=m.step-2)m.step=p;else return;paint();if(m.step===path.length-1){m.done=true;pointerId=null;$('#message').textContent='救援成功啦！';finishMiniGame('找到小猫啦，救援成功！')}};const visitLine=e=>{if(!last){last=[e.clientX,e.clientY];visit(cellAtPoint(e.clientX,e.clientY));return}const r=board.getBoundingClientRect(),step=Math.max(4,Math.min(r.width,r.height)/18),dist=Math.hypot(e.clientX-last[0],e.clientY-last[1]),count=Math.max(1,Math.ceil(dist/step));for(let i=1;i<=count;i++)visit(cellAtPoint(last[0]+(e.clientX-last[0])*i/count,last[1]+(e.clientY-last[1])*i/count));last=[e.clientX,e.clientY]};board.onpointerdown=e=>{if(e.isPrimary===false||state.maze.done)return;const idx=cellAtPoint(e.clientX,e.clientY),current=path[state.maze.step];if(idx!==current){$('#message').textContent='请从阿奇现在的位置开始';return}e.preventDefault();pointerId=e.pointerId;last=[e.clientX,e.clientY];state.maze.started=true;board.setPointerCapture?.(e.pointerId);paint();$('#message').textContent='沿着浅色小路继续滑'};board.onpointermove=e=>{if(e.pointerId!==pointerId)return;e.preventDefault();visitLine(e)};board.onpointerup=board.onpointercancel=e=>{if(e.pointerId!==pointerId)return;board.releasePointerCapture?.(e.pointerId);pointerId=null;last=null;if(!state.maze.done)$('#message').textContent='很好，从阿奇这里继续滑'}}


function snakeNewFruit(s){let x,y;do{x=10+Math.random()*80;y=12+Math.random()*76}while(Math.hypot(x-s.x,y-s.y)<28);return{x,y}}
function renderSnakeFruit(){if(!state.snake){const s={x:50,y:72,vx:0,vy:0,score:0,fruit:null,done:false,started:false,trail:Array.from({length:6},(_,i)=>({x:50,y:72+i*1.5}))};s.fruit=snakeNewFruit(s);state.snake=s}const s=state.snake;return `<div class="lesson snake-game gesture-lesson"><div class="game-title-row"><div><h2>🐛 滑动小虫吃水果</h2><p>在草地上滑一下，小虫就会朝那个方向一直跑</p></div><button class="voice-help" onclick="speak('在草地上滑一下，小虫就会朝那个方向一直跑')">🔊 听玩法</button></div><div class="snake-score">🍎 已吃到 <b id="snakeScore">${s.score}</b> / 5</div><div class="bug-field ${s.started?'started':''}" id="snakeBoard"><span class="bug-sun">☀️</span><span class="bug-leaf leaf-one">🌿</span><span class="bug-leaf leaf-two">🍃</span><span class="bug-fruit" id="bugFruit" style="left:${s.fruit.x}%;top:${s.fruit.y}%">🍎</span>${s.trail.map((p,i)=>`<i class="bug-tail" data-tail="${i}" style="left:${p.x}%;top:${p.y}%;opacity:${.18+i*.11}"></i>`).join('')}<span class="bug-player" id="bugPlayer" style="left:${s.x}%;top:${s.y}%">🐛</span><span class="swipe-hand" aria-hidden="true">👆</span></div><div class="gesture-tip">上下左右或斜着滑都可以 · 不会撞死</div><div class="message" id="message">在草地上滑一下，帮助小虫出发</div><button class="wide-btn" onclick="resetSnakeFruit()">重新开始</button></div>`}
function initSnakeFruit(){const field=$('#snakeBoard'),bug=$('#bugPlayer'),fruit=$('#bugFruit'),s=state.snake;if(!field||!bug||!fruit||!s)return;let pointer=null;const aim=(dx,dy)=>{const d=Math.hypot(dx,dy);if(d<5||s.done)return;s.vx=dx/d;s.vy=dy/d;s.started=true;field.classList.add('started');$('#message').textContent='继续滑动，小虫就会转弯'};const collect=()=>{if(Math.hypot(s.x-s.fruit.x,s.y-s.fruit.y)>9||s.done)return;s.score++;$('#snakeScore').textContent=s.score;navigator.vibrate?.(22);tone(523+s.score*35,.12);if(s.score>=5){s.done=true;fruit.classList.add('picked');stopInteractiveGame();$('#message').textContent='五个苹果都找到啦！';finishMiniGame('五个苹果都找到了，真棒！');return}s.fruit=snakeNewFruit(s);fruit.style.left=s.fruit.x+'%';fruit.style.top=s.fruit.y+'%';fruit.animate?.([{transform:'translate(-50%,-50%) scale(.35)'},{transform:'translate(-50%,-50%) scale(1.15)'},{transform:'translate(-50%,-50%) scale(1)'}],{duration:260});$('#message').textContent=`吃到苹果啦，还剩 ${5-s.score} 个`};const tick=()=>{if(!s.started||s.done)return;s.trail.push({x:s.x,y:s.y});while(s.trail.length>6)s.trail.shift();s.x+=s.vx*.82;s.y+=s.vy*.82;if(s.x<3)s.x=97;if(s.x>97)s.x=3;if(s.y<4)s.y=96;if(s.y>96)s.y=4;bug.style.left=s.x+'%';bug.style.top=s.y+'%';field.querySelectorAll('[data-tail]').forEach((el,i)=>{const p=s.trail[i]||s;el.style.left=p.x+'%';el.style.top=p.y+'%'});collect()};field.onpointerdown=e=>{if(e.isPrimary===false||s.done)return;e.preventDefault();pointer={id:e.pointerId,x:e.clientX,y:e.clientY};field.setPointerCapture?.(e.pointerId)};field.onpointermove=e=>{if(!pointer||e.pointerId!==pointer.id||s.done)return;e.preventDefault();const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;if(Math.hypot(dx,dy)>7){aim(dx,dy);pointer.x=e.clientX;pointer.y=e.clientY}};field.onpointerup=field.onpointercancel=e=>{if(!pointer||e.pointerId!==pointer.id)return;aim(e.clientX-pointer.x,e.clientY-pointer.y);field.releasePointerCapture?.(e.pointerId);pointer=null};state.gameTimer=setInterval(tick,45)}

function resetSnakeFruit(){stopInteractiveGame();state.snake=null;render()}

function renderBeeGarden(){if(!state.bee)state.bee={x:50,y:50,collected:[],done:false};const b=state.bee;return `<div class="lesson bee-game gesture-lesson"><div class="game-title-row"><div><h2>🐝 小蜜蜂采花</h2><p>按住小蜜蜂，在花园里滑动，把六朵花都找到</p></div><button class="voice-help" onclick="speak('按住小蜜蜂，在花园里滑动，把六朵花都找到')">🔊 听玩法</button></div><div class="bee-score">🌸 已采到 <b id="beeScore">${b.collected.length}</b> / ${beeFlowers.length}</div><div class="bee-field" id="beeField"><div class="garden-cloud">☁️</div>${beeFlowers.map((p,i)=>`<span data-flower="${i}" class="garden-flower ${b.collected.includes(i)?'picked':''}" style="left:${p[0]}%;top:${p[1]}%">🌸</span>`).join('')}<span class="bee-player" id="beePlayer" style="left:${b.x}%;top:${b.y}%">🐝</span></div><div class="gesture-tip">手指不松开，可以在花园里转来转去</div><div class="message" id="message">按住小蜜蜂开始采花</div><button class="wide-btn" onclick="state.bee=null;render()">重新采花</button></div>`}
function initBeeGarden(){const field=$('#beeField'),bee=$('#beePlayer'),b=state.bee;if(!field||!bee||!b)return;let pointerId=null,last=null;const moveTo=(x,y)=>{b.x=Math.max(5,Math.min(95,x));b.y=Math.max(5,Math.min(95,y));bee.style.left=b.x+'%';bee.style.top=b.y+'%';beeFlowers.forEach((p,i)=>{if(b.collected.includes(i)||Math.hypot(b.x-p[0],b.y-p[1])>10)return;b.collected.push(i);field.querySelector(`[data-flower="${i}"]`)?.classList.add('picked');$('#beeScore').textContent=b.collected.length;tone(600+i*45,.1)});if(b.collected.length===beeFlowers.length&&!b.done){b.done=true;pointerId=null;$('#message').textContent='六朵花都采到啦！';finishMiniGame('六朵花都采到了，真棒！')}else if(!b.done)$('#message').textContent=`还剩 ${beeFlowers.length-b.collected.length} 朵花`};const move=e=>{const r=field.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*100,y=(e.clientY-r.top)/r.height*100;if(last){const count=Math.max(1,Math.ceil(Math.hypot(x-last[0],y-last[1])/3));for(let i=1;i<=count;i++)moveTo(last[0]+(x-last[0])*i/count,last[1]+(y-last[1])*i/count)}else moveTo(x,y);last=[x,y]};field.onpointerdown=e=>{if(e.isPrimary===false||b.done)return;e.preventDefault();pointerId=e.pointerId;last=null;field.setPointerCapture?.(e.pointerId);move(e)};field.onpointermove=e=>{if(e.pointerId!==pointerId)return;e.preventDefault();move(e)};field.onpointerup=field.onpointercancel=e=>{if(e.pointerId!==pointerId)return;pointerId=null;last=null;field.releasePointerCapture?.(e.pointerId)}}


function renderRocketStars(){if(!state.rocket)state.rocket={x:50,y:82,collected:[],done:false};const r=state.rocket;return `<div class="lesson rocket-game gesture-lesson"><div class="game-title-row"><div><h2>🚀 滑动火箭收星星</h2><p>按住火箭，在太空里自由滑动，把星星都收起来</p></div><button class="voice-help" onclick="speak('按住火箭，在太空里自由滑动，把星星都收起来')">🔊 听玩法</button></div><div class="rocket-score">⭐ 已收集 <b id="rocketScore">${r.collected.length}</b> / ${rocketStarPoints.length}</div><div class="rocket-field" id="rocketField">${rocketStarPoints.map((p,i)=>`<span data-star="${i}" class="space-star ${r.collected.includes(i)?'picked':''}" style="left:${p[0]}%;top:${p[1]}%">⭐</span>`).join('')}<span class="space-planet">🪐</span><span class="rocket-player" id="rocketPlayer" style="left:${r.x}%;top:${r.y}%">🚀</span></div><div class="gesture-tip">手指可以一直按着，转来转去</div><div class="message" id="message">按住火箭开始飞</div><button class="wide-btn" onclick="state.rocket=null;render()">重新出发</button></div>`}
function initRocketStars(){const field=$('#rocketField'),rocket=$('#rocketPlayer'),r=state.rocket;if(!field||!rocket||!r)return;let pointerId=null,last=null;const moveTo=(x,y)=>{r.x=Math.max(5,Math.min(95,x));r.y=Math.max(5,Math.min(95,y));rocket.style.left=r.x+'%';rocket.style.top=r.y+'%';rocketStarPoints.forEach((p,i)=>{if(r.collected.includes(i)||Math.hypot(r.x-p[0],r.y-p[1])>10)return;r.collected.push(i);field.querySelector(`[data-star="${i}"]`)?.classList.add('picked');$('#rocketScore').textContent=r.collected.length;navigator.vibrate?.(18);tone(620+i*32,.1)});if(r.collected.length===rocketStarPoints.length&&!r.done){r.done=true;pointerId=null;$('#message').textContent='星星全部收好啦！';finishMiniGame('星星全部收好了，太棒了！')}else if(!r.done)$('#message').textContent=`还剩 ${rocketStarPoints.length-r.collected.length} 颗星星`};const move=e=>{const box=field.getBoundingClientRect(),x=(e.clientX-box.left)/box.width*100,y=(e.clientY-box.top)/box.height*100;if(last){const count=Math.max(1,Math.ceil(Math.hypot(x-last[0],y-last[1])/3));for(let i=1;i<=count;i++)moveTo(last[0]+(x-last[0])*i/count,last[1]+(y-last[1])*i/count)}else moveTo(x,y);last=[x,y]};field.onpointerdown=e=>{if(e.isPrimary===false||r.done)return;e.preventDefault();pointerId=e.pointerId;last=null;field.setPointerCapture?.(e.pointerId);move(e)};field.onpointermove=e=>{if(e.pointerId!==pointerId)return;e.preventDefault();move(e)};field.onpointerup=field.onpointercancel=e=>{if(e.pointerId!==pointerId)return;pointerId=null;last=null;field.releasePointerCapture?.(e.pointerId)}}


function finishMiniGame(message='完成啦！你真棒！'){if($('#gameCelebration'))return;reward();navigator.vibrate?.([25,35,45]);tone(659,.16);later(()=>tone(784,.22),150);speak(message);document.body.insertAdjacentHTML('beforeend',`<div class="game-celebration" id="gameCelebration" role="dialog" aria-modal="true"><div><span>🌟</span><h2>完成啦！</h2><p>${esc(message)}</p><button class="celebrate-again" onclick="restartCurrentGame()">↻ 再玩一次</button><button class="celebrate-home" onclick="leaveGame()">🏠 换个游戏</button></div></div>`)}
function renderBubbleBath(){if(!state.bubbleBath)state.bubbleBath={popped:[],done:false};const b=state.bubbleBath,total=15;return `<div class="lesson bubble-bath-game"><h2>🫧 泡泡洗澡</h2><p>点破所有泡泡，帮小鸭洗香香</p><div class="bath-score">🫧 还剩 <b id="bathLeft">${total-b.popped.length}</b> 个</div><div class="bubble-bath-board"><span class="bath-duck">🦆</span>${Array.from({length:total},(_,i)=>`<button class="bath-bubble b${i} ${b.popped.includes(i)?'popped':''}" onclick="popBathBubble(${i},this)" aria-label="泡泡">${i%4===0?'✨':' '}</button>`).join('')}</div><div class="message" id="message">小手点一点，泡泡啵啵啵</div></div>`}
function popBathBubble(i,el){const b=state.bubbleBath;if(!b||b.done||b.popped.includes(i))return;b.popped.push(i);el.classList.add('popped');$('#bathLeft').textContent=15-b.popped.length;tone(520+(i%5)*55,.1);navigator.vibrate?.(10);if(b.popped.length===15){b.done=true;$('#message').textContent='小鸭洗干净啦！';later(()=>finishMiniGame('泡泡都洗干净啦，你的小手真灵活！'),320)}else $('#message').textContent=`啵！还剩 ${15-b.popped.length} 个泡泡`}
function makeFruitBasket(){const items=[['🍎','fruit'],['🍌','fruit'],['🍓','fruit'],['🧸','toy'],['⚽','toy'],['🪀','toy']].map(x=>({icon:x[0],kind:x[1]})).sort(()=>Math.random()-.5);return{items,index:0,score:0,done:false}}
function renderFruitBasket(){if(!state.fruitBasket)state.fruitBasket=makeFruitBasket();const g=state.fruitBasket,item=g.items[g.index];return `<div class="lesson sorting-drag-game fruit-basket-game"><h2>🍎 水果回家</h2><p>按住中间的东西，把它送回自己的家</p><div class="drag-progress">已经送回家 <b>${g.score}</b> / ${g.items.length}</div><div class="drag-sort-board" id="fruitSortBoard"><button class="sort-home fruit-home" data-basket="fruit" onclick="fruitBasketDrop('fruit')"><span>🧺</span><b>果篮</b></button><div class="drag-item" id="fruitDragItem" role="button" aria-label="拖动${item?.icon||''}">${item?.icon||'⭐'}<i>☝️</i></div><button class="sort-home toy-home" data-basket="toy" onclick="fruitBasketDrop('toy')"><span>🧸</span><b>玩具箱</b></button></div><div class="message" id="message">${item?.kind==='fruit'?'这是水果，送到果篮吧':'这是玩具，送到玩具箱吧'}</div></div>`}
function fruitBasketDrop(kind){const g=state.fruitBasket,item=g?.items[g.index];if(!item||g.done)return;if(kind!==item.kind){$('#message').textContent='这个家不对哦，换另一边试试';speak('换另一边试试');document.querySelector(`[data-basket="${kind}"]`)?.classList.add('nope');later(()=>document.querySelector(`[data-basket="${kind}"]`)?.classList.remove('nope'),350);return}g.index++;g.score++;tone(650,.12);if(g.index>=g.items.length){g.done=true;$('#fruitDragItem')?.classList.add('sent-home');$('#message').textContent='每样东西都回家啦！';later(()=>finishMiniGame('水果和玩具都回到自己的家啦！'),280)}else render()}
function initFruitBasket(){const item=$('#fruitDragItem');if(!item||state.fruitBasket?.done)return;let drag=null;item.onpointerdown=e=>{if(e.isPrimary===false)return;e.preventDefault();drag={id:e.pointerId,x:e.clientX,y:e.clientY};item.setPointerCapture?.(e.pointerId);item.classList.add('dragging')};item.onpointermove=e=>{if(!drag||e.pointerId!==drag.id)return;e.preventDefault();item.style.transform=`translate(calc(-50% + ${e.clientX-drag.x}px),calc(-50% + ${e.clientY-drag.y}px)) scale(1.08)`};item.onpointerup=item.onpointercancel=e=>{if(!drag||e.pointerId!==drag.id)return;item.releasePointerCapture?.(e.pointerId);item.style.pointerEvents='none';const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-basket]');item.style.pointerEvents='';item.classList.remove('dragging');item.style.transform='';drag=null;if(target)fruitBasketDrop(target.dataset.basket);else $('#message').textContent='拖到左边或右边的大篮子里'}}
function makeColorTrain(){const colors=[['red','红色','#ff716b','🐰'],['yellow','黄色','#f5c84c','🐥'],['blue','蓝色','#55a9e8','🐘']];return{colors,round:0,total:5,current:colors[Math.floor(Math.random()*colors.length)],done:false}}
function renderColorTrain(){if(!state.colorTrain)state.colorTrain=makeColorTrain();const g=state.colorTrain,c=g.current;return `<div class="lesson color-train-game"><h2>🚂 彩虹小火车</h2><p>把彩色乘客送上同样颜色的车厢</p><div class="drag-progress">送上火车 <b>${g.round}</b> / ${g.total}</div><div class="train-sky" id="trainBoard"><div class="train-passenger" id="trainPassenger" style="--passenger:${c[2]}" role="button" aria-label="拖动${c[1]}乘客"><span>${c[3]}</span><i>☝️</i></div><div class="train-track">${g.colors.map((x,i)=>`<button class="train-car" data-train-color="${x[0]}" style="--car:${x[2]}" onclick="colorTrainDrop('${x[0]}')"><span>${i===0?'●':i===1?'▲':'■'}</span><b>${x[1]}</b></button>`).join('')}</div></div><div class="message" id="message">把${c[1]}乘客拖到${c[1]}车厢</div></div>`}
function colorTrainDrop(color){const g=state.colorTrain;if(!g||g.done)return;if(color!==g.current[0]){$('#message').textContent='颜色不一样，再找一找';speak('再找找一样的颜色');document.querySelector(`[data-train-color="${color}"]`)?.classList.add('nope');later(()=>document.querySelector(`[data-train-color="${color}"]`)?.classList.remove('nope'),350);return}g.round++;tone(700,.13);if(g.round>=g.total){g.done=true;$('#trainPassenger')?.classList.add('aboard');$('#message').textContent='乘客都上车啦！';later(()=>finishMiniGame('彩色乘客都坐上正确的车厢啦！'),280);return}g.current=g.colors[Math.floor(Math.random()*g.colors.length)];render()}
function initColorTrain(){const item=$('#trainPassenger');if(!item||state.colorTrain?.done)return;let drag=null;item.onpointerdown=e=>{if(e.isPrimary===false)return;e.preventDefault();drag={id:e.pointerId,x:e.clientX,y:e.clientY};item.setPointerCapture?.(e.pointerId);item.classList.add('dragging')};item.onpointermove=e=>{if(!drag||e.pointerId!==drag.id)return;e.preventDefault();item.style.transform=`translate(calc(-50% + ${e.clientX-drag.x}px),calc(-50% + ${e.clientY-drag.y}px)) scale(1.08)`};item.onpointerup=item.onpointercancel=e=>{if(!drag||e.pointerId!==drag.id)return;item.releasePointerCapture?.(e.pointerId);item.style.pointerEvents='none';const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-train-color]');item.style.pointerEvents='';item.style.transform='';item.classList.remove('dragging');drag=null;if(target)colorTrainDrop(target.dataset.trainColor);else $('#message').textContent='把乘客拖到下面的彩色车厢'}}
function makeShadowQuestion(round=0){const all=[['🐰','小兔'],['🐘','大象'],['🦒','长颈鹿'],['🐟','小鱼'],['🦋','蝴蝶'],['🚗','小汽车'],['✈️','飞机'],['🌳','大树']],right=all[Math.floor(Math.random()*all.length)],opts=[right];while(opts.length<3){const x=all[Math.floor(Math.random()*all.length)];if(!opts.includes(x))opts.push(x)}return{round,right,opts:opts.sort(()=>Math.random()-.5),answered:false}}
function renderShadowMatch(){if(!state.shadowMatch)state.shadowMatch=makeShadowQuestion();const g=state.shadowMatch;return `<div class="lesson shadow-game"><h2>🔦 影子好朋友</h2><p>仔细看看，这是谁的影子？</p><div class="shadow-stage"><span>${g.right[0]}</span><i>🔦</i></div><div class="shadow-options">${g.opts.map(x=>`<button onclick="shadowAnswer(this,'${x[0]}')"><span>${x[0]}</span><b>${x[1]}</b></button>`).join('')}</div><div class="message" id="message">找到和影子一样的图案</div><div class="round-dots">${Array.from({length:5},(_,i)=>`<i class="${i<g.round?'done':''}"></i>`).join('')}</div></div>`}
function shadowAnswer(el,value){const g=state.shadowMatch;if(!g||g.answered)return;if(value!==g.right[0]){el.classList.add('bad');$('#message').textContent='轮廓不一样，再看一看';speak('再仔细看一看');later(()=>el.classList.remove('bad'),420);return}g.answered=true;el.classList.add('good');g.round++;tone(680,.13);if(g.round>=5){$('#message').textContent='五个影子都找到啦！';later(()=>finishMiniGame('五个影子都找到好朋友啦！'),320)}else{ $('#message').textContent='找对啦！下一个影子';later(()=>{state.shadowMatch=makeShadowQuestion(g.round);render()},520)}}
function renderFireflyTrail(){if(!state.firefly)state.firefly={index:0,x:fireflyPoints[0][0],y:fireflyPoints[0][1],done:false,started:false};const g=state.firefly;return `<div class="lesson firefly-game gesture-lesson"><h2>✨ 萤火虫亮灯</h2><p>按住小萤火虫，沿着发亮的圆点一直滑</p><div class="firefly-score">点亮 <b id="fireflyScore">${g.index}</b> / ${fireflyPoints.length}</div><div class="firefly-field" id="fireflyField">${fireflyPoints.map((p,i)=>`<i class="firefly-light ${i<g.index?'lit':''} ${i===g.index?'next':''}" data-light="${i}" style="left:${p[0]}%;top:${p[1]}%">${i<g.index?'★':'•'}</i>`).join('')}<span class="firefly-player" id="fireflyPlayer" style="left:${g.x}%;top:${g.y}%">✨</span><span class="firefly-hand">☝️</span></div><div class="message" id="message">从发亮的第一个圆点开始</div></div>`}
function initFireflyTrail(){const field=$('#fireflyField'),player=$('#fireflyPlayer'),g=state.firefly;if(!field||!player||!g||g.done)return;let drag=null,last=null;const visit=(x,y)=>{g.x=Math.max(3,Math.min(97,x));g.y=Math.max(3,Math.min(97,y));player.style.left=g.x+'%';player.style.top=g.y+'%';const target=fireflyPoints[g.index];if(!target||Math.hypot(g.x-target[0],g.y-target[1])>10)return;field.querySelector(`[data-light="${g.index}"]`)?.classList.remove('next');field.querySelector(`[data-light="${g.index}"]`)?.classList.add('lit');g.index++;$('#fireflyScore').textContent=g.index;tone(560+g.index*35,.1);navigator.vibrate?.(12);field.querySelector(`[data-light="${g.index}"]`)?.classList.add('next');if(g.index>=fireflyPoints.length){g.done=true;$('#message').textContent='夜空全都亮起来啦！';later(()=>finishMiniGame('萤火虫把整条星光小路都点亮啦！'),260)}else $('#message').textContent=`真亮！还差 ${fireflyPoints.length-g.index} 盏小灯`};const move=e=>{const r=field.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*100,y=(e.clientY-r.top)/r.height*100;if(last){const steps=Math.max(1,Math.ceil(Math.hypot(x-last[0],y-last[1])/3));for(let i=1;i<=steps;i++)visit(last[0]+(x-last[0])*i/steps,last[1]+(y-last[1])*i/steps)}else visit(x,y);last=[x,y]};field.onpointerdown=e=>{if(e.isPrimary===false||g.done)return;e.preventDefault();drag=e.pointerId;last=null;g.started=true;field.classList.add('started');field.setPointerCapture?.(e.pointerId);move(e)};field.onpointermove=e=>{if(e.pointerId!==drag)return;e.preventDefault();move(e)};field.onpointerup=field.onpointercancel=e=>{if(e.pointerId!==drag)return;field.releasePointerCapture?.(e.pointerId);drag=null;last=null;if(!g.done)$('#message').textContent='很好，从小萤火虫这里继续滑'}}
function makeRhythm(){return{sequence:[Math.floor(Math.random()*4),Math.floor(Math.random()*4)],input:[],round:1,playing:false,started:false,done:false}}
function renderRhythmTap(){if(!state.rhythm)state.rhythm=makeRhythm();const g=state.rhythm,pads=[['🐸','#5fc882'],['🦊','#ef9362'],['🐼','#7399d8'],['🐰','#d786c0']];return `<div class="lesson rhythm-game"><h2>🥁 森林节奏</h2><p>先看小动物亮起来，再照着顺序点</p><div class="rhythm-round">第 <b id="rhythmRound">${g.round}</b> / 3 轮</div><div class="rhythm-pads">${pads.map((p,i)=>`<button data-rhythm="${i}" style="--pad:${p[1]}" onclick="tapRhythm(${i})"><span>${p[0]}</span></button>`).join('')}</div><button class="rhythm-start ${g.started?'hidden':''}" id="rhythmStart" onclick="startRhythm()">▶ 看节奏</button><div class="message" id="message">点开始，先用小眼睛看</div></div>`}
function lightRhythmPad(i){const el=document.querySelector(`[data-rhythm="${i}"]`);if(!el)return;el.classList.add('lit');tone([392,494,587,698][i],.22);later(()=>el.classList.remove('lit'),300)}
function playRhythmSequence(){const g=state.rhythm;if(!g||g.done)return;g.playing=true;g.input=[];document.querySelectorAll('[data-rhythm]').forEach(x=>x.disabled=true);$('#message').textContent='小眼睛看，小耳朵听';g.sequence.forEach((n,i)=>later(()=>lightRhythmPad(n),300+i*620));later(()=>{if(!state.rhythm)return;g.playing=false;document.querySelectorAll('[data-rhythm]').forEach(x=>x.disabled=false);$('#message').textContent='轮到你啦，照着点一遍'},420+g.sequence.length*620)}
function startRhythm(){const g=state.rhythm;if(!g||g.playing)return;g.started=true;$('#rhythmStart')?.classList.add('hidden');playRhythmSequence()}
function tapRhythm(i){const g=state.rhythm;if(!g||g.done||g.playing||!g.started)return;lightRhythmPad(i);const expected=g.sequence[g.input.length];if(i!==expected){g.input=[];$('#message').textContent='没关系，再看一遍';speak('没关系，再看一遍');g.playing=true;later(()=>playRhythmSequence(),650);return}g.input.push(i);if(g.input.length<g.sequence.length){$('#message').textContent='对啦，继续点下一个';return}if(g.round>=3){g.done=true;$('#message').textContent='三轮节奏全对啦！';later(()=>finishMiniGame('三轮节奏都记住啦，你是节奏小高手！'),350);return}g.round++;g.sequence.push(Math.floor(Math.random()*4));g.input=[];$('#rhythmRound').textContent=g.round;$('#message').textContent='太棒啦，下一轮会多一个声音';g.playing=true;later(()=>playRhythmSequence(),780)}
function later(fn,ms){state.gameTimeouts=state.gameTimeouts||[];const id=setTimeout(()=>{state.gameTimeouts=(state.gameTimeouts||[]).filter(x=>x!==id);fn()},ms);state.gameTimeouts.push(id);return id}
function stopInteractiveGame(){window.ART_STUDIO?.stop();window.MUSIC_STUDIO?.stop();window.WRITING?.stop();window.NEW_GAMES?.stop();if(state.gameTimer){clearInterval(state.gameTimer);state.gameTimer=null}(state.gameTimeouts||[]).forEach(clearTimeout);state.gameTimeouts=[]}
function renderBrandMemory(){if(!state.memory){const icons=['🐷','🦖','🚒','🚓','🚁','🚤'];state.memory={cards:[...icons,...icons].sort(()=>Math.random()-.5),open:[],done:[]}}const m=state.memory;return `<div class="lesson brand-memory"><h2>💛 角色记忆翻牌</h2><p>找出佩奇和汪汪队的相同伙伴</p><div class="memory-grid">${m.cards.map((x,i)=>`<button class="memory-card ${m.open.includes(i)||m.done.includes(i)?'open':''}" onclick="flipCard(${i})">${m.open.includes(i)||m.done.includes(i)?x:'⭐'}</button>`).join('')}</div><div class="message">已经找到 ${m.done.length/2} 对</div><button class="wide-btn" onclick="state.memory=null;render()">重新开始</button></div>`}
function renderStoryOrder(){if(!state.order){const sets=[[['🥾','穿好雨靴'],['🐷','跳泥坑'],['🛁','回家洗澡']],[['🔔','收到警报'],['🚒','出发救援'],['🐱','救出小猫']]],steps=[...sets[Math.floor(Math.random()*sets.length)].map((x,i)=>({icon:x[0],text:x[1],order:i}))].sort(()=>Math.random()-.5);state.order={steps,picked:[]}}const o=state.order;return `<div class="lesson"><h2>🔢 故事顺序</h2><p>按事情发生的顺序点卡片</p><div class="story-order">${o.steps.map(x=>`<button class="order-card ${o.picked.includes(x.order)?'picked':''}" onclick="orderPick(this,${x.order})"><span>${x.icon}</span><b>${x.text}</b></button>`).join('')}</div><div class="message" id="message">先点第 1 步</div><button class="wide-btn" onclick="state.order=null;render()">换一个故事</button></div>`}
function orderPick(el,n){const o=state.order;if(o.picked.includes(n))return;if(n===o.picked.length){o.picked.push(n);el.classList.add('picked');if(o.picked.length===3){reward();$('#message').textContent='顺序全对啦 ⭐';speak('故事顺序全对啦')}else $('#message').textContent='再点第 '+(o.picked.length+1)+' 步'}else{el.classList.add('shake');setTimeout(()=>el.classList.remove('shake'),350);speak('想一想，哪件事先发生')}}
const courseUnitIcons={
  '入学准备':'🎒','识字':'🌱','汉语拼音':'🎵','拼音运用':'🚂','阅读表达':'📖','表达练习':'💬','复习':'🌟',
  '准备课':'🔢','位置':'🧭','5以内的数':'🖐️','5以内加减法':'🍎','6—10的数':'🔟','6—10加减法':'🚂',
  '11—20的数':'🧮','20以内计算':'🧱','20以内进位加法':'👐','认识图形':'🧊','分类整理':'🧺','解决问题':'💡','数学乐园':'🎨','复习与关联':'🏆'
};
function unitIcon(unit){return courseUnitIcons[unit]||'⭐'}
function courseSpeech(c,step){if(step===0)return `果粒橙小朋友，我们今天来学${c.title}。${c.intro}`;if(step===1)return `看一看，跟着老师一起想。${c.demo}`;return `轮到你啦。${c.question}选项一，${c.choices[0]}。选项二，${c.choices[1]}。选项三，${c.choices[2]}。`}
function playClassroomText(text,onend=null){const run=++voiceRun;const start=()=>{if(run!==voiceRun)return;if(state.muted){onend?.();return}const src=window.VOICE_MAP?.[voiceKey(text,'zh-CN')];if(!src){console.warn('课堂固定配音缺失',text);onend?.();return}let settled=false;const finish=()=>{if(run!==voiceRun||settled)return;settled=true;onend?.()},failed=()=>{if(run!==voiceRun||settled)return;console.warn('课堂配音加载失败',src);player.removeAttribute('src');finish()};player.onended=finish;player.onerror=failed;player.src=src;player.play().catch(failed)};if(!state.muted&&window.ensureVoiceCatalogue&&!window.VOICE_CATALOGUE_READY){window.ensureVoiceCatalogue().then(start,()=>{if(run===voiceRun)onend?.()});return}start()}
function renderSchool(){
  const all=window.GRADE_ONE_COURSES||[],subject=state.subject||'语文',items=all.filter(x=>x.subject===subject),units=[...new Set(items.map(x=>x.unit))],done=completedCourses(),doneCount=items.filter(x=>done.includes(courseKey(x))).length,percent=Math.round(doneCount/items.length*100),activeUnit=units.includes(state.courseUnit)?state.courseUnit:units[0],unitItems=items.filter(x=>x.unit===activeUnit),next=items.find(x=>!done.includes(courseKey(x)))||items[0],theme=subject==='语文'?'chinese':'math';
  state.courseUnit=activeUnit;
  return `<div class="school-page school-${theme}">
    <section class="school-welcome">
      <div class="teacher-avatar" aria-hidden="true"><span>👩🏻‍🏫</span><i>✨</i></div>
      <div class="teacher-bubble"><small>果粒橙老师</small><h1>今天想学什么？</h1><p>选一节课，老师会边讲边带你做。</p><button onclick="speakSchoolWelcome()">🔊 听老师说</button></div>
    </section>
    <div class="subject-tabs" role="tablist" aria-label="选择学科">
      <button class="subject-tab chinese ${subject==='语文'?'active':''}" onclick="showSubject('语文')"><span>📕</span><b>语文课</b><small>认字 · 拼音 · 阅读</small></button>
      <button class="subject-tab math ${subject==='数学'?'active':''}" onclick="showSubject('数学')"><span>🔢</span><b>数学课</b><small>数数 · 计算 · 图形</small></button>
    </div>
    <section class="study-progress" aria-label="学习进度"><div><b>${subject}小脚印</b><span>⭐ ${doneCount} 课</span></div><i><em style="width:${percent}%"></em></i><small>${doneCount?`已经学会 ${doneCount} 课，继续加油！`:'学完一课，就会得到一颗小星星。'}</small></section>
    ${next?`<button class="next-course" onclick="openCourse('${subject}',${all.indexOf(next)})"><span class="next-course-icon">${next.icon}</span><span><small>老师推荐从这里开始</small><b>${esc(next.title)}</b></span><strong>开始 ▶</strong></button>`:''}
    <h2 class="school-section-title"><span>${unitIcon(activeUnit)}</span> 选一个小主题</h2>
    <div class="unit-rail">${units.map((u,i)=>`<button class="unit-chip ${u===activeUnit?'active':''}" onclick="selectCourseUnit(${i})"><span>${unitIcon(u)}</span><b>${esc(u)}</b></button>`).join('')}</div>
    <div class="course-list">${unitItems.map((x,i)=>{const finished=done.includes(courseKey(x));return `<button class="course-card ${finished?'finished':''}" onclick="openCourse('${subject}',${all.indexOf(x)})"><i>${x.icon}</i><span><small>第 ${i+1} 课</small><b>${esc(x.title)}</b><em>${finished?'再听一遍':'点我上课'}</em></span><strong>${finished?'✓':'▶'}</strong></button>`}).join('')}</div>
  </div>`
}
function speakSchoolWelcome(){stopAudio();playClassroomText('老师在这里。点一节喜欢的课，我们一起开始吧。')}
function showSubject(subject){state.subject=subject;state.courseUnit=null;appEl.innerHTML=renderSchool();scrollTo(0,0);stopAudio();playClassroomText(`果粒橙小朋友，选一节${subject}课，我们一起学吧。`)}
function selectCourseUnit(index){const items=(window.GRADE_ONE_COURSES||[]).filter(x=>x.subject===(state.subject||'语文')),units=[...new Set(items.map(x=>x.unit))];state.courseUnit=units[index]||units[0];appEl.innerHTML=renderSchool();document.querySelector('.school-section-title')?.scrollIntoView({behavior:'smooth',block:'start'})}
function openCourse(subject,index){state.subject=subject;state.course=(window.GRADE_ONE_COURSES||[])[index];state.courseStep=0;state.courseAnswered=false;state.courseRewarded=false;go('classroom');speakCourse()}
function leaveClassroom(){stopAudio();if(state.stack.at(-1)?.page==='school')state.stack.pop();state.page='school';render()}
function visualParts(text){return esc(text).split(/(?:　+|\s{2,}|\n+)/).filter(Boolean).map((x,i)=>`<span style="--piece:${i}">${x}</span>`).join('')}
function courseVisual(course,step){return step===2?(typeof course.quizVisual==='string'&&course.quizVisual.trim()?course.quizVisual:course.question):course.visual}
function renderClassroom(){
  const c=state.course;if(!c)return renderSchool();const step=state.courseStep||0,text=step===0?c.intro:step===1?c.demo:c.question,labels=[['👂','听老师'],['👀','看一看'],['🙋','我来答']],theme=c.subject==='语文'?'chinese':'math';
  return `<div class="classroom classroom-${theme}">
    <div class="classroom-head"><button class="class-back" onclick="leaveClassroom()" aria-label="回到课程列表">←</button><div><small>${esc(c.subject)} · ${esc(c.unit)}</small><h1>${c.icon} ${esc(c.title)}</h1></div><span class="class-star">⭐</span></div>
    <div class="class-steps">${labels.map((x,i)=>`<div class="${i===step?'now':i<step?'done':''}"><span>${i<step?'✓':x[0]}</span><b>${x[1]}</b></div>`).join('')}</div>
    <article class="teacher-card" id="teacherCard">
      <div class="teacher-scene"><div class="mini-teacher"><span>👩🏻‍🏫</span><i></i></div><div class="teacher-says"><small>果粒橙老师</small><b>${step===0?'小耳朵准备好了吗？':step===1?'一起看图想一想':'轮到你来试一试'}</b></div><span class="sound-waves" aria-hidden="true">)))</span></div>
      <div class="lesson-visual ${step===2&&!(typeof c.quizVisual==='string'&&c.quizVisual.trim())?'is-question':''}">${visualParts(courseVisual(c,step))}</div>
      <div class="lesson-talk"><span class="talk-icon">${labels[step][0]}</span><p>${esc(text)}</p></div>
      <button class="listen-teacher" id="listenTeacher" onclick="speakCourse()">🔊 再听老师讲一遍</button>
    </article>
    ${step===2?`<section class="answer-stage"><h2>点一个答案</h2><div class="course-answers">${c.choices.map((x,i)=>`<button onclick="courseAnswer(this,${i})"><span>${['①','②','③'][i]||'●'}</span><b>${esc(x)}</b></button>`).join('')}</div><div class="message" id="courseMessage" aria-live="polite">听一听，想一想，再点答案</div></section>`:''}
    <div class="class-actions"><button onclick="courseTurn(-1)" ${step===0?'disabled':''}><span>←</span> 前一步</button><button class="primary" id="courseNextBtn" onclick="courseTurn(1)" ${step===2&&!state.courseAnswered?'disabled':''}>${step===2?(state.courseAnswered?'我学会啦 ⭐':'先答一题'):'下一步'} <span>→</span></button></div>
    <details class="parent-tip"><summary>👨‍👩‍👧 给家长的小提示</summary><p>${esc(c.tip)}</p></details>
  </div>`
}
function speakCourse(){const c=state.course;if(!c)return;const step=state.courseStep||0,card=$('#teacherCard'),btn=$('#listenTeacher'),cleanup=()=>{card?.classList.remove('is-speaking');if(btn)btn.textContent='🔊 再听老师讲一遍'};stopAudio();if(state.muted){cleanup();return}card?.classList.add('is-speaking');if(btn)btn.textContent='🎧 老师正在讲…';playClassroomText(courseSpeech(c,step),cleanup)}
function courseTurn(d){stopAudio();if(d>0&&(state.courseStep||0)===2){if(!state.courseAnswered)return;if(completeCourse(state.course))reward();leaveClassroom();playClassroomText('这节课学完啦！果粒橙小朋友认真听、认真想，真棒！');return}state.courseStep=Math.max(0,Math.min(2,(state.courseStep||0)+d));state.courseAnswered=false;render();speakCourse()}
function courseAnswer(el,index){if(state.courseAnswered)return;state.courseAnswered=true;const buttons=[...document.querySelectorAll('.course-answers button')];buttons.forEach(b=>b.disabled=true);const right=state.course.choices[state.course.answer],next=$('#courseNextBtn');if(next){next.disabled=false;next.innerHTML='我学会啦 ⭐ <span>→</span>'}stopAudio();if(index===state.course.answer){el.classList.add('good');$('#courseMessage').textContent='答对啦！送你一颗星 ⭐';if(!state.courseRewarded){state.courseRewarded=true;reward()}playClassroomText(`答对啦！${right}就是正确答案。你听得真认真。`)}else{el.classList.add('bad');buttons[state.course.answer]?.classList.add('good');$('#courseMessage').textContent='没关系，老师陪你一起看答案';playClassroomText(`没关系，我们一起看看。正确答案是${right}。`)}}
function renderCreate(){return shell('创意乐园','自由探索，没有标准答案',`<div class="activity-grid"><button class="activity" onclick="go('coloring')"><span class="icon">🎨</span><b>涂颜色</b><small>点一点，给图画上色</small></button><button class="activity" onclick="go('draw')"><span class="icon">🖍️</span><b>自由画画</b><small>用手指画出想象</small></button><button class="activity" onclick="go('piano')"><span class="icon">🎹</span><b>音乐小琴</b><small>听听不同的声音</small></button><button class="activity" onclick="openGame('match')"><span class="icon">🧩</span><b>图形配对</b><small>观察和判断</small></button></div>`)}
function renderColoring(){const cur=state.coloring||colorings[0],fill=state.fill||palette[0];return `<div class="lesson coloring-game"><h2>🎨 涂颜色</h2><p>选图画、选颜色，再点要上色的地方</p><div class="coloring-choices">${colorings.map(x=>`<button class="coloring-choice ${x[0]===cur[0]?'active':''}" onclick="chooseColoring('${x[0]}')"><img src="img/coloring/${x[0]}.png" alt=""><span>${x[1]}</span></button>`).join('')}</div><div class="palette">${palette.map(c=>`<button class="${fill===c?'active':''}" style="background:${c}" onclick="setFill('${c}',this)" aria-label="选择颜色"></button>`).join('')}</div><canvas id="colorPad" width="560" height="560"></canvas><div class="color-actions"><button id="colorUndo" onclick="undoColoring()" disabled>↶ 撤销一步</button><button onclick="resetColoring()">↻ 重新涂</button><button class="finish-coloring" onclick="finishArtwork('colorPad')">⭐ 保存作品</button><button onclick="nextColoring()">换一张 →</button></div><div class="art-save-message" id="artSaveMessage" aria-live="polite"></div></div>`}
function initColoring(){const c=$('#colorPad');if(!c)return;const x=c.getContext('2d',{willReadFrequently:true}),img=new Image();state.colorUndo=[];state.colorReady=false;img.onload=()=>{x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);const r=Math.min(c.width/img.width,c.height/img.height),w=img.width*r,h=img.height*r;x.drawImage(img,(c.width-w)/2,(c.height-h)/2,w,h);state.colorReady=true};img.src='img/coloring/'+(state.coloring||colorings[0])[0]+'.png';c.onpointerup=e=>{if(!state.colorReady)return;e.preventDefault();const r=c.getBoundingClientRect(),sx=Math.floor((e.clientX-r.left)*c.width/r.width),sy=Math.floor((e.clientY-r.top)*c.height/r.height),before=x.getImageData(0,0,c.width,c.height);if(!floodFill(x,sx,sy,state.fill||palette[0]))return;state.colorUndo.push(before);if(state.colorUndo.length>8)state.colorUndo.shift();$('#colorUndo').disabled=false;tone(520,.08)};state.colorCtx=x}
function floodFill(ctx,sx,sy,hex){const im=ctx.getImageData(0,0,ctx.canvas.width,ctx.canvas.height),d=im.data,w=im.width,h=im.height,i0=(sy*w+sx)*4,target=[d[i0],d[i0+1],d[i0+2]],rgb=hex.match(/\w\w/g).map(x=>parseInt(x,16));if(target.every((v,i)=>Math.abs(v-rgb[i])<8)||(target[0]<80&&target[1]<80&&target[2]<80))return false;const seen=new Uint8Array(w*h),q=[sx,sy];let head=0,count=0;while(head<q.length&&count<w*h){const x=q[head++],y=q[head++],p=y*w+x;if(x<0||y<0||x>=w||y>=h||seen[p])continue;seen[p]=1;const i=p*4;if(Math.abs(d[i]-target[0])>38||Math.abs(d[i+1]-target[1])>38||Math.abs(d[i+2]-target[2])>38)continue;d[i]=rgb[0];d[i+1]=rgb[1];d[i+2]=rgb[2];count++;q.push(x+1,y,x-1,y,x,y+1,x,y-1)}if(!count)return false;ctx.putImageData(im,0,0);return true}
function chooseColoring(id){state.coloring=colorings.find(x=>x[0]===id);state.colorUndo=[];render()}function nextColoring(){const i=colorings.findIndex(x=>x[0]===(state.coloring||colorings[0])[0]);state.coloring=colorings[(i+1)%colorings.length];state.colorUndo=[];render()}function setFill(c,el){state.fill=c;document.querySelectorAll('.palette button').forEach(b=>b.classList.remove('active'));el.classList.add('active')}function undoColoring(){const im=state.colorUndo?.pop();if(!im||!state.colorCtx)return;state.colorCtx.putImageData(im,0,0);$('#colorUndo').disabled=!state.colorUndo.length}function resetColoring(){state.colorUndo=[];render()}
function renderDraw(){if(window.ART_STUDIO)return window.ART_STUDIO.render();const pen=state.pen||'#ff6b6b',size=state.penSize||14,colors=['#ff6b6b','#ffb84d','#58c792','#4b9cff','#9b78e8','#344052'],tool=state.drawTool||'pen';return `<div class="lesson draw-game"><h2>🖍️ 自由画画</h2><p>可以画线，也可以选一枚贴纸点在画板上</p><div class="draw-tools"><div class="draw-colors">${colors.map(c=>`<button class="draw-color ${tool==='pen'&&pen===c?'active':''}" style="background:${c}" onclick="setPen('${c}',this)" aria-label="选择颜色"></button>`).join('')}<button class="eraser-btn ${tool==='pen'&&pen==='#fff'?'active':''}" onclick="setPen('#fff',this)">🧽 橡皮</button></div><div class="brush-sizes"><span>笔头</span>${[[8,'小'],[14,'中'],[26,'大']].map(x=>`<button class="brush-btn ${size===x[0]?'active':''}" onclick="setBrush(${x[0]},this)"><i style="width:${x[0]}px;height:${x[0]}px"></i>${x[1]}</button>`).join('')}</div><div class="stamp-tools"><span>贴纸</span>${drawStamps.map(s=>`<button class="stamp-btn ${tool==='stamp'&&state.stamp===s?'active':''}" onclick="setStamp('${s}',this)" aria-label="选择${s}贴纸">${s}</button>`).join('')}</div></div><canvas id="drawPad" width="700" height="700" aria-label="自由画板"></canvas><div class="draw-actions"><button id="drawUndo" onclick="undoDrawing()" disabled>↶ 撤销一步</button><button onclick="clearPad()">↻ 擦干净</button><button class="finish-drawing" onclick="finishArtwork('drawPad')">⭐ 保存作品</button></div><div class="art-save-message" id="artSaveMessage" aria-live="polite"></div></div>`}
function initDraw(){if(window.ART_STUDIO){window.ART_STUDIO.mount(appEl);return}const c=$('#drawPad');if(!c)return;const x=c.getContext('2d');x.lineCap='round';x.lineJoin='round';state.drawUndo=[];state.pad=x;let down=false;const point=e=>{const r=c.getBoundingClientRect();return[(e.clientX-r.left)*c.width/r.width,(e.clientY-r.top)*c.height/r.height]};const style=()=>{x.lineWidth=state.penSize||14;x.strokeStyle=state.pen||'#ff6b6b';x.fillStyle=state.pen||'#ff6b6b'};c.onpointerdown=e=>{e.preventDefault();const[a,b]=point(e);rememberDrawing();if(state.drawTool==='stamp'){x.save();x.font=`${Math.max(64,(state.penSize||14)*5)}px "Apple Color Emoji","Segoe UI Emoji",sans-serif`;x.textAlign='center';x.textBaseline='middle';x.fillText(state.stamp||'⭐',a,b);x.restore();tone(659,.08);return}down=true;c.setPointerCapture?.(e.pointerId);style();x.beginPath();x.arc(a,b,(state.penSize||14)/2,0,Math.PI*2);x.fill();x.beginPath();x.moveTo(a,b)};c.onpointermove=e=>{if(!down)return;e.preventDefault();const[a,b]=point(e);style();x.lineTo(a,b);x.stroke()};c.onpointerup=c.onpointercancel=e=>{if(!down)return;down=false;c.releasePointerCapture?.(e.pointerId)}}
function setPen(c,el){state.pen=c;state.drawTool='pen';document.querySelectorAll('.draw-color,.eraser-btn,.stamp-btn').forEach(b=>b.classList.remove('active'));el?.classList.add('active')}function setBrush(n,el){state.penSize=n;document.querySelectorAll('.brush-btn').forEach(b=>b.classList.remove('active'));el?.classList.add('active')}function setStamp(s,el){state.stamp=s;state.drawTool='stamp';document.querySelectorAll('.draw-color,.eraser-btn,.stamp-btn').forEach(b=>b.classList.remove('active'));el?.classList.add('active')}function artSaveMessage(text){const el=$('#artSaveMessage');if(el)el.textContent=text}function artworkSaved(){reward();artSaveMessage('作品保存好啦！');speak('画得真漂亮')}function saveArtwork(id){const source=$('#'+id);if(!source)return;artSaveMessage('正在准备作品…');try{const out=document.createElement('canvas');out.width=source.width;out.height=source.height;const x=out.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,out.width,out.height);x.drawImage(source,0,0);const data=out.toDataURL('image/png'),name='果粒橙小朋友作品-'+Date.now()+'.png';if(typeof File==='function'&&navigator.share&&navigator.canShare){const raw=atob(data.split(',')[1]),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);const file=new File([bytes],name,{type:'image/png'});if(navigator.canShare({files:[file]})){navigator.share({files:[file],title:'果粒橙小朋友的作品'}).then(artworkSaved).catch(e=>artSaveMessage(e?.name==='AbortError'?'可以继续画哦':'保存失败了，请再试一次'));return}}const a=document.createElement('a');a.href=data;a.download=name;document.body.appendChild(a);a.click();a.remove();artworkSaved()}catch(e){artSaveMessage('保存失败了，请再试一次')}}function finishArtwork(id){saveArtwork(id)}function rememberDrawing(){if(!state.pad)return;state.drawUndo=state.drawUndo||[];state.drawUndo.push(state.pad.getImageData(0,0,700,700));if(state.drawUndo.length>8)state.drawUndo.shift();const b=$('#drawUndo');if(b)b.disabled=false}function undoDrawing(){const im=state.drawUndo?.pop();if(!im||!state.pad)return;state.pad.putImageData(im,0,0);const b=$('#drawUndo');if(b)b.disabled=!state.drawUndo.length}function clearPad(){if(!state.pad)return;rememberDrawing();state.pad.clearRect(0,0,700,700)}
function renderPiano(){if(window.MUSIC_STUDIO)return window.MUSIC_STUDIO.render();const keys=[['do','#ff746c',261.6],['re','#ffad5c',293.7],['mi','#ffd65a',329.6],['fa','#6ed19d',349.2],['sol','#65b8ff',392],['la','#8b91ff',440],['si','#b788ed',493.9],['do','#ef7eba',523.3]];return `<div class="lesson"><h2>🎹 音乐小琴</h2><p>点琴键，听听声音有什么不同</p><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:18px 0">${keys.map(k=>`<button onclick="tone(${k[2]})" style="height:120px;border-radius:20px;background:${k[1]};color:white;font-size:20px;font-weight:900">${k[0]}</button>`).join('')}</div><button class="wide-btn" onclick="playSong()">▶ 听一段小星星</button></div>`}
function tone(freq,d=.35){if(state.muted)return;const C=window.AudioContext||window.webkitAudioContext;if(!C)return;state.ctx=state.ctx||new C();const o=state.ctx.createOscillator(),g=state.ctx.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.15,state.ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,state.ctx.currentTime+d);o.connect(g).connect(state.ctx.destination);o.start();o.stop(state.ctx.currentTime+d)}function playSong(){[261.6,261.6,392,392,440,440,392].forEach((n,i)=>later(()=>tone(n,.42),i*480))}
function render(){syncGameMenuUrl();document.body.classList.toggle('playing-cozy-game',['pet','garden'].includes(state.page));const pages={home:renderHome,pet:()=>COZY.renderPet(),garden:()=>COZY.renderGarden(),videos:()=>HOME.renderVideos(),school:renderSchool,classroom:renderClassroom,stories:()=>renderStories(state.storyFilter),reader:renderReader,learn:renderLearn,lesson:renderLesson,games:renderGames,game:renderGame,create:renderCreate,coloring:renderColoring,draw:renderDraw,piano:renderPiano,writing:()=>window.WRITING.render()};appEl.innerHTML=(pages[state.page]||renderHome)();document.body.classList.toggle('princess-mode',state.page==='game'&&state.game==='princess');if(['coloring','draw','piano'].includes(state.page))appEl.insertAdjacentHTML('afterbegin',creativeGameNav());document.body.classList.toggle('playing-mini-game',state.page==='game'||['coloring','draw','piano'].includes(state.page));document.body.classList.toggle('playing-writing-studio',state.page==='writing');$('#backBtn').classList.toggle('hidden',state.page==='home'||state.page==='reader'||state.page==='classroom'||state.page==='game'||['draw','piano','writing'].includes(state.page)||(state.page==='lesson'&&state.learn==='recognition'));$('#bottomNav').classList.toggle('hidden',['reader','classroom','game','lesson','coloring','draw','piano','writing'].includes(state.page));document.querySelectorAll('#bottomNav button').forEach(b=>b.classList.toggle('active',b.dataset.go===state.page));$('#stars').textContent=state.stars;if(state.page==='draw')initDraw();if(state.page==='piano')window.MUSIC_STUDIO?.mount(appEl);if(state.page==='writing')window.WRITING.mount(appEl);if(state.page==='coloring')initColoring();if(state.page==='game'&&state.game==='pawMaze')initPawMaze();if(state.page==='game'&&state.game==='snakeFruit')initSnakeFruit();if(state.page==='game'&&state.game==='beeGarden')initBeeGarden();if(state.page==='game'&&state.game==='rocketStars')initRocketStars();if(state.page==='game'&&state.game==='fruitBasket')initFruitBasket();if(state.page==='game'&&state.game==='colorTrain')initColorTrain();if(state.page==='game'&&state.game==='fireflyTrail')initFireflyTrail();if(state.page==='game'&&window.NEW_GAMES?.entries.some(g=>g.id===state.game))window.NEW_GAMES.mount(state.game,appEl);if(['pet','garden'].includes(state.page))COZY.mount();scrollTo(0,0);if(state.page==='games')restoreGameMenu();if(state.page==='stories')restoreStoryMenu();window.KNOW?.afterRender()}
// Native update navigation was introduced in Android 2.3.0. The old online
// wrapper also identifies itself as GuolichengTablet, but cannot handle it.
function supportsAndroidAppUpdates(userAgent){
  const version=String(userAgent||'').match(/(?:^|\s)GuolichengTablet\/(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-Offline)?(?=\s|$)/);
  if(!version)return false;
  const [major,minor,patch]=version.slice(1).map(Number);
  if(![major,minor,patch].every(Number.isSafeInteger))return false;
  return major>2||(major===2&&minor>=3);
}
$('#backBtn').onclick=back;$('#homeBtn').onclick=()=>go('home');$('#soundBtn').onclick=()=>{state.muted=!state.muted;window.MUSIC_STUDIO?.setMuted(state.muted);if(state.muted){state.readerAuto=false;state.readerPaused=false}stopAudio();$('#teacherCard')?.classList.remove('is-speaking');const teacherButton=$('#listenTeacher');if(teacherButton)teacherButton.textContent='🔊 再听老师讲一遍';$('#soundBtn').textContent=state.muted?'🔇':'🔊';if(state.page==='reader')render()};document.querySelectorAll('#bottomNav button').forEach(b=>b.onclick=()=>go(b.dataset.go));if(typeof navigator!=='undefined'&&supportsAndroidAppUpdates(navigator.userAgent))$('#appUpdateBtn')?.classList.remove('hidden');
window.speak=speak;window.stopAudio=stopAudio;window.go=go;window.showBooks=showBooks;window.leaveReader=leaveReader;window.showSubject=showSubject;window.selectCourseUnit=selectCourseUnit;window.speakSchoolWelcome=speakSchoolWelcome;window.openCourse=openCourse;window.leaveClassroom=leaveClassroom;window.speakCourse=speakCourse;window.courseTurn=courseTurn;window.courseAnswer=courseAnswer;window.openBook=openBook;window.artFallback=artFallback;window.turn=turn;window.readPage=readPage;window.toggleAutoRead=toggleAutoRead;window.readAutoPage=readAutoPage;window.toggleFav=toggleFav;window.openLearn=openLearn;window.learnTurn=learnTurn;window.speakWord=speakWord;window.openGame=openGame;window.gamePrompt=gamePrompt;window.answer=answer;window.flipCard=flipCard;window.sortAnswer=sortAnswer;window.popBalloon=popBalloon;window.brandAnswer=brandAnswer;window.mazeMove=mazeMove;window.orderPick=orderPick;window.resetSnakeFruit=resetSnakeFruit;window.chooseColoring=chooseColoring;window.nextColoring=nextColoring;window.setFill=setFill;window.undoColoring=undoColoring;window.resetColoring=resetColoring;window.setPen=setPen;window.setBrush=setBrush;window.setStamp=setStamp;window.finishArtwork=finishArtwork;window.undoDrawing=undoDrawing;window.clearPad=clearPad;window.tone=tone;window.playSong=playSong;Object.assign(window,{rememberGameMenu,categoryGameHelp,creativeGameHelp,selectGameCategory,leaveGame,gameHelp,restartCurrentGame,leaveCreativeGame,restartCreativeGame,popBathBubble,fruitBasketDrop,colorTrainDrop,shadowAnswer,startRhythm,tapRhythm});window.state=state;window.render=render;render();
