const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function boot(saved){const store=new Map(saved?[[ 'kid-cozy-home-v1',saved]]:[]);const w={localStorage:{getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v)},render(){},speak(){},go(){},state:{page:'garden'}};vm.runInNewContext(fs.readFileSync('cozy-games.js','utf8'),{window:w});return {api:w.COZY,store}}
test('plant, two waters, harvest once and restore progress',()=>{const {api,store}=boot();api.plot(0);assert.equal(api._test.get().plots[0].stage,1);api.tool('water');api.plot(0);api.plot(0);assert.equal(api._test.get().plots[0].stage,3);api.tool('harvest');api.plot(0);api.plot(0);assert.equal(api._test.get().basket,1);assert.equal(api._test.get().stars,1);assert.equal(boot(store.get('kid-cozy-home-v1')).api._test.get().basket,1)});
test('bad actions cannot replace crops or harvest unfinished plants',()=>{const {api}=boot();api.plot(0);api.seed('corn');api.plot(0);assert.equal(api._test.get().plots[0].crop,'carrot');api.tool('harvest');api.plot(0);assert.equal(api._test.get().basket,0);api.plot(-1);api.plot(99);api.tool('oops');assert.equal(api._test.get().plots.length,6)});
test('pet care capped and new round only after all needs filled',()=>{const {api}=boot();api.care(0);api.newDay();assert.equal(api._test.get().care[0],1);for(let i=0;i<3;i++)for(let j=0;j<5;j++)api.care(i);assert.equal(JSON.stringify(api._test.get().care),'[3,3,3]');api.newDay();assert.equal(JSON.stringify(api._test.get().care),'[0,0,0]')});
test('corrupt persisted data is bounded and invalid crops ignored',()=>{const {api}=boot(JSON.stringify({pet:'<script>',care:[-2,999,'x'],basket:-99,plots:[{crop:'carrot',stage:999},{crop:'bad',stage:3}]}));assert.equal(api._test.get().pet,'bunny');assert.equal(JSON.stringify(api._test.get().care),'[0,3,0]');assert.equal(api._test.get().plots[0].stage,3);assert.equal(api._test.get().plots[1].crop,null)});
test('offline drawing page and dependencies included with isolated scope',()=>{const m=JSON.parse(fs.readFileSync('offline/assets.json'));for(const p of ['/offline/artist.html','/little-artist/app.js','/little-artist/magnet.js','/little-artist/templates.js','/little-artist/style.css'])assert.ok(m.files.some(f=>f.url===p));assert.match(fs.readFileSync('offline/artist.html','utf8'),/base href="\/little-artist\/"/);assert.match(fs.readFileSync('little-artist/app.js','utf8'),/setPalmGuard\(false\)/)});
test('pet mood reflects play and meals, with species-specific drawing',()=>{const {api}=boot();assert.match(api.renderPet(),/pet-mood-lonely/);api.care(2);assert.match(api.renderPet(),/pet-mood-happy/);api.care(0);api.care(0);api.care(0);assert.match(api.renderPet(),/pet-mood-full/);assert.match(api.renderPet(),/pet-belly-paw/);api.choosePet('kitten');assert.match(api.renderPet(),/pet-species-kitten/);assert.match(api.renderPet(),/M51 142 28 136/);api.choosePet('puppy');assert.match(api.renderPet(),/pet-species-puppy/)});
test('pet activities use complete scenes and rotate three sports courts',()=>{const {api}=boot();api.care(0);assert.match(api.renderPet(),/data-pet-scene="dining"/);assert.match(api.renderPet(),/scene-table/);api.care(1);assert.match(api.renderPet(),/data-pet-scene="bath"/);assert.match(api.renderPet(),/scene-tub/);assert.match(api.renderPet(),/scene-water/);for(const court of ['basketball','football','tennis','basketball']){api.care(2);assert.match(api.renderPet(),new RegExp('data-court="'+court+'"'));}api.homeScene();assert.doesNotMatch(api.renderPet(),/data-pet-scene/);api.care(0);api.choosePet('kitten');assert.doesNotMatch(api.renderPet(),/data-pet-scene/)});
test('full pets can keep interacting without adding extra hearts',()=>{const {api}=boot();for(let i=0;i<7;i++)api.care(0);assert.equal(api._test.get().care[0],3);assert.match(api.renderPet(),/scene-dining scene-active/)});
test('activity expiry keeps its scene and does not repaint a page the child left',()=>{let callback;const w={localStorage:{getItem:()=>null,setItem(){}},state:{page:'pet'},render(){this.renders=(this.renders||0)+1},speak(){},setTimeout(fn){callback=fn;return 1},clearTimeout(){}};vm.runInNewContext(fs.readFileSync('cozy-games.js','utf8'),{window:w,document:{querySelector:()=>null}});w.COZY.care(1);w.COZY.mount();callback();assert.match(w.COZY.renderPet(),/scene-bath scene-rest/);w.COZY.care(2);w.COZY.mount();w.state.page='home';const before=w.renders;callback();assert.equal(w.renders,before)});
