(() => {
'use strict';
window.KidGames ||= {};
const W=8,H=8;
const dirs={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]};
const same=(a,b)=>a[0]===b[0]&&a[1]===b[1];
const key=p=>p.join(',');
const arrows='<button data-action="up" type="button">↑ 上</button><button data-action="left" type="button">← 左</button><button data-action="down" type="button">↓ 下</button><button data-action="right" type="button">右 →</button>';
function render(api,w,h,cell){api.board.innerHTML=`<div class="panel-stack"><div class="grid-game" style="grid-template-columns:repeat(${w},minmax(0,1fr))">${Array.from({length:w*h},(_,n)=>{const x=n%w,y=Math.floor(n/w),c=cell(x,y)||{};return `<div class="grid-cell ${c.class||''}" aria-label="${c.label||''}">${window.kidIcon(c.emoji)||''}</div>`}).join('')}</div><p class="board-caption">${api.caption||''}</p></div>`}
function swipe(api,act){let sx=0,sy=0;const down=e=>{sx=e.touches[0].clientX;sy=e.touches[0].clientY},up=e=>{const dx=e.changedTouches[0].clientX-sx,dy=e.changedTouches[0].clientY-sy;if(Math.max(Math.abs(dx),Math.abs(dy))<25)return;act(Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'down':'up')};api.board.addEventListener('touchstart',down,{passive:true});api.board.addEventListener('touchend',up,{passive:true});return()=>{api.board.removeEventListener('touchstart',down);api.board.removeEventListener('touchend',up)}}
function movement(api){api.controls.innerHTML=arrows;return()=>{}}
function snake(api){let body,apple,eaten,cleanup=()=>{};const spawn=()=>{const free=[];for(let y=0;y<H;y++)for(let x=0;x<W;x++)if(!body.some(p=>p[0]===x&&p[1]===y))free.push([x,y]);return free[Math.floor(Math.random()*free.length)]};function draw(){api.caption='每走一步都要想好方向';render(api,W,H,(x,y)=>{if(same([x,y],body[0]))return{emoji:'🐍',class:'head'};if(body.some(p=>p[0]===x&&p[1]===y))return{emoji:'',class:'snake'};if(same([x,y],apple))return{emoji:'🍎'};return{}});api.setMetric(`苹果 ${eaten} / 5`)}function move(dir){if(!dirs[dir])return;const [dx,dy]=dirs[dir],head=[body[0][0]+dx,body[0][1]+dy],grow=same(head,apple);if(head[0]<0||head[0]>=W||head[1]<0||head[1]>=H||body.slice(0,grow?body.length:body.length-1).some(p=>same(p,head))){api.fail('小蛇碰到了边缘。看看路线，再试一次！');return}body=[head,...body.slice(0,grow?body.length:body.length-1)];api.sound(true,420);if(grow){eaten++;api.sound(true,720);api.setStatus(`吃到第 ${eaten} 颗苹果！`,eaten===3);if(eaten>=5){api.finish('小蛇吃到了五颗苹果，路线规划得真棒！');return}apple=spawn()}draw()}return{start(){body=[[3,3],[2,3],[1,3]];eaten=0;apple=[5,3];cleanup=movement(api,move);draw()},action:move,destroy(){cleanup()}}}
const mazeRows=['########','#S.....#','#.###..#','#...#..#','##..#..#','#......#','#..###G#','########'];
const mazeOpen=(x,y)=>mazeRows[y]?.[x]&&mazeRows[y][x]!=='#';
function maze(api){let p,steps,cleanup=()=>{};function draw(){api.caption='走过的路可以再走，但要找到星星';render(api,8,8,(x,y)=>{if(!mazeOpen(x,y))return{class:'wall'};if(same(p,[x,y]))return{emoji:'🐣'};if(x===6&&y===6)return{emoji:'⭐',class:'goal'};return{}});api.setMetric(`走了 ${steps} 步`)}function move(dir){if(!dirs[dir])return;const [dx,dy]=dirs[dir],x=p[0]+dx,y=p[1]+dy;if(!mazeOpen(x,y)){api.sound(false);api.setStatus('这里有墙，换一条路试试');return}p=[x,y];steps++;api.sound();if(x===6&&y===6){api.finish(`你走了 ${steps} 步，成功找到星星！`);return}draw()}return{start(){p=[1,1];steps=0;cleanup=movement(api,move);draw()},action:move,destroy(){cleanup()}}}
function pac(api){let p,ghost,dots,lives,turn,cleanup=()=>{};function draw(){api.caption='黄色小伙伴吃豆豆，粉色小怪会走动';render(api,8,8,(x,y)=>{if(!mazeOpen(x,y))return{class:'wall'};if(same(p,[x,y]))return{emoji:'😋'};if(same(ghost,[x,y]))return{emoji:'👻',class:'ghost'};if(dots.has(key([x,y])))return{emoji:'🟡'};return{}});api.setMetric(`豆豆 ${5-dots.size} / 5 · ❤️ ${lives}`)}function move(dir){if(!dirs[dir])return;const [dx,dy]=dirs[dir],next=[p[0]+dx,p[1]+dy];if(!mazeOpen(...next)){api.sound(false);return}p=next;turn++;if(dots.delete(key(p))){api.sound(true,760);api.setStatus('吃到一颗豆豆！')}else api.sound(true,430);if(!dots.size){api.finish('五颗豆豆都找到了，迷宫高手！');return}const choices=Object.values(dirs).map(([a,b])=>[ghost[0]+a,ghost[1]+b]).filter(([x,y])=>mazeOpen(x,y)&&!same([x,y],p));if(choices.length&&turn%2===0)ghost=choices[Math.floor(Math.random()*choices.length)];if(same(p,ghost)){lives--;p=[1,1];ghost=[5,5];api.sound(false);api.setStatus(`碰到小怪啦，还有 ${lives} 次机会`,true);if(!lives){api.fail('这次小怪赢啦。再试一次，记得绕开它！');return}}draw()}return{start(){p=[1,1];ghost=[5,5];dots=new Set(['2,1','5,1','1,3','3,5','6,6']);lives=3;turn=0;cleanup=movement(api,move);draw()},action:move,destroy(){cleanup()}}}
function frog(api){let p,lives,turn,cleanup=()=>{};const isCar=(x,y,t)=>y>0&&y<6&&((x+7*30+(y%2?1:-1)*t+[0,2,4,1,6,1][y])%7)<(y===3?2:1);function draw(){api.caption='观察车车位置，再走下一步';render(api,7,7,(x,y)=>{if(same(p,[x,y]))return{emoji:'🐸'};if(y===0)return{emoji:x===3?'🏡':'',class:'goal'};if(y===6)return{class:'target'};return isCar(x,y,turn)?{emoji:'🚗',class:'road'}:{class:'road'}});api.setMetric(`❤️ ${lives} · 前进 ${6-p[1]} 格`)}function move(dir){if(!dirs[dir])return;const [dx,dy]=dirs[dir];p=[Math.max(0,Math.min(6,p[0]+dx)),Math.max(0,Math.min(6,p[1]+dy))];turn++;api.sound(true,440);if(p[1]===0){api.finish('青蛙安全到家啦，你很会观察车车！');return}if(isCar(p[0],p[1],turn)){lives--;p=[3,6];api.sound(false);api.setStatus(`碰到车车了，还剩 ${lives} 次机会`,true);if(!lives){api.fail('车车太多啦。看准空隙再出发！');return}}draw()}return{start(){p=[3,6];lives=3;turn=0;cleanup=movement(api,move);draw()},action:move,destroy(){cleanup()}}}
function sokoban(api){let p,boxes,targets,steps,cleanup=()=>{};const walls=new Set();for(let x=0;x<8;x++){walls.add(`${x},0`);walls.add(`${x},7`)}for(let y=0;y<8;y++){walls.add(`0,${y}`);walls.add(`7,${y}`)}walls.add('4,3');walls.add('1,4');function draw(){api.caption='先走到箱子旁边，才能把它推走';render(api,8,8,(x,y)=>{const k=key([x,y]);if(walls.has(k))return{class:'wall'};if(same(p,[x,y]))return{emoji:'🧒'};if(boxes.has(k))return{emoji:'📦',class:'box'};if(targets.has(k))return{emoji:'✅',class:'target'};return{}});api.setMetric(`箱子 ${[...targets].filter(k=>boxes.has(k)).length} / 2 · ${steps} 步`)}function move(dir){if(!dirs[dir])return;const [dx,dy]=dirs[dir],next=[p[0]+dx,p[1]+dy],nk=key(next);if(walls.has(nk)){api.sound(false);return}if(boxes.has(nk)){const beyond=[next[0]+dx,next[1]+dy],bk=key(beyond);if(walls.has(bk)||boxes.has(bk)){api.sound(false);api.setStatus('箱子那边挡住啦，换个方向');return}boxes.delete(nk);boxes.add(bk);api.sound(true,650)}else api.sound(true,410);p=next;steps++;if([...targets].every(k=>boxes.has(k))){api.finish(`两个箱子都到家啦！一共走了 ${steps} 步。`);return}draw()}return{start(){p=[1,1];boxes=new Set(['3,2','3,4']);targets=new Set(['5,2','5,4']);steps=0;cleanup=movement(api,move);draw()},action:move,destroy(){cleanup()}}}
Object.assign(window.KidGames,{snake,maze,pac,frog,sokoban});
})();
