(() => {
'use strict';
window.KidGames ||= {};
const rand=n=>Math.floor(Math.random()*n);
function memory(api){let cards,open,done,lock,timer=null,tries;const icons=['🐶','🐱','🐼','🦊','🐸','🐻','🐰','🦁'];function draw(){api.board.innerHTML=`<div class="panel-stack"><div class="memory-grid">${cards.map((v,i)=>`<button class="${open.includes(i)||done.has(i)?'open':''}" data-action="flip" data-value="${i}" type="button" ${done.has(i)?'disabled':''} aria-label="第 ${i+1} 张牌">${window.kidIcon(open.includes(i)||done.has(i)?v:'❓')}</button>`).join('')}</div><p class="board-caption">记住位置，找出八组相同伙伴</p></div>`;api.setMetric(`配对 ${done.size/2} / 8 · 翻牌 ${tries} 次`)}function action(type,value){if(type!=='flip'||lock)return;const i=Number(value);if(done.has(i)||open.includes(i))return;open.push(i);tries++;api.sound(true,480);draw();if(open.length<2)return;lock=true;const [a,b]=open;if(cards[a]===cards[b]){timer=setTimeout(()=>{done.add(a);done.add(b);open=[];lock=false;api.sound(true,750);if(done.size===16){api.finish(`八组伙伴都找到了！翻牌 ${tries} 次。`);return}draw()},420)}else timer=setTimeout(()=>{open=[];lock=false;draw()},850)}return{start(){cards=[...icons,...icons].sort(()=>Math.random()-.5);open=[];done=new Set();lock=false;tries=0;draw()},action,destroy(){clearTimeout(timer)}}}
const pads=[['#f48f88','🔴'],['#f6cc74','🟡'],['#7bcfab','🟢'],['#9db6ec','🔵']];
function simon(api){let pattern,step,round,showing,timers=[];const later=(fn,ms)=>{const id=setTimeout(fn,ms);timers.push(id)};function draw(){api.board.innerHTML=`<div class="panel-stack"><div class="simon-grid">${pads.map(([color,icon],i)=>`<button style="background:${color}" data-action="pad" data-value="${i}" type="button" aria-label="${icon} 颜色键">${icon}</button>`).join('')}</div><p class="board-caption">先看颜色闪亮，再按同样顺序点</p></div>`;api.setMetric(`第 ${round} / 4 轮 · ${step} / ${pattern.length}`)}function show(){showing=true;step=0;draw();api.setStatus('仔细看颜色闪亮的顺序');for(let i=0;i<pattern.length;i++){later(()=>{const b=api.board.querySelector(`[data-value="${pattern[i]}"]`);b?.classList.add('lit');api.tone([330,392,494,587][pattern[i]],.24)},450+i*660);later(()=>api.board.querySelector(`[data-value="${pattern[i]}"]`)?.classList.remove('lit'),780+i*660)}later(()=>{showing=false;api.setStatus('轮到你啦，照着顺序点！',round===1)},600+pattern.length*660)}function action(type,value){if(type!=='pad'||showing)return;const i=Number(value);api.sound(i===pattern[step],[330,392,494,587][i]);if(i!==pattern[step]){showing=true;api.setStatus('顺序错了，看看再试一次',true);later(show,900);return}step++;draw();if(step===pattern.length){if(round===4){api.finish('四轮颜色顺序都记住了，记忆力真棒！');return}round++;pattern.push(rand(4));showing=true;api.setStatus('太棒啦，下一轮会更长！',true);later(show,900)}}return{start(){pattern=[rand(4),rand(4)];step=0;round=1;showing=true;draw();later(show,450)},action,destroy(){timers.forEach(clearTimeout);timers=[]}}}
const winLines=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];
const won=(board,player)=>winLines.some(line=>line.every(i=>board[i]===player));
function tictactoe(api){let cells,waiting,timer=null,rounds;function draw(){api.board.innerHTML=`<div class="panel-stack"><div class="strategy-grid" style="grid-template-columns:repeat(3,1fr)">${cells.map((v,i)=>`<button data-action="cell" data-value="${i}" type="button" ${v||waiting?'disabled':''}>${v==='o'?'⭕':v==='x'?'❌':''}</button>`).join('')}</div><p class="board-caption">你是 ⭕，小电脑是 ❌。连成三颗就赢。</p></div>`;api.setMetric(`第 ${rounds} 回合 · ${waiting?'电脑在想':'轮到你'}`)}function choose(){const free=cells.map((v,i)=>v?-1:i).filter(i=>i>=0);for(const symbol of ['x','o'])for(const i of free){cells[i]=symbol;const can=won(cells,symbol);cells[i]='';if(can&&(symbol==='x'||Math.random()<.7))return i}if(cells[4]==='')return 4;return free[rand(free.length)]}function action(type,value){if(type!=='cell'||waiting)return;const i=Number(value);if(cells[i])return;cells[i]='o';rounds++;api.sound(true,530);if(won(cells,'o')){api.finish('你先连成三颗，赢过小电脑啦！');return}if(cells.every(Boolean)){api.fail('这局打成平手，再来一局吧！');return}waiting=true;draw();timer=setTimeout(()=>{const j=choose();cells[j]='x';api.sound(true,360);if(won(cells,'x')){api.fail('小电脑先连成三颗。再试一次！');return}if(cells.every(Boolean)){api.fail('这局打成平手，再来一局吧！');return}waiting=false;draw()},420)}return{start(){cells=Array(9).fill('');waiting=false;rounds=0;draw()},action,destroy(){clearTimeout(timer)}}}
function connect4(api){let cells,waiting,timer=null,moves;const width=6,height=5;function drop(board,col,piece){for(let y=height-1;y>=0;y--)if(!board[y*width+col]){board[y*width+col]=piece;return true}return false}function win(board,piece){for(let y=0;y<height;y++)for(let x=0;x<width;x++)for(const [dx,dy] of [[1,0],[0,1],[1,1],[1,-1]]){let good=true;for(let k=0;k<4;k++){const xx=x+dx*k,yy=y+dy*k;if(xx<0||xx>=width||yy<0||yy>=height||board[yy*width+xx]!==piece){good=false;break}}if(good)return true}return false}function draw(){api.board.innerHTML=`<div class="panel-stack"><div class="strategy-grid" style="grid-template-columns:repeat(6,1fr);gap:4px">${cells.map((v,i)=>`<button data-action="column" data-value="${i%width}" type="button" style="background:#e0ebf3;border-radius:50%;font-size:clamp(20px,5vw,34px)">${v==='r'?'🔴':v==='y'?'🟡':'⚪'}</button>`).join('')}</div><p class="board-caption">点任意一列放下 🔴，连成四颗</p></div>`;api.setMetric(`落子 ${moves} 次 · ${waiting?'电脑在想':'轮到你'}`)}function choose(){const valid=Array.from({length:width},(_,i)=>i).filter(i=>!cells[i]);for(const piece of ['y','r'])for(const col of valid){const copy=cells.slice();drop(copy,col,piece);if(win(copy,piece)&&(piece==='y'||Math.random()<.55))return col}return valid[rand(valid.length)]}function action(type,value){if(type!=='column'||waiting)return;const col=Number(value);if(!drop(cells,col,'r')){api.sound(false);return}moves++;api.sound(true,520);if(win(cells,'r')){api.finish('四颗红棋连在一起啦！你赢了！');return}if(cells.every(Boolean)){api.fail('棋盘满了，换个策略再试一次！');return}waiting=true;draw();timer=setTimeout(()=>{drop(cells,choose(),'y');api.sound(true,330);if(win(cells,'y')){api.fail('小电脑先连成四颗。再试一次！');return}if(cells.every(Boolean)){api.fail('棋盘满了，再来一局吧！');return}waiting=false;draw()},400)}return{start(){cells=Array(width*height).fill('');waiting=false;moves=0;draw()},action,destroy(){clearTimeout(timer)}}}
function mole(api){let spot,count,timer=null;function draw(){api.board.innerHTML=`<div class="panel-stack"><div class="mole-grid">${Array.from({length:9},(_,i)=>`<button data-action="hole" data-value="${i}" type="button" aria-label="第 ${i+1} 个洞">${window.kidIcon(i===spot?'🐹':'🕳️')}</button>`).join('')}</div><p class="board-caption">地鼠会换洞，点中八次就赢</p></div>`;api.setMetric(`抓到 ${count} / 8`)}function change(){let next=rand(9);if(next===spot)next=(next+1)%9;spot=next;draw()}function action(type,value){if(type!=='hole')return;const i=Number(value);if(i!==spot){api.sound(false);return}count++;api.sound(true,750);if(count===4)api.setStatus('已经抓到四只了，加油！',true);if(count>=8){api.finish('八只地鼠都抓到了，反应真快！');return}change()}return{start(){spot=rand(9);count=0;draw();timer=setInterval(change,1450)},action,destroy(){clearInterval(timer)}}}
Object.assign(window.KidGames,{memory,simon,tictactoe,connect4,mole});
})();
